<div class="assessment test">
	<div class="mm-spinner" ng-if="CreateTestCtrl.getSettingsInProgress">
		<div>
			<img src="public/images/loader/spin.gif" alt="loading">
		</div>
	</div> 
	<div layout="column" class="container-box">
		<div class="create-test">
			<div class="header">
				<div class="container">
					<div layout="row" ng-if="CreateTestCtrl.testId">
						<a ui-sref="app.campaigns.EditTest({id: CreateTestCtrl.testId})"><img class="back" src="public/images/back.png" alt="back"></a>
						<h4 class="title" flex ng-bind="CreateTestCtrl.testObj.exam_type"></h4>
					</div>
					<h4 ng-if="!CreateTestCtrl.testId" class="title">Create a New Test</h4>
				</div>
			</div>
			<div class="section">
				<div class="container">
					<div class="test-pic"><img src="public/images/test_img.svg"></div>
					<div layout="row">
						<i flex></i>
						<div flex="70">
							<form name="createTestForm">
								<div layout="column">
									<div layout="row">
										<md-input-container flex class="md-block full-box">
											<span class="qst-label">What role is this test for? *</span>
											<!-- <label>What role is this test for? *</label> -->
											<input type="text" name="exam_type" ng-change="CreateTestCtrl.setTestName()" ng-model="CreateTestCtrl.testObj.exam_type" required aria-label="role">
											<div class="error-spacer"></div>
											<div ng-if="createTestForm.exam_type.$error.required && CreateTestCtrl.postCreateTestSubmitted" class="has-error-msg">Please enter job Role.</div>
										</md-input-container>
										<i flex="5"></i>
										<md-input-container flex class="md-block select-box">
											<span class="qst-label">Work Experience *</span>
											<label style="display:none">Please Select</label>
											<md-select name="work_experience" ng-model="CreateTestCtrl.testObj.work_experience" required>
												<md-option ng-repeat="type in CreateTestCtrl.experienceList" ng-value="type.experience_id">{{type.experience_name}}</md-option>
											</md-select>
											<div class="error-spacer"></div>
											<div ng-if="createTestForm.work_experience.$error.required && CreateTestCtrl.postCreateTestSubmitted"  class="has-error-msg">Please select Work Experience.</div>
										</md-input-container> 
									</div>
									<div layout="row">
										<md-input-container flex class="md-block full-box">
											<span class="qst-label">Test Name </span>
											<!-- <label>Test Name</label> -->
											<input type="text" name="exam_name" readonly ng-model="CreateTestCtrl.testObj.exam_name" style="background: #f0f0f0" aria-label="exam_name">
										</md-input-container>
										<i flex="5"></i>
										<md-input-container flex class="md-block full-box">
											<span class="qst-label">Duration (mins) * </span>
											<input type="text" check-char-zero ng-pattern="/(^[^0]$)|(^[1-9]\d{0,}$)/" name="max_duration" ng-model="CreateTestCtrl.testObj.max_duration" required aria-label="due">
											<div ng-if="createTestForm.max_duration.$error.required && CreateTestCtrl.postCreateTestSubmitted"  class="has-error-msg">Please enter Duration.</div>
											<div ng-if="createTestForm.max_duration.$error.pattern" class="has-error-msg">Duration should not be zero.</div>
										</md-input-container>
									</div>
									<div layout="row">
										<md-input-container flex class="md-block full-box">
											<span class="qst-label">Test Description Link(Optional)</span>
											<input type="text" name="description_url" ng-model="CreateTestCtrl.testObj.description_url" aria-label="link">
										</md-input-container>
										<i flex="5"></i>
										<i flex></i>
									</div>
								</div>
							</form>
						</div>
						<i flex></i>
					</div>
					<div layout="row" class="footer" ng-if="!CreateTestCtrl.testId">
						<i flex></i>
							<md-button ui-sref="app.campaigns.TestsList" class="cancel">Cancel</md-button>
							<md-button class="md-raised action" ng-disabled="CreateTestCtrl.postCreateTestInProgress" ng-click="CreateTestCtrl.postCreateTest(createTestForm)">CREATE TEST
								<img class="loader-dot" ng-if="CreateTestCtrl.postCreateTestInProgress" src="public/images/loader/dot.svg" alt="loading">
							</md-button>
						<i flex></i>
					</div>
					<div layout="row" class="footer" ng-if="CreateTestCtrl.testId">
						<i flex></i>
							<md-button ui-sref="app.campaigns.EditTest({id: CreateTestCtrl.testId})" class="cancel">Cancel</md-button>
							<md-button class="md-raised action" ng-disabled="CreateTestCtrl.postCreateTestInProgress" ng-click="CreateTestCtrl.postCreateTest(createTestForm)">EDIT TEST
								<img class="loader-dot" ng-if="CreateTestCtrl.postCreateTestInProgress" src="public/images/loader/dot.svg" alt="loading">
							</md-button>
						<i flex></i>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>