<div class="all-campaigns assessment">
   <div class="mm-spinner" ng-if="EditTestCtrl.getTestDetailsInProgress">
		<div>
			<img src="public/images/loader/spin.gif" alt="loading">
		</div>
	</div>
   <div class="container edit-test">
      <div class="row">
         <div class="col-sm-12" style="padding-bottom:50px;">
            <div class="box">
               <div class="box-header header clearfix">
                  <div layout="row">
                     <a ui-sref="app.campaigns.TestsList" class="link"><img src="public/images/back-arrow-black.svg" alt="back"></a>
                     <h4 class="title" flex ng-bind="EditTestCtrl.testDetails.exam_name"></h4>
                     <md-button ui-sref="app.campaigns.TestSettings({id:EditTestCtrl.testDetails.exam_id})" class="md-raised action">SETTINGS</md-button>
                     <md-button ui-sref="app.campaigns.CreateTest({examId:EditTestCtrl.testDetails.exam_id})" class="md-raised action">EDIT</md-button>
                  </div>
               </div>
               <div class="box-content tests-list">
                  <md-divider></md-divider>
                  <div layout="row" class="meta-data">
                     <div flex="40" class="ellipsis">
                        <span class="title">Assessment Name</span>
                        <span ng-bind="EditTestCtrl.testDetails.exam_name" title="{{EditTestCtrl.testDetails.exam_name}}"></span>
                     </div>
                     <i flex></i>
                     <div flex="15">
                        <span class="title">Work Experience</span>
                        <span ng-bind="EditTestCtrl.testDetails.experience_name"></span>
                     </div>
                     <div flex="15" class="duration">
                        <span class="title">Duration (mins)</span>
                        <span ng-bind="EditTestCtrl.testDetails.max_duration"></span>
                     </div>
                  </div>
                  <div id="grid" ng-if="EditTestCtrl.gridOptions.data.length" ui-grid="EditTestCtrl.gridOptions" class="grid edit" ui-grid-selection style="border: 0;height: calc(100vh - 360px) !important">
                     <div class="grid-msg-overlay" ng-if="EditTestCtrl.grid.inProgress">
                        <div class="msg">
                           <span>
                              <img src="public/images/loader/spin.gif" alt="loader" width="18%">
                           </span>
                        </div>
                     </div>
                     <div class="grid-msg-overlay" ng-if="!EditTestCtrl.gridOptions.data.length && !EditTestCtrl.grid.inProgress">
                        <div class="msg">
                           <span ng-bind="EditTestCtrl.grid.responseMsg"></span>
                        </div>
                     </div>	
                  </div>
               </div>
               <div class="box-footer footer clearfix" ng-style="{'background' : EditTestCtrl.testDetails.exam_question_list.length ? '' : '#fff'}">
                  <div layout="row" class="success-msg" ng-if="!EditTestCtrl.testDetails.exam_question_list.length">
                     <h5 class="text-center" flex>
                        <span class="icon"><i class="material-icons">done</i></span>
                        Your assessment has been successfully created.
                     </h5>
                  </div>
                  <div layout="row">
                     <i flex></i>
                     <md-button ui-sref="app.campaigns.QuestionAdd({ examId: EditTestCtrl.testDetails.exam_id})" ng-click="EditTestCtrl.setServieData()" class="md-raised action">ADD QUESTIONS</md-button>
                     <span class="or"> or </span>
                     <md-button ui-sref="app.campaigns.CreateQuestion({ mode:'add', id: 0, examId: EditTestCtrl.testDetails.exam_id})" ng-click="EditTestCtrl.setServieData()" class="md-raised action create-new">CREATE NEW QUESTION</md-button>
                     <i flex></i>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>

<!-- Action -->
<script type="text/ng-template" id="action.html">
	<div class="ui-grid-cell-contents ui-grid-details">
      <a class="name" ui-sref="app.campaigns.CreateQuestion({mode:'view', id:row.entity.question_id})" ng-click="grid.appScope.setServieData();$event.stopPropagation()"><img src="public/images/eye.png" alt="view"></a>
      <a class="name" ng-click="grid.appScope.deleteQuestion(COL_FIELD);$event.stopPropagation()"><img src="public/images/bin.png" alt="view"></a>
	</div>
</script>

