<div class="all-campaigns assessment">
    <div class="container">
        <div class="row">
            <div class="col-sm-12" style="padding-bottom:50px;">
                <div class="box">
                    <div class="box-header clearfix">
                        <div class="col-sm-4">
                            <span> ASSESSMENTS ({{TestsListCtrl.grid.totalRecords}})</span>
                        </div>
                        <md-input-container class="filter">
                            <label style="display:none !important">Filter By Status</label>
                            <md-select ng-model="TestsListCtrl.grid.filter" md-on-close="TestsListCtrl.applyFilter()"
                                       data-md-container-class="multiple-select multiple-select-assessment" multiple placeholder="Filter by Status">
                                <md-optgroup ng-repeat="parent in TestsListCtrl.filterOptions" label="{{parent.name}}">
                                    <md-option ng-value="children.label" ng-repeat="children in parent.children">{{children.value}}</md-option>
                                </md-optgroup>
                            </md-select>
                        </md-input-container>
                        <div class="col-sm-3 pull-right">
                            <div data-epi-search data-opts="TestsListCtrl.search_opts" data-path="templates/components/"></div>
                        </div>
                    </div>
                    <div class="box-content tests-list">
                        <div id="grid" ui-grid="TestsListCtrl.gridOptions" class="grid" ui-grid-selection style="border: 0;">
                           <div class="grid-msg-overlay" ng-if="TestsListCtrl.grid.inProgress">
                              <div class="msg">
                                 <span>
                                    <img src="public/images/loader/spin.gif" alt="loader" width="18%">
                                 </span>
                              </div>
                           </div>
                           <div class="grid-msg-overlay" ng-if="!TestsListCtrl.gridOptions.data.length && !TestsListCtrl.grid.inProgress">
                              <div class="msg">
                                 <span ng-bind="TestsListCtrl.grid.responseMsg"></span>
                              </div>
                           </div>	
                        </div>
                    </div>
                    <div class="box-footer clearfix">
                        <div class="paging col-sm-4 col-sm-offset-4 text-center" ng-if="TestsListCtrl.grid.totalRecords > 10">
                            <ul uib-pagination total-items="TestsListCtrl.grid.totalRecords" ng-model="TestsListCtrl.grid.pageNo" max-size="3" direction-links="false" force-ellipses="true" ng-change="TestsListCtrl.getTestList()" boundary-link-numbers="true" rotate="false"></ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



<!-- Test Name -->
<script type="text/ng-template" id="test-name.html">
	<div class="ui-grid-cell-contents ui-grid-details">
      <a ng-bind="COL_FIELD" ui-sref="app.campaigns.EditTest({ id: row.entity.idexam })" title="{{COL_FIELD}}" class="name ellipsis" ng-click="$event.stopPropagation()"></a>
      <span ng-bind="row.entity.experience"></span>
	</div>
</script>

