<div class="container">
	<div class="row">
		<div class="col-sm-5">
			<p>&copy; 2016 MINTMESH&trade; INC. ALL RIGHTS RESERVED.</p>
		</div>
		<div class="col-sm-7">
			<ul>
				<li><a href="https://mintmesh.com/us/" target="_blank">ABOUT US</a></li>
				<li><a href="https://mintmesh.com/terms-of-use/" target="_blank">TERMS & CONDITIONS</a></li>
				<li><a href="https://mintmesh.com/privacy-policy/" target="_blank">PRIVACY POLICY</a></li>
			</ul>
		</div>
	</div>
</div>