<div class="error-page">
    <div class="container">
    	<div class="row">
    		<div class="col-sm-6 col-sm-offset-3">
    			<div class="error">
    				<div class="error-background"></div>
    				<div class="error-text">
    					<h1>PAGE NOT FOUND</h1>
    					<p>YOU HAVE TAKEN A WRONG TURN</p>
    				</div>
    				<div class="error-action">
    					<a ui-sref="home">BACK TO HOME PAGE</a>
    				</div>
    			</div>
    		</div>
    	</div>
</div>