<div class="edit-campaigns">
    <div class="container">
        <div class="head">
            <a ng-click="EditCampaignsCtrl.back()" title=""><img src="public/images/back-arrow-black.svg" alt="back"><span>BACK TO ALL CAMPAIGNS</span></a>
            <span class="pull-right" ng-click="EditCampaignsCtrl.share()"><img src="public/images/material_icons/share.svg" alt=""></span>
        </div>
        <div class="box">
            <div class="box-content">
                <div class="row">
                    <div class="col-sm-12">
                        <form name="edit_campaigns_form" novalidate autocomplete="off">
                            <input type="hidden" name="campaign_id" value="{{EditCampaignsCtrl.campaignDetails.id}}">
                            <div class="content">
                                <div class="head-title">CAMPAIGN DETAILS</div>
                                <div class="clearfix">
                                    <md-input-container class="md-block select-box">
                                        <label style="display:none">CAMPAIGN TYPE</label>
                                        <md-select name="campaign_type" ng-model="EditCampaignsCtrl.campaignDetails.campaign_type" required ng-class="{'error-border':edit_campaigns_form.campaign_type.$invalid && EditCampaignsCtrl.errCond}">
                                            <md-option ng-repeat="type in EditCampaignsCtrl.campaign" ng-value="type">{{type| uppercase}}</md-option>
                                        </md-select>
                                        <div class="error-spacer"></div>
                                        <div ng-if="edit_campaigns_form.campaign_type.$error.required && EditCampaignsCtrl.errCond"  class="has-error-msg">Please select Campaign Type.</div>
                                    </md-input-container>
                                    <md-input-container class="md-block">
                                        <label>CAMPAIGN NAME</label>
                                        <input type="text" name="campaign_name" ng-model="EditCampaignsCtrl.campaignDetails.campaign_name" required ng-class="{'has-error-border':edit_campaigns_form.campaign_name.$invalid && EditCampaignsCtrl.errCond}">
                                        <div ng-if="edit_campaigns_form.campaign_name.$error.required && EditCampaignsCtrl.errCond" class="has-error-msg">Please enter Campaign Name.</div>
                                    </md-input-container>
                                </div>
                                <div class="clearfix">
                                    <p>LOCATION</p>
                                    <md-radio-group ng-model="EditCampaignsCtrl.radioButtons.address">
                                        <md-radio-button value="online" class="md-primary">Online</md-radio-button>
                                        <md-radio-button value="onsite" class="md-primary">On Site</md-radio-button>
                                    </md-radio-group>
                                    <input type="hidden" name="location_type" value="{{EditCampaignsCtrl.radioButtons.address}}">
                                </div>
                                <div class="location" style="margin-top: 40px;" ng-if="EditCampaignsCtrl.radioButtons.address == 'onsite'">
                                    <div class="clearfix">
                                        <md-input-container class="md-block">
                                            <label>ADDRESS</label>
                                            <input type="text" name="address" ng-model="EditCampaignsCtrl.campaignDetails.location.address" ng-required="EditCampaignsCtrl.radioButtons.address == 'onsite'" ng-class="{'has-error-border':edit_campaigns_form.address.$invalid && EditCampaignsCtrl.errCond}">
                                            <div ng-if="edit_campaigns_form.address.$error.required && EditCampaignsCtrl.errCond" class="has-error-msg">Please enter Address.</div>
                                        </md-input-container>
                                        <md-input-container class="md-block">
                                            <label>CITY</label>
                                            <input type="text" name="city" ng-model="EditCampaignsCtrl.campaignDetails.location.city" ng-keyup="EditCampaignsCtrl.resetLocation(EditCampaignsCtrl.campaignDetails.location.city)" ng-required="EditCampaignsCtrl.radioButtons.address == 'onsite'" ng-class="{'has-error-border':edit_campaigns_form.city.$invalid && EditCampaignsCtrl.errCond}" ng-autocomplete="EditCampaignsCtrl.geo_location" details="EditCampaignsCtrl.geo_details" options="EditCampaignsCtrl.geo_options" apiplaceholder="">
                                            <div ng-if="edit_campaigns_form.city.$error.required && EditCampaignsCtrl.errCond" class="has-error-msg">Please enter City.</div>
                                        </md-input-container>
                                        <input type="hidden" name="latitude" value="{{EditCampaignsCtrl.lat}}">
                                        <input type="hidden" name="longitude" value="{{EditCampaignsCtrl.lng}}">
                                    </div>
                                    <div class="clearfix">
                                        <md-input-container class="md-block">
                                            <label>ZIP CODE</label>
                                            <input type="text" name="zip_code" ng-model="EditCampaignsCtrl.campaignDetails.location.zip_code" ng-class="{'has-error-border':edit_campaigns_form.zip_code.$invalid && EditCampaignsCtrl.errCond}" onkeypress='return event.charCode >= 48 && event.charCode <= 57 || event.charCode == 0' ng-pattern="/^[0-9]{5,6}$/" >
                                            <div ng-if="edit_campaigns_form.zip_code.$error.pattern && EditCampaignsCtrl.errCond" class="has-error-msg">Please enter valid Zip Code.</div>
                                        </md-input-container>
                                        <md-input-container class="md-block">
                                            <label>STATE</label>
                                            <input type="text" name="state" ng-model="EditCampaignsCtrl.campaignDetails.location.state" ng-required="EditCampaignsCtrl.radioButtons.address == 'onsite'" ng-class="{'has-error-border':edit_campaigns_form.state.$invalid && EditCampaignsCtrl.errCond}">
                                            <div ng-if="edit_campaigns_form.state.$error.required && EditCampaignsCtrl.errCond" class="has-error-msg">Please enter State.</div>
                                        </md-input-container>
                                    </div>
                                    <div class="clearfix">
                                        <md-input-container class="md-block">
                                            <label>COUNTRY</label>
                                            <input type="text" name="country" ng-model="EditCampaignsCtrl.campaignDetails.location.country" ng-required="EditCampaignsCtrl.radioButtons.address == 'onsite'" ng-class="{'has-error-border':edit_campaigns_form.country.$invalid && EditCampaignsCtrl.errCond}">
                                            <div ng-if="edit_campaigns_form.country.$error.required && EditCampaignsCtrl.errCond" class="has-error-msg">Please enter Country.</div>
                                        </md-input-container>
                                    </div>
                                </div>
                                <div class="clearfix date" ng-style="{'margin-top': EditCampaignsCtrl.address == 'online' ? '40px' : '30px'}">
                                <div class="head-title">SCHEDULE & JOBS</div>
                                    
                                <div flex class="schedule">
                                    <div layout="column" class="timesheet" ng-repeat="group in EditCampaignsCtrl.campaignDetails.schedule">
                                        <!--IMP NOTE don't rearrange the below div for this check in directive(schedule-start, schedule-end)-->
                                        <div layout="row">
                                            <img ng-if="group.hasCloseIcon" ng-click="EditCampaignsCtrl.closeSchedule($index)" class="closed" src="public/images/close-popup-red.svg" alt="close">
                                            <div flex="40" class="sib">
                                                <md-input-container class="md-block date-time">
                                                    <label>CAMPAIGN START DATE</label>
                                                    <input type='text' ng-disabled="group.status == 'CLOSED'" name="start{{$index}}" class="form-controls" schedule-start ng-model="scheduleStart" id='dtPickerStart{{$index}}' required ng-class="{'has-error-border':EditCampaignsCtrl.errCond && edit_campaigns_form['start'+$index].$error.required}"/>
                                                    <span class="input-group-addon">
                                                        <span class="glyphicon glyphicon-calendar"></span>
                                                    </span>

                                                    <input type="hidden" name="schedule[{{$index}}][start_on_date]" value="{{EditCampaignsCtrl.getScheduleDate('#dtPickerStart'+ $index)}}">
                                                    <input type="hidden" name="schedule[{{$index}}][start_on_time]" value="{{EditCampaignsCtrl.getScheduleTime('#dtPickerStart'+ $index)}}">

                                                </md-input-container>
                                                <div ng-show="EditCampaignsCtrl.errCond && edit_campaigns_form['start'+$index].$error.required" class="has-error-msg msg">Please select Start Date.</div>
                                            </div>
                                            <div flex="40" class="sib">
                                                <md-input-container class="md-block date-time">
                                                    <label>CAMPAIGN END DATE</label>
                                                    <input type='text' class="form-controls" name="end{{$index}}" required ng-model="scheduleEnd" schedule-end ng-disabled="group.status == 'CLOSED'" id='dtPickerEnd{{$index}}' ng-class="{'has-error-border':EditCampaignsCtrl.errCond && edit_campaigns_form['end'+$index].$error.required}"/>
                                                    <span class="input-group-addon">
                                                        <span class="glyphicon glyphicon-calendar"></span>
                                                    </span>

                                                    <input type="hidden" name="schedule[{{$index}}][end_on_date]" value="{{EditCampaignsCtrl.getScheduleDate('#dtPickerEnd'+ $index)}}">
                                                    <input type="hidden" name="schedule[{{$index}}][end_on_time]" value="{{EditCampaignsCtrl.getScheduleTime('#dtPickerEnd'+ $index)}}">
                                                    <input type="hidden" name="schedule[{{$index}}][schedule_id]" value="{{group.schedule_id}}">

                                                </md-input-container>
                                                <div ng-show="EditCampaignsCtrl.errCond && edit_campaigns_form['end'+$index].$error.required" class="has-error-msg msg">Please select End Date.</div>
                                            </div>
                                            <span ng-if="group.status == 'CLOSED'" class="status">CLOSED</span>
                                        </div>
                                    </div>
                                    <span class="btn-action" ng-class="{ 'disable-cursor' : EditCampaignsCtrl.campaignDetails.schedule.length == 5}" ng-click="EditCampaignsCtrl.addSchedule()">ADD MULTIPLE SCHEDULE</span>
                                </div>

                                <div class="clearfix tag-jobs">
                                    <div class="drop">
                                        <div class="create-job">
                                            <div class="modern-select">
                                                <select data-rel="chosen" id="mul_select" name="job_ids[]"  ng-model="EditCampaignsCtrl.campaignDetails.job_ids" data-placeholder="Select Your Options" class="form-control" multiple required ng-class="{'has-error-border': edit_campaigns_form['jobs[]'].$invalid && EditCampaignsCtrl.errCond}">
                                                    <option value=""></option>
                                                    <option ng-repeat="list in EditCampaignsCtrl.jobsList" ng-bind="list.name + ' ( ' + list.no_of_vacancies + ' )'" ng-value="list.post_id"></option>
                                                </select>
                                            </div>
                                            <span class="btn-action" style="position: absolute;top: 9px;right: 0;" ng-click="EditCampaignsCtrl.createJob()">CREATE JOB</span>
                                        </div>
                                    </div>
                                </div>


                                <div class="head-title">CAREERS PAGE</div>
                                <div layout="column">
                                    <div layout="row" class="section">
                                        <div layout="column" flex class="careers">
                                            <div layout="row">
                                                <div flex="70" class="left">
                                                    <div layout="column">
                                                        <h5 class="sub-head">UPLOADS</h5>
                                                        <div layout="row">
                                                            <div mm-uploader flex="50" class="uploads" datasource="EditCampaignsCtrl.companyLogoOpts"></div>
                                                            <i flex="5"></i>
                                                            <div mm-uploader flex="50" class="uploads" datasource="EditCampaignsCtrl.heroShortImageOpts"></div>
                                                        </div>
                                                        <h5 class="sub-head link">SHOW TALENT COMMUNITY</h5>
                                                        <md-radio-group layout="row" style="color: #9f9f9f" ng-model="EditCampaignsCtrl.campaignDetails.career_talent_network">
                                                              <md-radio-button flex="20" value="enable" class="md-primary">Yes</md-radio-button>
                                                              <md-radio-button flex="20" value="disable" class="md-primary">No</md-radio-button>
                                                        </md-radio-group>
                                                        <input type="hidden" name="career_talent_network" value={{EditCampaignsCtrl.campaignDetails.career_talent_network}}>
                                                        <h5 class="sub-head link" style="padding-bottom: 27px">LINKS</h5>
                                                        <div layout="row" class="link-box" ng-repeat="link in EditCampaignsCtrl.campaignDetails.career_links">
                                                            <img ng-click="EditCampaignsCtrl.campaignDetails.career_links.splice($index, 1);" class="closed" src="public/images/close-popup-red.svg" alt="close">
                                                            <md-input-container flex="50" class="md-block">
                                                                <label>LABEL {{$index + 1}}</label>
                                                                <input type="text" class="form-controls" name="label{{$index}}" ng-required="link.url" ng-model="link.label" ng-class="{'has-error-border':edit_campaigns_form['label'+$index].$error.required && EditCampaignsCtrl.errCond}">
                                                                <div ng-if="edit_campaigns_form['label'+$index].$error.required && EditCampaignsCtrl.errCond"  class="has-error-msg">Please enter Label Name.</div>
                                                            </md-input-container>
                                                            <i flex="5"></i>
                                                            <input type="hidden" ng-if="link.label" name="career_links[{{$index}}][label]" value="{{link.label}}">  
                                                            <md-input-container flex="50" class="md-block" style="margin-bottom:0">
                                                                <label>Website(URL)</label>
                                                                <input  type="text" class="form-controls" name="url{{$index}}" ng-required="link.label" ng-model="link.url" ng-pattern="/^(?:http(s)?:\/\/)?[\w.-]+(?:\.[\w\.-]+)+[\w\-\._~:/?#[\]@!\$&'\(\)\*\+,;=.]+$/" ng-class="{'has-error-border':edit_campaigns_form['url'+$index].$invalid && EditCampaignsCtrl.errCond}">
                                                                <div ng-if="edit_campaigns_form['url'+$index].$error.required && EditCampaignsCtrl.errCond"  class="has-error-msg">Please enter Website URL.</div>
                                                                <div ng-if="edit_campaigns_form['url'+$index].$error.pattern && EditCampaignsCtrl.errCond"  class="has-error-msg">Please enter valid Website URL.</div>
                                                            </md-input-container>
                                                            <input type="hidden" ng-if="link.url" name="career_links[{{$index}}][url]" value="{{link.url}}">
                                                        </div>
                                                        <div style="margin-bottom: 36px;">
                                                            <span class="btn-action" ng-click="EditCampaignsCtrl.addHyperlink()" ng-class="{ 'disable-cursor' : EditCampaignsCtrl.campaignDetails.career_links.length > 3 }" ng-disabled="EditCampaignsCtrl.campaignDetails.career_links.length > 3" class="hyper-link">ADD LINK</span>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div flex="30">
                                                    <h5 class="sub-head">COMPANY DESCRIPTION</h5>
                                                    <md-input-container class="md-block" flex=100>
                                                        <textarea name="career_description" class="description" ng-model="EditCampaignsCtrl.campaignDetails.career_description" aria-label="des" md-maxlength="5000" maxlength="5000" ng-maxlength="5000"></textarea>
                                                    </md-input-container>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="head-title">MANAGE CONTACTS</div>
                                <div class="clearfix upload-contacts">
                                    <buckets-view datasource="EditCampaignsCtrl.bucktesViewInternalOpts"></buckets-view>
                                    <!-- <div style="min-height:30px">
                                        <div ng-show="edit_campaigns_form.selectedBuckets.$invalid && EditCampaignsCtrl.errCond" class="has-error-msg">Please select atleast one Community to Publish Campaign.</div>
                                    </div> -->
                                    <div ng-if="EditCampaignsCtrl.campaignDetails.career_talent_network == 'enable'"> 
                                        <buckets-view datasource="EditCampaignsCtrl.bucktesViewExternalOpts"></buckets-view>
                                    </div>
                                    <input type="hidden" name="selectedBuckets" required value="{{EditCampaignsCtrl.getSelectedBkt()}}" ng-model="EditCampaignsCtrl.selectedBkts">
                                </div>
                                <div class="clearfix upload-files">
                                    <div>
                                        <md-checkbox ng-model="EditCampaignsCtrl.checkbox.ceoPitch" aria-label="Checkbox 1" class="md-primary">
                                            Upload CEO's Pitch
                                        </md-checkbox>
                                        <div ng-style="{'pointer-events': EditCampaignsCtrl.checkbox.ceoPitch ? 'auto' : 'none'}" class="upload-pitch">BROWSE FILE</div>
                                    </div>
                                    <div>
                                        <md-checkbox ng-model="EditCampaignsCtrl.checkbox.employeePitch" aria-label="Checkbox 2" class="md-primary">
                                            Upload Employees's Pitch
                                        </md-checkbox>
                                        <div ng-style="{'pointer-events': EditCampaignsCtrl.checkbox.employeePitch ? 'auto' : 'none'}" class="upload-pitch">BROWSE FILE</div>
                                    </div>
                                </div>	
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="box-footer clearfix">
                <div class="pull-left" ng-if="EditCampaignsCtrl.loader">
                    <span ><img src="public/images/loader/upload_file.gif" alt="loader" style="margin:5px;" > Updating</span>
                </div>
                <div class="pull-right disabled">
                    <span class="btn-update ripplelink" ng-click="EditCampaignsCtrl.updateCampaign(edit_campaigns_form.$valid)">Update Campaign</span>
                </div>
            </div>
        </div>
    </div>
</div>