<style type="text/css">
    /* Form view */
.angular-survey-template {
  min-height: calc(100vh - 350px); !important;
  height: 500px;
  max-width: 100%;
  }
  .angular-survey-template .container {
    width: 1027px;
    padding: 0; }
    .angular-survey-template .container .close {
      position: absolute;
      right: 20px;
      padding: 0;
      top: 20px;
      opacity: 1;
      width: 28px;
      height: 28px;
    }
    .angular-survey-template .container .head, .angular-survey-template .container .checkbox, .angular-survey-template .container hr {
      display: none; }
    .angular-survey-template .container .mw-form-viewer {
      margin: 0;
      padding: 0; }
      .angular-survey-template .container .mw-form-viewer form {
        overflow: hidden; }
        .angular-survey-template .container .mw-form-viewer form .mw-title-page {
          text-align: center;
          margin: 38px 20px;}
          .angular-survey-template .container .mw-form-viewer form .mw-title-page .mw-form-description {
            font-size: 14px;
            text-align: left;
            line-height: 22px;
          }
        .angular-survey-template .container .mw-form-viewer form .begin-response-button, .angular-survey-template .container .mw-form-viewer form .begin-response-button:hover {
          background: #31BE9E !important;
          color: #fff;
          width: auto;
          height: 52px;
          font-size: 22px;
          border-radius: 0; }
          .angular-survey-template .container .mw-form-viewer form .begin-response-button:hover, .angular-survey-template .container .mw-form-viewer form .begin-response-button:active, .angular-survey-template .container .mw-form-viewer form .begin-response-button:hover:hover, .angular-survey-template .container .mw-form-viewer form .begin-response-button:hover:active {
            background: transparent;
            outline: none;
            box-shadow: none; }
        .angular-survey-template .container .mw-form-viewer form .mw-form-question {
          /*color: #808080;*/
          padding-top: 24px; }
          .angular-survey-template .container .mw-form-viewer form .mw-form-question .mw-question-text {
            font-weight: normal;
            font-size: 14px;
            margin-bottom: 24px; }
          .angular-survey-template .container .mw-form-viewer form .mw-form-question .mw-question-answers {
            font-size: 14px; }
        .angular-survey-template .container .mw-form-viewer form .mw-form-action-list {
          position: fixed;
          bottom: 0;
          right: 0;
          width: 100%;
          background: #eee;
          height: 80px;}
          .angular-survey-template .container .mw-form-viewer form .mw-form-action-list .btn {
            padding: 2px 50px;
            margin: 20px 20px 16px 20px;
            font-size: 14px;
            font-weight: 600; }
          .angular-survey-template .container .mw-form-viewer form .mw-form-action-list .prev-page-button {
            float: left;
            color: #fff;
            background: #31BE9E;
            padding: 2px 25px;}
            .angular-survey-template .container .mw-form-viewer form .mw-form-action-list .prev-page-button:hover, .angular-survey-template .container .mw-form-viewer form .mw-form-action-list .prev-page-button:active {
              background: transparent;
              outline: none;
              box-shadow: none; }
            .angular-survey-template .container .mw-form-viewer form .mw-form-action-list .prev-page-button i {
              /*display: none;*/ }
          .angular-survey-template .container .mw-form-viewer form .mw-form-action-list .prev-page-button:hover {
            background: #31BE9E !important; }
          .angular-survey-template .container .mw-form-viewer form .mw-form-action-list .next-page-button {
            float: right;
            background: #31BE9E;
            opacity: 1;
            color: #fff; }
            .angular-survey-template .container .mw-form-viewer form .mw-form-action-list .next-page-button i {
              /*display: none;*/ }
    .angular-survey-template .container .mw-pending-message {
      color: #9E9E9E;
      display: block;
      text-align: center;
      font-size: 24px;
      line-height: 200px; }
      .container-header {
        padding: 19px 20px;
        background: #eeeeee;
      }
      .questionnaire-name {
          text-align: left;
          margin: 0;
          font-size: 20px;
      }
      .questionnaire-description {
          float: right;
          margin-right: 139px;
          clear: both;
          margin-top: 6px;
          font-size: 14px;
          color: #4a4a4a;
      }
      .questionnaire-footer {
        position: absolute;
        bottom: 0;
        left: 0;
        right: 0;
        width: 100%;
        height: 80px;
        line-height: 80px;
        background: #eeeeee;
        padding: 0 20px;
      }
      .angular-survey-template .container .mw-form-viewer form .begin-response-button {
        text-transform: uppercase;
        width: auto;
        border-radius: 5px;
        -webkit-border-radius: 5px;
        -moz-border-radius: 5px;
        -o-border-radius: 5px;
        font-size: 17px;
        font-weight: 700;
        letter-spacing: 1px;
        margin-top: 15px;
        padding: 0 40px;
      }
      .angular-survey-template .container .mw-form-viewer form .begin-response-button:hover {
        width: auto;
        height: 52px;
        border-radius: 5px;
        -webkit-border-radius: 5px;
        -moz-border-radius: 5px;
        -o-border-radius: 5px;
        font-size: 17px;
      }
      .total-question {

      }
      .time-duration {
        margin-left: 30px;
      }
      .copy-right {
        color: #767877;
        font-size: 14px;
      }
      .mw-form-viewer .mw-form-page {
        margin: 0;
        padding: 25px 20px;
        font-size: 14px;
      }
      .question-number {
        font-weight: 600;
        color: rgba(0,0,0,0.87);
      }
      .time-left {
        font-size: 14px;
      }
      .time-left span {
        color: #a63936;
      }
      .full-screen {
        width: 100%;
        min-height: 100%;
      }
      .full-screen .container {
        width: 100%;
      }
      .fullscreen-icon {
        position: absolute;
        top: 20px;
        right: 90px;
        font-size: 30px;
        width: 28px;
        height: 28px;
      }
      .angular-survey-template .container .mw-form-viewer form .mw-form-question .mw-question-text .required-question {
        color: red;
      }
      .vertical-center {
        position: absolute;
        top: 50%;
        transform: translateY(-50%);
        width: 100%;
        text-align: center;
      }
      .mw-confirmation-message {
        color: #1f8c6f;
        font-size: 25px;
      }
      .mw-form-confirmation-page .vertical-center i {
        font-size: 50px;
        margin-right: 10px;
        position: relative;
        top: 8px;
      }
      .mw-timeup-message {
        color: red;
      }
</style>
<md-dialog class="angular-survey-template">
    <div class="container">
        <div class="container-header">
        <!-- {{FormViewerCtrl.formData}} -->
          <span class="questionnaire-name">{{FormViewerCtrl.formData.exam_name}} - Instructions</span>
          <div class="questionnaire-description">
            <span class="total-question">Total Questions: {{FormViewerCtrl.formData.pages.length}}</span>
            <span class="time-duration" ng-if="FormViewerCtrl.formData.max_duration">Time: {{FormViewerCtrl.formData.max_duration}} mins</span>
          </div>
          <img src="public/images/resize.svg" alt="fullscreen" class="fullscreen-icon" ng-click="FormViewerCtrl.fullScreen();" />

          <img src="public/images/cross-grey.svg" alt="close" class="close" ng-click="FormViewerCtrl.closeDialog($event)">
        </div>


        <!-- <div layout="row" class="head">
            <span flex></span>
            <md-checkbox ng-model="FormViewerCtrl.viewerReadOnly" aria-label="Checkbox 1">Read only</md-checkbox>
            <md-checkbox ng-model="FormViewerCtrl.formOptions.autoStart" aria-label="Checkbox 1">Autostart</md-checkbox>
            <button class="btn mm-btn" type="button" ng-click="FormViewerCtrl.resetViewer()">Reset</button>
        </div> -->

        <mw-form-viewer ng-if="FormViewerCtrl.formData"
                        form-data="FormViewerCtrl.formData"
                        template-data="FormViewerCtrl.templateData"
                        form-status="FormViewerCtrl.formStatus"
                        options="FormViewerCtrl.formOptions"
                        api="FormViewerCtrl.formViewer"
                        response-data="FormViewerCtrl.responseData"
                        read-only="FormViewerCtrl.viewerReadOnly"
                        on-submit="FormViewerCtrl.saveResponse()">
        </mw-form-viewer>
        <hr>
        <div class="checkbox">
            <label>
                <input type="checkbox" ng-model="FormViewerCtrl.showResponseData" ng-click="FormViewerCtrl.showResponseModal(FormViewerCtrl.showResponseData)"> Show response data
            </label>
        </div>
    </div>
</md-dialog>

<!-- Form Build Json -->
<script type="text/ng-template" id="form_view_json.phtml">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" ng-click="$dismiss()">&times;</button>
                <h4 class="modal-title">Form Build Json</h4>
            </div>
            <div class="modal-body">
                <pre>{{FormViewerCtrl.responseData|json}}</pre>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" ng-click="$dismiss()">OKAY</button>
            </div>
        </div>
    </div>
</script>
