<div class="config-manager">
    <div class="container">
        <div class="saml" layout="row">
            <div class="lt" flex="20">
                <md-list>
                    <md-list-item class="md-2-line" ng-class="{'md-list-active': true}">
                        <div class="md-list-item-text" layout="column">
                            <h3>SS0</h3>
                            <h4>SAML 2.0</h4>
                        </div>
                    </md-list-item>
                </md-list>
            </div>
            <md-divider ></md-divider>
            <div class="rt" flex="80">
                <md-card>
                    <md-card-content layout="column" layout-align="space-between">
                        <div layout="row">
                            <div flex="50">
                                <div class="form-group">
                                    <label for="xml">Paste your XML Metadata here</label>
                                    <textarea class="form-control" rows="5" id="xml"></textarea>
                                </div>
                            </div>
                            <div flex="50">
                                <!--<div flow-init="{target: '/upload'}"
                                     flow-files-submitted="$flow.upload()"
                                     flow-file-success="$file.msg = $message">

                                    <input type="file" flow-btn/>
                                    Input OR Other element as upload button
                                    <span class="btn" flow-btn>Upload File</span>

                                    <table>
                                        <tr ng-repeat="file in $flow.files">
                                            <td>{{$index + 1}}</td>
                                            <td>{{file.name}}</td>
                                            <td>{{file.msg}}</td>
                                        </tr>
                                    </table>
                                </div>-->
                            </div>
                        </div>
                        <div layout="row">
                            <div flex="50">
                                <md-input-container>
                                    <label>Issuer URL</label>
                                    <input name="issuer_url" ng-model="url">
                                </md-input-container>
                            </div>
                            <div flex="50">
                                <md-input-container>
                                    <label>SAML 2.0 Endpoint (HTTP)</label>
                                    <input name="saml_url" ng-model="url">
                                </md-input-container>
                            </div>
                        </div>
                        <div layout="row">
                            <div flex="50">
                                <md-input-container>
                                    <label>SLO Endpoint (HTTP)</label>
                                    <input name="slo_url" ng-model="url">
                                </md-input-container>
                            </div>
                        </div>
                    </md-card-content>
                    <md-divider ></md-divider>
                    <md-card-actions layout="row" layout-align="end center">
                        <md-button class="mm-btn">Save</md-button>
                    </md-card-actions>
                </md-card>
            </div>
        </div>
    </div>
</div>