<div class="manager-tab">
    <div class="container">
        <div class="saml" layout="row">
            <div class="lt" flex="20">
                <md-list>
                    <md-list-item class="md-1-line" ng-class="{'md-list-active': true}">
                        <div class="md-list-item-text" layout="column">
                            <h4>Single Sign-On (SSO)</h4>
                        </div>
                    </md-list-item>
                </md-list>
            </div>
            <md-divider ></md-divider>
            <div class="rt" flex="80">
                <md-card>
                    <md-card-content>
                        <form name="single_signin" novalidate autocomplete="off">
                         
                            <div layout="row">
                                <div flex="50">
                                    <md-checkbox ng-model="ConfigMngCtrl.SSOCheckbox" aria-label="start project" class="md-primary">Enable Single Sign-On(SSO)</md-checkbox>
                                    <input type="hidden" name="status" value="{{ConfigMngCtrl.SSOCheckbox ? 1 : 0}}">
                                    <input type="hidden" name="id" value="{{ConfigMngCtrl.ssoDetails.id}}">
                                </div>
                                <span flex></span>
                                <!--<md-button aria-label="edit" class="mm-no-btn" ng-click="ConfigMngCtrl.edit()">
                                    <md-icon><i class="material-icons">edit</i></md-icon>Edit
                                </md-button>-->
                            </div>
                            <div layout="row" style="padding-top: 15px;">
                                <div flex="50">
                                    <md-input-container>
                                        <label>Sign-In Page(URL)</label>
                                        <input id="ft" name="signin_url" ng-model="ConfigMngCtrl.ssoDetails.signin_url" required ng-class="{'has-error-border': single_signin.signin_url.$invalid && ConfigMngCtrl.show_error}">
                                        <div ng-if="single_signin.signin_url.$error.required && ConfigMngCtrl.show_error"  class="has-error-msg">Please Enter Sign-In Page URL.</div>
                                    </md-input-container>
                                </div>
                                <div flex="50">
                                    <md-input-container>
                                        <label>Sign-Out Page(URL)</label>
                                        <input name="signout_url" ng-model="ConfigMngCtrl.ssoDetails.signout_url" required ng-class="{'has-error-border': single_signin.signout_url.$invalid && ConfigMngCtrl.show_error}">
                                        <div ng-if="single_signin.signout_url.$error.required && ConfigMngCtrl.show_error"  class="has-error-msg">Please Enter Sign-Out Page URL.</div>
                                    </md-input-container>
                                </div>
                            </div>
                            <div layout="row">
                                <div flex="50">
                                    <div layout="column" style="height:240px">
                                        <div flex>
                                            <md-input-container>
                                                <label>Identity Provider Issuer(URL)</label>
                                                <input name="idp_issuer" ng-model="ConfigMngCtrl.ssoDetails.idp_issuer" required ng-class="{'has-error-border': single_signin.idp_issuer.$invalid && ConfigMngCtrl.show_error}">
                                                <div ng-if="single_signin.idp_issuer.$error.required && ConfigMngCtrl.show_error"  class="has-error-msg">Please Enter Identity Provider Issuer URL.</div>
                                            </md-input-container>
                                        </div>
                                        <div flex>
                                            <div class="file-upload">
                                                <span>Upload Identity Provider Certificate</span>
                                                <div id="upload"></div>
                                                <p class="has-error-msg" style="margin-top: -4px;" ng-if="!ConfigMngCtrl.uploadSuccess && ConfigMngCtrl.show_error">Please Upload a File</p>
                                                <!--<div class="up-tmp" ng-if="ConfigMngCtrl.successUpload">
                                                    <div class="box" layout="row">
                                                        <img src="public/images/pdf.png" class="avatar">
                                                        <div layout="column">
                                                            <p>Default_Cerificate 1 (2048-bit)</p>
                                                            <span>69.09 KB</span>
                                                        </div>
                                                        <span flex></span>
                                                        <i class="material-icons">close</i>
                                                    </div>
                                                    <div layout="row" class="action">
                                                        <span style="padding-right: 10px;">Change</span>
                                                        <md-divider ></md-divider>
                                                        <span style="padding-left: 10px;">View Details</span>
                                                        <span flex></span>
                                                        <span>(Maximum size is 10MB)</span>
                                                    </div>
                                                </div>-->
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div flex="50">
                                    <div class="modern-select">
                                        <select data-rel="chosen" name="job_ids[]" id="selectJob" ng-model="ConfigMngCtrl.selectedEmails" data-own="White Listing" data-placeholder="" class="form-control" multiple>
                                            <option ng-repeat="emails in ConfigMngCtrl.emailsList" value="{{emails.id}}" ng-bind="emails.email_id"></option>
                                            <!-- <option ng-if="NewCampaignCtrl.jobLists.length == 0" value="" disabled>No jobs found.</option> -->
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </md-card-content>
                    <md-card-actions style="min-height: 53px;">
                        <div class="bor" ng-show="single_signin.$dirty || ConfigMngCtrl.changeOccured" layout="row">
                            <div flex>
                                <span ng-if="ConfigMngCtrl.spinner"><img src="public/images/loader/upload_file.gif" alt="loader"> Adding...</span>
                                <span ng-if="ConfigMngCtrl.sucMsg != ''" class="suc" ng-bind="ConfigMngCtrl.sucMsg"></span> 
                            </div>
                            <span flex></span>
                            <md-button class="mm-btn" ng-disabled="ConfigMngCtrl.spinner" ng-click="ConfigMngCtrl.save(single_signin.$valid)">{{ConfigMngCtrl.hasRecord ? 'Update' : 'Save'}}</md-button>
                        </div>
                    </md-card-actions>
                    <div class="im-spinner" ng-if="ConfigMngCtrl.loader">
                        <div>
                            <img src="public/images/loader/spin.gif" alt="loading">
                        </div>
                    </div>
                </md-card>
            </div>
        </div>
    </div>
</div>