<div class="config-manager">
    <div class="container">
        <div class="saml" layout="row">
            <div class="lt" flex="20">
                <md-list>
                    <md-list-item class="md-1-line" ng-class="{'md-list-active': true}">
                        <div class="md-list-item-text" layout="column">
                            <h4>Single Sign-On (SSO)</h4>
                        </div>
                    </md-list-item>
                </md-list>
            </div>
            <md-divider ></md-divider>
            <div class="rt" flex="80">
                <md-card>
                    <md-card-content layout="column" layout-align="space-between">
                        <form name="single_signin" novalidate>
                            <md-grid-list md-cols-xs="1" md-cols="2" md-row-height="6:1" md-gutter="30px">
                                <md-grid-tile md-colspan="2">
                                    <md-checkbox ng-model="ConfigMngCtrl.SSOCheckbox" aria-label="start project" class="md-primary">Enable Single sign-On(SSO)</md-checkbox>
                                </md-grid-tile>
                                <md-grid-tile>
                                    <md-input-container>
                                        <label>Sign-In Page(URL)</label>
                                        <input name="signin_url" ng-model="ConfigMngCtrl.partnerDetails.signin_url" ng-pattern="/^(http:\/\/www\.|https:\/\/www\.|www\.|https:\/\/|http:\/\/)[A-Za-z0-9]+([\-\.]{1}[A-Za-z0-9]+)*\.[A-Za-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/i" required ng-class="{'has-error-border': single_signin.signin_url.$invalid && ConfigMngCtrl.show_error}">
                                        <div ng-if="single_signin.signin_url.$error.required && ConfigMngCtrl.show_error"  class="has-error-msg">Please Enter Sign-In Page URL.</div>
                                        <div ng-if="single_signin.signin_url.$error.pattern && ConfigMngCtrl.show_error"  class="has-error-msg">Please Enter Valid URL.</div>
                                    </md-input-container>
                                </md-grid-tile>
                                <md-grid-tile>
                                    <md-input-container>
                                        <label>Sign-Out Page(URL)</label>
                                        <input name="signout_url" ng-model="ConfigMngCtrl.partnerDetails.signout_url" ng-pattern="/^(http:\/\/www\.|https:\/\/www\.|www\.|https:\/\/|http:\/\/)[A-Za-z0-9]+([\-\.]{1}[A-Za-z0-9]+)*\.[A-Za-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/i" required ng-class="{'has-error-border': single_signin.signout_url.$invalid && ConfigMngCtrl.show_error}">
                                        <div ng-if="single_signin.signout_url.$error.required && ConfigMngCtrl.show_error"  class="has-error-msg">Please Enter Sign-Out Page URL.</div>
                                        <div ng-if="single_signin.signout_url.$error.pattern && ConfigMngCtrl.show_error"  class="has-error-msg">Please Enter Valid URL.</div>
                                    </md-input-container>
                                </md-grid-tile>
                                <md-grid-tile>
                                    <md-input-container>
                                        <label>Identity Provider Issuer(URL)</label>
                                        <input name="identity_provider" ng-model="ConfigMngCtrl.partnerDetails.identity_provider" ng-pattern="/^(http:\/\/www\.|https:\/\/www\.|www\.|https:\/\/|http:\/\/)[A-Za-z0-9]+([\-\.]{1}[A-Za-z0-9]+)*\.[A-Za-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/i" required ng-class="{'has-error-border': single_signin.identity_provider.$invalid && ConfigMngCtrl.show_error}">
                                        <div ng-if="single_signin.identity_provider.$error.required && ConfigMngCtrl.show_error"  class="has-error-msg">Please Enter Identity Provider Issuer URL.</div>
                                        <div ng-if="single_signin.identity_provider.$error.pattern && ConfigMngCtrl.show_error"  class="has-error-msg">Please Enter Valid URL.</div>
                                    </md-input-container>
                                </md-grid-tile>
                                <md-grid-tile>
                                    <!--<div data-epi-multiple-select model="selectedOptions" options="ConfigMngCtrl.options"></div>-->
                                    <!--<md-input-container>
                                        <label>DC Center URL</label>
                                        <input name="dc_url" ng-model="ConfigMngCtrl.partnerDetails.dc_url" ng-pattern="/^(http:\/\/www\.|https:\/\/www\.|www\.|https:\/\/|http:\/\/)[A-Za-z0-9]+([\-\.]{1}[A-Za-z0-9]+)*\.[A-Za-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/i" required ng-class="{'has-error-border': single_signin.dc_url.$invalid && ConfigMngCtrl.show_error}">
                                        <div ng-if="single_signin.dc_url.$error.required && ConfigMngCtrl.show_error"  class="has-error-msg">Please Enter DC Center URL.</div>
                                        <div ng-if="single_signin.dc_url.$error.pattern && ConfigMngCtrl.show_error"  class="has-error-msg">Please Enter Valid URL.</div>
                                    </md-input-container>-->
                                </md-grid-tile>
                                <md-grid-tile>
                                    <!--<md-input-container>
                                        <label>DC Center URL</label>
                                        <input name="dc_url" ng-model="ConfigMngCtrl.partnerDetails.dc_url" ng-pattern="/^(http:\/\/www\.|https:\/\/www\.|www\.|https:\/\/|http:\/\/)[A-Za-z0-9]+([\-\.]{1}[A-Za-z0-9]+)*\.[A-Za-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/i" required ng-class="{'has-error-border': single_signin.dc_url.$invalid && ConfigMngCtrl.show_error}">
                                        <div ng-if="single_signin.dc_url.$error.required && ConfigMngCtrl.show_error"  class="has-error-msg">Please Enter DC Center URL.</div>
                                        <div ng-if="single_signin.dc_url.$error.pattern && ConfigMngCtrl.show_error"  class="has-error-msg">Please Enter Valid URL.</div>
                                    </md-input-container>-->
                                </md-grid-tile>
                            </md-grid-list>
                        </form>
                    </md-card-content>
                    <md-divider ></md-divider>
                    <md-card-actions layout="row" layout-align="end center">
                        <md-button class="mm-btn" ng-click="ConfigMngCtrl.save(single_signin.$valid)">Save</md-button>
                    </md-card-actions>
                </md-card>
            </div>
        </div>
    </div>
</div>