<div class="manager-tab integration">
    <!-- <div class="init-loader" ng-if="IntMngCtrl.loader"></div> -->
    <!-- <div class="container" ng-show="!IntMngCtrl.loader"> -->
    <div class="container">
        <div class="hcms" layout="row">
            <div class="lt" flex="20">
                <!--<div class="ad-pt" layout="row">
                    ADD PARTNER
                    <span flex></span>
                    <md-button class="md-icon-button" ng-click="IntMngCtrl.addPartner($event)">
                        <md-icon><i class="material-icons">add</i></md-icon>
                    </md-button>
                </div>-->
                <md-list>
                    <md-list-item class="md-1-line" ng-class="{'md-list-active': $index == IntMngCtrl.activeIndex}" ng-repeat="pat in IntMngCtrl.mintmeshPartnes track by $index">
                        <div class="md-list-item-text" layout="column" ng-click="IntMngCtrl.getPartnersData($index)">
                            <h4 ng-bind="pat.hcm_name"></h4>
                        </div>
                    </md-list-item>
                </md-list>
            </div>
            <md-divider></md-divider>
            <div class="rt" flex="80">
                <md-card>
                    <div class="im-spinner" ng-if="IntMngCtrl.loader">
                        <div>
                            <img src="public/images/loader/spin.gif" alt="loading">
                        </div>
                    </div>
                    <md-card-content>
                        <form name="suc_fac_form" novalidate autocomplete="off">
                            <input name="hcm_id" value="{{IntMngCtrl.partnerDetails.hcm_id}}" type="hidden">
                            
                            <!-- Auto off for saved username and password  -->
                            <input type="password" style="display: none">
                            
                            <div layout="row" ng-if="IntMngCtrl.activeIndex != 1">
                                <div flex="50">
                                    <md-input-container>
                                        <label>DC Center URL</label>
                                        <input name="hcm_url" ng-model="IntMngCtrl.partnerDetails.hcm_url" required ng-class="{'has-error-border': suc_fac_form.hcm_url.$invalid && IntMngCtrl.show_error}">
                                        <div ng-if="suc_fac_form.hcm_url.$error.required && IntMngCtrl.show_error"  class="has-error-msg">Please Enter DC Center URL.</div>
                                    </md-input-container>
                                </div>
                                <div flex="50">
                                    <md-input-container>
                                        <label>User Name</label>
                                        <input name="hcm_username" ng-model="IntMngCtrl.partnerDetails.hcm_username" required ng-class="{'has-error-border': suc_fac_form.hcm_username.$invalid && IntMngCtrl.show_error}">
                                        <div ng-if="suc_fac_form.hcm_username.$error.required && IntMngCtrl.show_error"  class="has-error-msg">Please Enter User Name.</div>
                                    </md-input-container>
                                </div>
                            </div>
                            <div layout="row">
                                <div flex="50" ng-if="IntMngCtrl.activeIndex != 1">
                                    <md-input-container>
                                        <label>Password</label>
                                        <input name="hcm_password" type="password" ng-model="IntMngCtrl.partnerDetails.hcm_password" required ng-class="{'has-error-border': suc_fac_form.hcm_password.$invalid && IntMngCtrl.show_error}">
                                        <div ng-if="suc_fac_form.hcm_password.$error.required && IntMngCtrl.show_error"  class="has-error-msg">Please Enter Password.</div>
                                    </md-input-container>
                                </div>
                                <!-- <div flex="50" ng-if="IntMngCtrl.activeIndex == 1">
                                        <label>Access Token</label>
                                        <input name="hcm_access_token" type="hidden" ng-model="IntMngCtrl.partnerDetails.hcm_access_token" required ng-class="{'has-error-border': suc_fac_form.hcm_access_token.$invalid && IntMngCtrl.show_error}" >
                                        <div ng-if="suc_fac_form.hcm_access_token.$error.required && IntMngCtrl.show_error"  class="has-error-msg">Please Enter Access Token.</div>
                                    <md-input-container>
                                    </md-input-container>
                                </div> -->
                            </div>
                            <div ng-if="IntMngCtrl.activeIndex == 1 && !IntMngCtrl.zenefitsInProgress && !IntMngCtrl.showSynWithZenefits" class="animated fadeIn text-center msg-sync">Synced Successfully.</div>
                            <div layout="row">
                                <div flex="50">
                                    <md-checkbox style="margin:10px 0" ng-model="IntMngCtrl.checkbox" aria-label="start project" class="md-primary">Start running the job</md-checkbox>
                                </div>
                                <div flex="50" class="text-right" ng-if="IntMngCtrl.activeIndex == 1">
                                    <a ng-if="IntMngCtrl.showSynWithZenefits" href="https://secure.zenefits.com/oauth2/platform-authorize/?scope=platform companies people people.work_email people.manager people.status employments&state={{companyDetails.company_code}}&redirect_uri=http://202.63.105.85/mintmesh/getAccesCode&response_type=code&client_id=5zr3cWgul9peKR3al1AZ65qcsbWC3JJr8jRd0IDU"><img alt="Sync with Zenefits" height="42" width="200" src="https://secure.zenefits.com/static/img/sync-with-zenefits-platform-button.png" srcset="https://secure.zenefits.com/static/img/sync-with-zenefits-platform-button.png 1x, https://secure.zenefits.com/static/img/sync-with-zenefits-platform-button@2x.png 2x" style="border:none;"/></a>
                                    <img ng-if="!IntMngCtrl.showSynWithZenefits" alt="Sync with Zenefits" height="42" width="200" src="https://secure.zenefits.com/static/img/sync-with-zenefits-platform-button.png" srcset="https://secure.zenefits.com/static/img/sync-with-zenefits-platform-button.png 1x, https://secure.zenefits.com/static/img/sync-with-zenefits-platform-button@2x.png 2x" style="opacity: 0.8;border: none;cursor:not-allowed;"/>
                                </div>
                            </div>
                            <div ng-if="IntMngCtrl.activeIndex == 1 && !IntMngCtrl.zenefitsInProgress" class="msg-job-run">
                                <p ng-if="!IntMngCtrl.startRunJob">Check the box for start running the job and click Save.</p>
                                <p ng-if="IntMngCtrl.startRunJob">Uncheck  the box for stop running the job and click Save.</p>
                            </div>
                            <!-- <div class="loader" ng-if="IntMngCtrl.loader">
                                <img src="public/images/loader/spin.gif" alt="loader" width="25%">
                            </div> -->
                        </form>
                    </md-card-content>
                    <md-card-actions style="min-height: 53px;">
                        <div class="bor" ng-show="suc_fac_form.$dirty" layout="row">
                        <div flex>
                            <span ng-if="IntMngCtrl.loading"><img src="public/images/loader/upload_file.gif" alt="loader">Saving...</span>
                            <span ng-if="IntMngCtrl.sucMsg" class="suc" ng-bind="IntMngCtrl.sucMsg"></span>
                        </div>
                        <span flex></span>
                        <md-button class="mm-btn" ng-click="IntMngCtrl.update(suc_fac_form.$valid)" ng-disabled="IntMngCtrl.loading">
                            save
                        </md-button>
                        </div>
                    </md-card-actions>

                    <!--<div class="loader" ng-if="IntMngCtrl.noPartners && !IntMngCtrl.loader">
                        <h4 class="err">No Partner Found.</h4>
                    </div>-->
                </md-card>
            </div>
        </div>
    </div>
</div>