<div class="my-profile">
	<div class="container">
		<div class="details">
			<div class="content">
				<form name="my_profile_form" novalidate>
					<div id="display_pic"></div>
					<p class='add-text'>User Photo</p>
					<!-- <div class="checkbox" ng-style="{'pointer-events': MyProfileCtrl.has_image == true ? 'auto' : 'none'}" ng-show="{{::userPermissions.is_primary == 1}}">
	  					<input id="disabled" type="hidden" name="flag" value="0">
	  					<input id="checkbox" type="checkbox" name="flag" value="1" onchange="angular.element(this).scope().MyProfileCtrl.change()">
	  					<label for="checkbox">Set as Company Profile pic</label>
					</div> -->
					<div class="first">
						<md-input-container class="md-block">
		                    <label>USER NAME</label>
		                    <input type="text" name="name" ng-model="MyProfileCtrl.myProfile.user_name" required ng-class="{'has-error-border':my_profile_form.name.$invalid && MyProfileCtrl.errCond}" autofocus>
		                    <div ng-if="my_profile_form.name.$error.required && MyProfileCtrl.errCond" class="has-error-msg">Please Enter Name</div>
		                </md-input-container>
		                <md-input-container class="md-block" style="margin-bottom:0;pointer-events:none;">
		                    <label>EMAIL</label>
		                    <input type="text" name="emailid" ng-model="MyProfileCtrl.myProfile.user_email" required ng-pattern="/^[a-z0-9A-Z._%+-]+@[a-zA-Z]+\.[a-z]{2,3}$/" ng-class="{'has-error-border':my_profile_form.emailid.$invalid && MyProfileCtrl.errCond}" tabindex="-1">
		                    <div ng-if="my_profile_form.emailid.$error.required && MyProfileCtrl.errCond" class="has-error-msg">Please Enter Email Address</div>
		                    <div ng-if="my_profile_form.emailid.$error.pattern && MyProfileCtrl.errCond" class="has-error-msg">Please Enter Valid Email Address</div>
		                </md-input-container>
		                <span ng-click="MyProfileCtrl.setPassword();" class="change">Change Password</span>
		            </div>
		        </form>
		    </div>
		    <div class="footer clearfix">
		    	<div class="pull-left">
					<span style="line-height:50px;">
						<span ng-if="MyProfileCtrl.loader"><img src="public/images/loader/upload_file.gif" alt="loader" style="margin:5px;"> Saving Changes</span>
						<span class="message fade" ng-if="MyProfileCtrl.message" ng-bind="MyProfileCtrl.successMsg"></span>
					</span>
				</div>
				<div class="pull-right disabled" ng-style="{'pointer-events': my_profile_form.$dirty || MyProfileCtrl.changeFound ? 'auto' : 'none', 'opacity': my_profile_form.$dirty || MyProfileCtrl.changeFound ? '1' : '0.5'}">
					<span class="btn-cancel ripplelink" data-ripple-color="#757575" ng-click="MyProfileCtrl.cancel('user');">Reset</span>
					<span class="btn-save-changes ripplelink" ng-click="MyProfileCtrl.saveChanges(my_profile_form.$valid)">Save Changes</span>
				</div>
		    </div>
		</div>
	</div>
</div>