<div class="content">
    <form name="new_user_form" novalidate>
        <div class="display-pic" ng-style="{'pointer-events' : UserGroupCtrl.readable ? 'none' : 'auto'}" onkeypress="return event.keyCode == 9">
            <div id="display_pic" class="change"></div>
            <p class='add-text' ng-bind="UserGroupCtrl.textCondition ? 'USER PHOTO' : 'ADD PHOTO'">ADD PHOTO</p>
        </div>
        <div class="clearfix">
            <md-input-container class="md-block" ng-if="!UserGroupCtrl.newPerson">
                <label>EMAIL</label>
                <input type="text" ng-disabled="UserGroupCtrl.newPerson ? '' : true" name="emailid" ng-model="UserGroupCtrl.personDetails.emailid">
                <input type="hidden" name="emailid" value="{{UserGroupCtrl.personDetails.emailid}}">
            </md-input-container>
            <md-input-container class="md-block" ng-if="UserGroupCtrl.newPerson">
                <label>EMAIL</label>
                <div angucomplete-alt id="ex1"
                     maxlength="50"
                     pause="100"
                     remote-api-handler="UserGroupCtrl.getServices"
                     title-field="emailid"
                     selected-object="UserGroupCtrl.selectedEmail"
                     search-fields="name"
                     title-field="name"
                     minlength="1"
                     input-class="md-input"
                     match-class="highlight"
                     field-required="true"
                     input-name="emailid"
                     ng-class="{'has-error-border': (new_user_form.emailid.$invalid && UserGroupCtrl.errCond) || UserGroupCtrl.backendError}">
                </div>
                <div ng-if="new_user_form.emailid.$error.hasOwnProperty('autocomplete-required') && UserGroupCtrl.errCond" class="has-error-msg">Please enter Email.</div>
                <div ng-if="UserGroupCtrl.backendError" class="has-error-msg" ng-bind="UserGroupCtrl.backendError" style="text-transform: capitalize;"></div>
            </md-input-container>
            <md-input-container class="md-block">
                <label>NAME</label>
                <input type="text" ng-disabled="true" name="fullname" ng-model="UserGroupCtrl.personDetails.fullname">
                <input type="hidden" name="fullname" value="{{UserGroupCtrl.personDetails.fullname}}">
            </md-input-container>
            <!--<md-input-container class="md-block">
                <label>DESIGNATION</label>
                <input type="text" ng-disabled="UserGroupCtrl.readable" name="designation" ng-model="UserGroupCtrl.personDetails.designation" required ng-class="{'has-error-border':new_user_form.designation.$invalid && UserGroupCtrl.errCond}">
                <div ng-if="new_user_form.designation.$error.required && UserGroupCtrl.errCond" class="has-error-msg">Please Enter Designation</div>
            </md-input-container>-->
        </div>
        <!--<div class="clearfix">
            <md-input-container class="md-block">
                <label>LOCATION</label>
                <input type="text" ng-disabled="UserGroupCtrl.readable" name="location" ng-model="UserGroupCtrl.personDetails.location" required ng-class="{'has-error-border':new_user_form.location.$invalid && UserGroupCtrl.errCond}" ng-autocomplete="UserGroupCtrl.geo_location" details="UserGroupCtrl.geo_details" options="UserGroupCtrl.geo_options" apiplaceholder="">
                <div ng-if="new_user_form.location.$error.required && UserGroupCtrl.errCond" class="has-error-msg">Please Enter Location</div>
            </md-input-container>
        </div>-->
        <div class="clearfix">
            <md-input-container class="md-block select-box">
                <label style="display:none">STATUS</label>
                <md-select ng-disabled="UserGroupCtrl.readable" name="status" ng-model="UserGroupCtrl.personDetails.status" required ng-class="{'has-error-border':new_user_form.status.$invalid && UserGroupCtrl.errCond}">
                    <md-option ng-repeat="status in UserGroupCtrl.statusText" ng-value="status">{{status}}</md-option>
                </md-select>
                <div class="error-spacer"></div>
                <div ng-if="new_user_form.status.$error.required && UserGroupCtrl.errCond"  class="has-error-msg">Please select Status.</div>
            </md-input-container>
            <md-input-container class="md-block select-box">
                <label style="display:none">USER GROUP</label>
                <md-select ng-disabled="UserGroupCtrl.readable" name="group_id" ng-model="UserGroupCtrl.personDetails.group_id" required ng-class="{'error-border':new_user_form.group_id.$invalid && UserGroupCtrl.errCond}">
                    <md-option ng-repeat="group in UserGroupCtrl.groupNames" ng-value="group.group_id">{{group.name| uppercase}}</md-option>
                </md-select>
                <div class="error-spacer"></div>
                <div ng-if="new_user_form.group_id.$error.required && UserGroupCtrl.errCond"  class="has-error-msg">Please select Group.</div>
            </md-input-container>
        </div>
        <div class="clearfix" ng-show="userPermissions.is_primary == 1 && UserGroupCtrl.personDetails.expired == 1">
            <span class="resend-activation" ng-click="UserGroupCtrl.resendActivation($event)">Resend Activation</span>
        </div>
    </form>
</div>
<div class="footer clearfix">
    <div class="pull-left">
        <span style="line-height:50px;">
            <span ng-if="UserGroupCtrl.loader"><img src="public/images/loader/upload_file.gif" alt="loader" style="margin:5px;"><span ng-bind="UserGroupCtrl.newPerson ? 'Creating' : 'Updating'"></span></span>
            <span class="message fade" ng-if="UserGroupCtrl.message" ng-bind="UserGroupCtrl.backendMsg"></span>
        </span>
    </div>
    <div class="pull-right disabled" ng-style="{'pointer-events': new_user_form.$dirty || UserGroupCtrl.changeFound.person ? 'auto' : 'none', 'opacity': new_user_form.$dirty || UserGroupCtrl.changeFound.person ? '1' : '0.5'}">
        <span class="btn-add-new-user ripplelink" ng-click="new_user_form.$dirty || UserGroupCtrl.changeFound.person ? UserGroupCtrl.addPerson(new_user_form.$valid, UserGroupCtrl.personDetails.user_id, UserGroupCtrl.newPerson) : ''" ng-bind="UserGroupCtrl.newPerson ? 'ADD USER' : 'SAVE
            CHANGES'"></span>
    </div>
</div>


<!-- Resend Activation Modal -->
<div class="modal fade" id="resend_activation" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Resend Activation Status</h4>
            </div>
            <div class="modal-body">
                <p>Email activation link has been sent to <u>{{UserGroupCtrl.personDetails.emailid}}</u> email id.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">OKAY</button>
            </div>
        </div>
    </div>
</div>