<div class="modal-header">
    <h3 class="modal-title" id="modal-title">CHANGE PASSWORD</h3>
    <img src="public/images/material_icons/close.svg" ng-click="$dismiss()">
</div>
<div class="modal-body" id="modal-body">
    <form name="change_password_form" novalidate>
        <div class="details">
            <md-input-container class="md-block">
                <label>CURRENT PASSWORD</label>
                    <input type="password" name="password_old" ng-model="MyProfileCtrl.passwords.password_old" required ng-pattern="/^(?=.*[a-zA-Z0-9]).{6,16}$/"  ng-class="{'has-error-border':change_password_form.password_old.$invalid && MyProfileCtrl.errCond || MyProfileCtrl.backendMsg}" value="123456">
                    <div ng-if="change_password_form.password_old.$error.required && MyProfileCtrl.errCond" class="has-error-msg">Please enter Password.</div>
                    <div ng-if="change_password_form.password_old.$error.pattern && MyProfileCtrl.errCond" class="has-error-msg">Please enter atleast 6 characters.</div>
                    <div ng-if="MyProfileCtrl.backendMsg" ng-bind="MyProfileCtrl.backendMsg" class="has-error-msg" style="text-transform: capitalize;"></div>
            </md-input-container>
            <md-input-container class="md-block">
                <label>NEW PASSWORD</label>
                    <input type="password" id="new_password" name="password_new" ng-model="MyProfileCtrl.passwords.password_new" required ng-pattern="/^(?=.*[a-zA-Z0-9]).{6,16}$/"  ng-class="{'has-error-border':change_password_form.password_new.$invalid && MyProfileCtrl.errCond}" value="123456">
                    <div ng-if="change_password_form.password_new.$error.required && MyProfileCtrl.errCond" class="has-error-msg">Please enter New Password.</div>
                    <div ng-if="change_password_form.password_new.$error.pattern && MyProfileCtrl.errCond" class="has-error-msg">Please enter atleast 6 characters.</div>
            </md-input-container>
            <md-input-container class="md-block" style="margin-bottom: 18px">
                <label>CONFIRM PASSWORD</label>
                    <input type="password" name="password_new_confirmation" ng-model="MyProfileCtrl.passwords.password_new_confirmation" pw-match="new_password"  ng-class="{'has-error-border':change_password_form.password_new_confirmation.$invalid && MyProfileCtrl.errCond}" value="123456">
                    <div ng-if="change_password_form.password_new_confirmation.$error.pwmatch && MyProfileCtrl.errCond" class="has-error-msg">Password doesn't match.</div>
            </md-input-container>
        </div>
    </form>
</div>
<div class="modal-footer">
    <div class="pull-left">
        <span style="line-height:68px;" ng-if="MyProfileCtrl.modalLoader">
            <span><img src="public/images/loader/upload_file.gif" alt="loader" style="margin:5px;"> Updating</span>
            <span class="message fade" ng-if="MyProfileCtrl.message" ng-bind="MyProfileCtrl.successMsg"></span>
        </span>
    </div>
    <div class="pull-right disabled">
        <span class="btn-confirm ripplelink" ng-click="MyProfileCtrl.changePassword(change_password_form.$valid)">Change Password<img src="public/images/loader/dot.svg" alt="dot" style="margin-top:8px;" ng-if="MyProfileCtrl.loader"></span>
    </div>
</div>