<div class="settings">
    <div class="sub-header">
        <div class="container">
            <ul>
                    <!-- <li><a ui-sref="^.settings.companyProfile" ui-sref-active="active" style="margin-left:0;"><span class="background one"></span><span class="text">COMPANY PROFILE</span></a></li> -->
                <li><a ui-sref="^.settings.myProfile" ui-sref-active="active"><span  class="background two"></span><span class="text">MY PROFILE</span></a></li>
                <li><a ui-sref="^.settings.userGroups" ui-sref-active="active"><span  class="background three"></span><span class="text">USER GROUP</span></a></li>
                <!--<li><a ui-sref="^.settings.configManager" ui-sref-active="active"><span  class="background four"></span><span class="text">CONFIGURATION MANAGER</span></a></li>-->
                <li><a ui-sref="^.settings.intManager" ui-sref-active="active"><span  class="background five"></span><span class="text">INTEGRATION MANAGER</span></a></li>
            </ul>
        </div>
    </div>

    <div ui-view></div>
</div>