<div class="campaigns">
	<div class="sub-header">
		<div class="container">
			<ul>
				<li><a ui-sref="^.campaignView.editCampaign" ui-sref-active="active"><span class="background three"></span><span class="text">CAMPAIGN DETAILS</span></a></li>
				<li><a ui-sref="^.campaignView.allCandidates" ui-sref-active="active"><span  class="background two"></span><span class="text">ALL CANDIDATES</span></a></li>
            <li><a ui-sref="^.campaignView.screenedCandidates" ui-sref-active="active"><span  class="background two"></span><span class="text">SCREENED CANDIDATES</span></a></li>
            <li></li>
			</ul>
		</div>
	</div>
	<div ui-view class="animated fadeIn"></div>
</div>
