<div class="questions">
	<div layout="column" class="container-box">
		<div class="questions-list">
			<div class="header" style="border-color:transparent">
				<div class="container">
					<div layout="row" >
						<h4 class="title">QUESTIONS</h4>
                  <i flex></i>
                  <md-button class="md-raised action delete-all mm-slide-left" ng-if="QuestionsListCtrl.selectedQuestions.length > 1" ng-click="QuestionsListCtrl.deleteQuestion()">DELETE</md-button>
						<md-button ui-sref="app.campaigns.CreateQuestion({mode:'add', id:0})" class="md-raised action">CREATE QUESTION</md-button>
					</div>
				</div>
			</div>

			<div class="section container" layout="row" style="clear:both">
				<div id="grid" ui-grid="QuestionsListCtrl.gridOptions" class="grid" ui-grid-selection>
					
					<div class="grid-msg-overlay" ng-if="QuestionsListCtrl.grid.inProgress">
						<div class="msg">
							<span>
								<img src="public/images/loader/spin.gif" alt="loader" width="18%">
							</span>
						</div>
					</div>

					<div class="grid-msg-overlay" ng-if="!QuestionsListCtrl.gridOptions.data.length">
						<div class="msg">
							<span ng-bind="QuestionsListCtrl.grid.responseMsg"></span>
						</div>
					</div>

				</div>
			</div>

			<div class="container">
				<div class="footer clearfix" layout="row">
					<div class="paging col-sm-4 col-sm-offset-4 text-center">
						<ul uib-pagination total-items="QuestionsListCtrl.grid.totalRecords" ng-model="QuestionsListCtrl.grid.pageNo" max-size="3" direction-links="false" force-ellipses="true" ng-change="QuestionsListCtrl.getQuestionList()" boundary-link-numbers="true" rotate="false"></ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>



<!-- Test Name -->
<script type="text/ng-template" id="action.html">
	<div class="ui-grid-cell-contents ui-grid-details">
      <a class="name" ui-sref="app.campaigns.CreateQuestion({mode:'view', id:COL_FIELD})" ng-click="$event.stopPropagation()"><img src="public/images/eye.png" alt="view"></a>
      <a class="name" ui-sref="app.campaigns.CreateQuestion({mode:'edit', id:COL_FIELD})" ng-click="$event.stopPropagation()"><img src="public/images/edit.png" alt="view"></a>
      <a class="name" ng-click="grid.appScope.deleteQuestion(COL_FIELD);$event.stopPropagation()"><img src="public/images/bin.png" alt="view"></a>
	</div>
</script>