<div class="all-campaigns questions">
    <div class="container">
         <div class="row">
               <div class="col-sm-12" style="padding-bottom:50px;">
                  <div class="box">
                     <div class="box-header clearfix">
                        <div class="col-sm-4">
                              <span> QUESTIONS ({{QuestionsListCtrl.grid.totalRecords}})</span>
                        </div>
                        <md-input-container class="filter">
                              <label style="display:none !important">Filter By Question Type</label>
                              <md-select ng-model="QuestionsListCtrl.grid.filter" md-on-close="QuestionsListCtrl.applyFilter()"
                                       data-md-container-class="multiple-select  multiple-select-assessment" multiple>
                                 <md-optgroup ng-repeat="parent in QuestionsListCtrl.filterOptions" label="{{parent.name}}">
                                    <md-option ng-value="children.id" ng-repeat="children in parent.children">{{children.name}}</md-option>
                                 </md-optgroup>
                              </md-select>
                        </md-input-container>
                        <div class="col-sm-3 pull-right">
                              <div data-epi-search data-opts="QuestionsListCtrl.search_opts" data-path="templates/components/"></div>
                        </div>
                        
                     </div>
                     <div class="box-content questions-list">
                        <div id="grid" ui-grid="QuestionsListCtrl.gridOptions" class="grid" ui-grid-selection style="border: 0;">
                           <div class="grid-msg-overlay" ng-if="QuestionsListCtrl.grid.inProgress">
                              <div class="msg">
                                 <span>
                                    <img src="public/images/loader/spin.gif" alt="loader" width="18%">
                                 </span>
                              </div>
                           </div>
                           <div class="grid-msg-overlay" ng-if="!QuestionsListCtrl.gridOptions.data.length && !QuestionsListCtrl.grid.inProgress">
                              <div class="msg">
                                 <span ng-bind="QuestionsListCtrl.grid.responseMsg"></span>
                              </div>
                           </div>	
                        </div>
                     </div>
                     <div class="box-footer clearfix">
                        <div class="paging col-sm-4 col-sm-offset-4 text-center" ng-if="QuestionsListCtrl.grid.totalRecords > 10">
                              <ul uib-pagination total-items="QuestionsListCtrl.grid.totalRecords" ng-model="QuestionsListCtrl.grid.pageNo" max-size="3" direction-links="false" force-ellipses="true" ng-change="QuestionsListCtrl.getQuestionList()" boundary-link-numbers="true" rotate="false"></ul>
                        </div>
                        <md-button class="md-raised action delete-all pull-right mm-slide-left" ng-if="QuestionsListCtrl.selectedQuestions.length > 1" ng-click="QuestionsListCtrl.deleteQuestion()">DELETE</md-button>
                     </div>
                  </div>
               </div>
         </div>
    </div>
</div>


<!-- <div class="questions">
	<div layout="column" class="container-box">
		<div class="questions-list">
			<div class="header" style="border-color:transparent">
				<div class="container">
					<div layout="row" >
						<h4 class="title">QUESTIONS</h4>
                  <i flex></i>
                  <md-button class="md-raised action delete-all mm-slide-left" ng-if="QuestionsListCtrl.selectedQuestions.length > 1" ng-click="QuestionsListCtrl.deleteQuestion()">DELETE</md-button>
						<md-button ui-sref="app.campaigns.CreateQuestion({mode:'add', id:0})" class="md-raised action">CREATE QUESTION</md-button>
					</div>
				</div>
			</div>

			<div class="section container" layout="row" style="clear:both">
				<div id="grid" ui-grid="QuestionsListCtrl.gridOptions" class="grid" ui-grid-selection>
					
					<div class="grid-msg-overlay" ng-if="QuestionsListCtrl.grid.inProgress">
						<div class="msg">
							<span>
								<img src="public/images/loader/spin.gif" alt="loader" width="18%">
							</span>
						</div>
					</div>

					<div class="grid-msg-overlay" ng-if="!QuestionsListCtrl.gridOptions.data.length">
						<div class="msg">
							<span ng-bind="QuestionsListCtrl.grid.responseMsg"></span>
						</div>
					</div>

				</div>
			</div>

			<div class="container">
				<div class="footer clearfix" layout="row">
					<div class="paging col-sm-4 col-sm-offset-4 text-center">
						<ul uib-pagination total-items="QuestionsListCtrl.grid.totalRecords" ng-model="QuestionsListCtrl.grid.pageNo" max-size="3" direction-links="false" force-ellipses="true" ng-change="QuestionsListCtrl.getQuestionList()" boundary-link-numbers="true" rotate="false"></ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</div> -->



<!-- Action -->
<script type="text/ng-template" id="action.html">
	<div class="ui-grid-cell-contents ui-grid-details">
      <a class="name" ui-sref="app.campaigns.CreateQuestion({mode:'view', id:COL_FIELD})" ng-click="$event.stopPropagation()"><img src="public/images/eye.png" alt="view"></a>
      <a class="name" ui-sref="app.campaigns.CreateQuestion({mode:'edit', id:COL_FIELD})" ng-click="$event.stopPropagation()"><img src="public/images/edit.png" alt="view"></a>
      <a class="name" ng-click="grid.appScope.deleteQuestion(COL_FIELD);$event.stopPropagation()"><img src="public/images/bin.png" alt="view"></a>
	</div>
</script>