<div class="modal-header" ng-if="CommonConfirmMsgCtrl.actionScreen">
	<img src="public/images/cross_icon.png" alt="close" class="img-close" ng-click="$dismiss()">
	<div style="padding:40px;overflow:hidden">
		<span>
			<p>{{CommonConfirmMsgCtrl.data.firstMsg}} <br>{{CommonConfirmMsgCtrl.data.secondMsg}}</p>
			<div style="background:#fff;border:1px solid red;color:#e66a6a" ng-click="$dismiss()">No</div>
			<div ng-click="CommonConfirmMsgCtrl.userConfirm()" class="load ripplelink pull-right">Yes<img src="public/images/loader/dot.svg" ng-if="CommonConfirmMsgCtrl.
			success_loader"/></div>
		</span>
	</div>
</div>
<div class="invited-contact animated zoomIn" ng-if="!CommonConfirmMsgCtrl.actionScreen" style="padding: 47px">
    <div class="modal-header text-center" style="border-bottom:0">
        <img src="public/images/tickmark.svg" alt="tickmark">
        <h3 ng-bind="CommonConfirmMsgCtrl.responseMsg"></h3>
    </div>
</div>

