<div class="modal-header">
	<img src="public/images/cross_icon.png" alt="close" class="img-close" ng-click="$dismiss()">
	<div style="padding:40px;overflow:hidden">
		<p>Are you sure want to <br> close the JOB ?</p>
		<div ng-click="ConfirmMsgCtrl.userConfirm()" class="load">Yes<img src="public/images/loader/dot.svg" ng-if="ConfirmMsgCtrl.success_loader"/></div>
		<div style="float:right;background:#fff;border:1px solid red;color:#e66a6a" ng-click="$dismiss()">No</div>
	</div>
</div>
