<div  style="background:#F0F0F0" class="upload-file-bucket" ng-init="fileUp.uploadFile()">
     <div class="modal-header" ng-style="{'background':fileUp.bucket.color}">
        <h4 class="modal-title text-center">{{fileUp.bucket.name | uppercase}}</h4>
    </div>
    <form name="fileup" ng-submit="fileUp.onfileSubmit(fileup.$valid)" novalidate>
        <div class="modal-body" style="padding: 4% 10% 2% 10%">
           
            <div ng-if="fileUp.newBucket">
                <input placeholder="BucketName" bucket-name-chk my-bucket={{fileUp.bucketNames}} my-name={{fileUp.customName}} name="customName" ng-model="fileUp.customName" required type="text" id="bucketName">
                <span style="color:red;display:inline-block" ng-show="fileup.customName.$error.required && fileUp.error_msg_show">Bucket Name Field is Required</span>
                <span style="color:red;display:inline-block" ng-show="fileup.customName.$error.bucketmatch && fileUp.error_msg_show">Choose another name</span>
            </div>
            <label style="display:table;margin:14px 0 0 0">
                <div class="customInput" ng-style="fileUp.obj">
                    <input type="file" name="file" valid-file ng-model="fileUp.file" style="border:0;display:none" id="fileUploads" onchange="callFileUp(this)" accept=".csv,.xlsx,.xls" required>
                    Browse File
                </div>
                <span id="file-name" ng-style="{'color':fileUp.bucket.color}"></span>
            </label>
            <span ng-if="fileup.file.$error.required && fileUp.error_msg_show" class="error-file">Please Choose File</span>
            <!-- Backend Errors -->
            <span class="error-file" ng-if="!fileUp.success">{{fileUp.inValidFile}}</span>
            <span ng-style="{'color':fileUp.bucket.color}" ng-if="fileUp.success">{{fileUp.success}}</span>

            <ul class="hints">
                <li>Only .csv and .xlsx files are allowed.</li>
                <li>File size must not exceed 25MB.</li>
            </ul>
        </div>
        <div class="modal-footer" style="background: #e9e9e9">
       
            <input class="btn btn-link pull-left" style="outline:0;padding:6px 0px;text-align:left" ng-style='{color:fileUp.bucket.color}' ng-click="$dismiss()" value="Cancel">
           <img src="public/images/loader/upload_file.gif" alt="loader" ng-if="fileUp.upload_load_cond">&nbsp;&nbsp;<button class="btn" type="submit" ng-style='{{fileUp.obj}}'  style="border-radius:0;background:#fff" ng-if="!fileUp.success_upload">Upload</button>
           <button class="btn" ng-style='{{fileUp.obj}}' type="button" style="border-radius:0;background:#fff" ng-click="$dismiss()" ng-if="fileUp.success_upload">OK</button>
        </div>
    </form>
</div>
<script type="text/javascript">
    function callFileUp(a){
        var files = a.files[0].name;
        var x = document.getElementById("file-name");
        x.innerHTML=files;
    }
</script>