<div class="modal-body">
    <div class="new-contact">
       <div>
            <img src="public/images/cross-grey.svg" alt="close" class="pull-right" ng-click="$dismiss()">
        </div>
        <div class="clearfix"></div>
        <div class="heading text-center">
            <h3 style="margin:0">Add Contact to Group</h3>
            <p>
                <span style="color:#989898;">Create your own contacts group Through uploading the contacts list</span>
            </p>
        </div>
        <div class="content">
            <form name="upload_contact_form" novalidate>
                <md-input-container class="md-block" style="width:45%">
                    <label style="display:none">Select Contact Group</label>
                    <md-select name="bucket" ng-model="SingleContCtrl.newContact.bucket" required ng-class="{'has-error-border':upload_contact_form.bucket.$invalid && SingleContCtrl.errCond}">
                        <md-option ng-repeat="bucket in SingleContCtrl.bucketList" ng-value="bucket">
                            {{bucket.bucket_name}}
                        </md-option>
                    </md-select>
                    <div ng-if="upload_contact_form.bucket.$error.required && SingleContCtrl.errCond" style="position:absolute" class="has-error-msg">Please Select Bucket Name</div>
                </md-input-container>
                <div class="pull-left">
                    <md-input-container class="md-block">
                        <label>FIRST NAME</label>
                        <input type="text" name="firstname" ng-model="SingleContCtrl.newContact.firstname" required ng-class="{'has-error-border':upload_contact_form.firstname.$invalid && SingleContCtrl.errCond}">
                        <div ng-if="upload_contact_form.firstname.$error.required && SingleContCtrl.errCond" class="has-error-msg">Please Enter First Name</div>
                    </md-input-container>
                    <md-input-container class="md-block">
                        <label>MOBILE</label>
                        <input type="text" name="mobile" ng-model="SingleContCtrl.newContact.mobile" required ng-class="{'has-error-border':upload_contact_form.mobile.$invalid && SingleContCtrl.errCond}">
                        <div ng-if="upload_contact_form.mobile.$error.required && SingleContCtrl.errCond" class="has-error-msg">Please Enter Mobile Number</div>
                    </md-input-container>
                    <md-input-container class="md-block">
                        <label style="display:none">STATUS</label>
                        <md-select name="status" ng-model="SingleContCtrl.newContact.status" required ng-class="{'has-error-border':upload_contact_form.status.$invalid && SingleContCtrl.errCond}">
                            <md-option ng-repeat="status in SingleContCtrl.statusText" ng-value="status">{{status}}</md-option>
                        </md-select>
                        <div ng-if="upload_contact_form.status.$error.required && SingleContCtrl.errCond" style="position:absolute" class="has-error-msg">Please Select Status</div>
                    </md-input-container>
                </div>
                <div class="pull-right">
                    <md-input-container class="md-block">
                        <label>LAST NAME</label>
                        <input type="text" name="lastname" ng-model="SingleContCtrl.newContact.lastname" required ng-class="{'has-error-border':upload_contact_form.lastname.$invalid && SingleContCtrl.errCond}">
                        <div ng-if="upload_contact_form.lastname.$error.required && SingleContCtrl.errCond" class="has-error-msg">Please Enter Last Name</div>
                    </md-input-container>
                    <md-input-container class="md-block">
                        <label>EMAIL</label>
                        <input type="text" name="email" ng-model="SingleContCtrl.newContact.email" required ng-pattern="/^[a-z0-9A-Z._%+-]+@[a-zA-Z]+\.[a-z]{2,3}$/" ng-class="{'has-error-border':upload_contact_form.email.$invalid && SingleContCtrl.errCond}">
                        <div ng-if="upload_contact_form.email.$error.required && SingleContCtrl.errCond" class="has-error-msg">Please Enter Email Address</div>
                        <div ng-if="upload_contact_form.email.$error.pattern && SingleContCtrl.errCond" class="has-error-msg">Please Enter Valid Email Address</div>
                    </md-input-container>
                </div>
            </form>
        </div>
    </div> 
            <!-- <div style="width:60%">
                <md-input-container class="md-block" style="margin:0">
                    <label>Bucket Name</label>
                    <input type="text" name="bucketName" ng-model="UploadContCtrl.modal.bucketName" required ng-class="{'has-error-border':new_bucket_form.bucketName.$invalid && UploadContCtrl.errorFromData}" check-bucket array-bucket="{{UploadContCtrl.bucketsList}}" bucket-name="{{UploadContCtrl.modal.bucketName}}" autocomplete="off">
                    <div ng-if="new_bucket_form.bucketName.$error.required && UploadContCtrl.errorFromData" class="has-error-msg">Please Enter Bucket Name</div>
                    <div ng-if="new_bucket_form.bucketName.$error.bucketmatch && UploadContCtrl.errorFromData && !new_bucket_form.bucketName.$error.required" class="has-error-msg">Bucket Name Already Exists</div>
                </md-input-container>
            </div> -->
</div>
<div class="modal-footer clearfix">
    <div class="pull-right">
        <span class="btn-cancel" ng-click="$dismiss()">Cancel</span>
        <span class="btn-upload" ng-click="SingleContCtrl.add(upload_contact_form.$valid)">ADD CONTACT</span>
    </div>
</div>