<div class="modal-body" style="width:100%;height:100%;cursor:default;" ng-click="SingleContCtrl.closeDropdown()">
    <div class="new-contact">
       <div>
            <img src="public/images/cross-grey.svg" alt="close" class="pull-right" ng-click="$dismiss()">
        </div>
        <div class="clearfix"></div>
        <div class="heading text-center">
            <h3 style="margin:0;margin-bottom:14px">Add Contact to Group</h3>
            <!-- <p>
                <span style="color:#989898;">Create your own contacts to group</span>
            </p> -->
        </div>
        <div class="content">
            <form name="upload_contact_form" novalidate>
                <md-input-container class="md-block" style="width:45%">
                    <label style="display:none">SELECT GROUP</label>
                    <md-select name="bucket_id" ng-model="SingleContCtrl.newContact.bucket" required ng-class="{'has-error-border':upload_contact_form.bucket_id.$invalid && SingleContCtrl.errCond}">
                        <md-option ng-repeat="bucket in SingleContCtrl.bucketList" ng-value="bucket.bucket_id">
                            {{bucket.bucket_name | uppercase}}
                        </md-option>
                    </md-select>
                    <div ng-if="upload_contact_form.bucket_id.$error.required && SingleContCtrl.errCond" style="position:absolute" class="has-error-msg">Please Select Group</div>
                </md-input-container>
                <div class="pull-left">
                    <md-input-container class="md-block">
                        <label>FIRST NAME</label>
                        <input type="text" name="firstname" ng-model="SingleContCtrl.newContact.firstname" required ng-class="{'has-error-border':upload_contact_form.firstname.$invalid && SingleContCtrl.errCond}">
                        <div ng-if="upload_contact_form.firstname.$error.required && SingleContCtrl.errCond" class="has-error-msg">Please Enter First Name</div>
                    </md-input-container>
                     <md-input-container class="md-block">
                        <label>ID</label>
                        <input type="text" name="other_id" ng-model="SingleContCtrl.newContact.otherid">
                    </md-input-container>
                    <md-input-container class="md-block">
                        <label>EMAIL</label>
                        <input type="text" name="emailid" ng-model="SingleContCtrl.newContact.email" required ng-pattern="/^[a-z0-9A-Z._%+-]+@[a-zA-Z]+\.[a-z]{2,3}$/i" ng-class="{'has-error-border':upload_contact_form.emailid.$invalid && SingleContCtrl.errCond}">
                        <div ng-if="upload_contact_form.emailid.$error.required && SingleContCtrl.errCond" class="has-error-msg">Please Enter Email Address</div>
                        <div ng-if="upload_contact_form.emailid.$error.pattern && SingleContCtrl.errCond" class="has-error-msg">Please Enter Valid Email Address</div>
                    </md-input-container>
                </div>
                <div class="pull-right">
                    <md-input-container class="md-block">
                        <label>LAST NAME</label>
                        <input type="text" name="lastname" ng-model="SingleContCtrl.newContact.lastname">
                    </md-input-container>
                    <md-input-container class="md-block">
                        <label>MOBILE</label>
                        <input type="text" name="phone" ng-model="SingleContCtrl.newContact.mobile" ng-pattern="/^\(?([0-9]{3})\)?([ .-]?)([0-9]{3})\2([0-9]{4})$/" ng-class="{'has-error-border':upload_contact_form.phone.$invalid && SingleContCtrl.errCond}">
                        <div ng-if="upload_contact_form.phone.$error.pattern && SingleContCtrl.errCond" class="has-error-msg">Please Enter Valid Mobile Number</div>
                    </md-input-container>
                    <md-input-container class="md-block">
                        <label style="display:none">STATUS</label>
                        <md-select name="status" ng-model="SingleContCtrl.newContact.status">
                            <md-option ng-repeat="status in SingleContCtrl.statusText" ng-value="status">{{status}}</md-option>
                        </md-select>
                    </md-input-container>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="modal-footer clearfix">
    <div class="pull-left">
        <span ng-if="SingleContCtrl.uploadLoader"><img src="public/images/loader/upload_file.gif" alt="loader" style="margin:5px;"> Uploading</span>
        <span ng-if="SingleContCtrl.backendError" style="color:#983a3a;line-height:48px;"><i class="fa fa-times"></i>&nbsp;{{SingleContCtrl.backendMsg}}</span>
    </div>
    <div class="pull-right disabled">
        <span class="btn-cancel" ng-click="$dismiss()">Cancel</span>
        <span class="btn-upload" ng-click="SingleContCtrl.add(upload_contact_form.$valid)">ADD CONTACT</span>
    </div>
</div>