<div class="modal-body" id="modal-body" ng-if="!UploadContCtrl.newBucketModal" style="width:100%;height:100%;">
    <form name="buckets_form">

    <div class="contacts-group">

        <div class="close" ng-click="$dismiss()">
            <img src="public/images/cross-grey.svg" alt="close">
        </div>
        <div class="clearfix"></div>

        <div class="box">

            <div class="box-content text-center">
                <div class="heading">
                    <h3 style="margin:0">Upload Contacts</h3>
                    <p style="margin:14px 0;">
                        <span style="color:#989898;">Organize your contacts in one of the groups below or create your own</span>
                    </p>
                </div>
                <div class="download">
                    <span ng-click="UploadContCtrl.downloadSample()" class="text-center">Download Sample Template</span>    
                </div>
                <div class="file-uploading">
                    <div class="row">
                        <div class="col-sm-4" ng-repeat="bucketList in UploadContCtrl.bucketsList" ng-init="colorCode = UploadContCtrl.colorPicker($index)">
                            <!-- qq uploader -->
                            <div class="upload-bucket" ng-style="{'background':colorCode,'border-color':colorCode}"></div>
                        </div>
                        <div class="col-sm-4" style="margin-bottom:20px;">
                            <div class="upload-bucket new-bucket" ng-click="UploadContCtrl.newBucket()">
                                <p class="own"><i class="fa fa-plus" style="margin-right:3px;"></i>New Group</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>
    </form>

</div>

<form name="new_bucket_form" novalidate>
    <div class="modal-body" ng-if="UploadContCtrl.newBucketModal">
        
        <div class="new-bucket">

            <div>
                <img src="public/images/back-arrow-grey.svg" alt="back" class="pull-left" ng-click="UploadContCtrl.back()">
                <img src="public/images/cross-grey.svg" alt="close" class="pull-right" ng-click="$dismiss()">
            </div>
            <div class="clearfix"></div>

            <div class="text-center">
                 <div class="heading">
                    <h3 style="margin:0">Add New Group</h3>
                    <p style="margin:14px 0;">
                        <span style="color:#989898;">Create your own group and add contacts to the group</span>
                    </p>
                </div>

                <div class="download">
                    <span ng-click="UploadContCtrl.downloadSample()" class="text-center">Download Sample Template</span>    
                </div>

                <div class="content">
                    <md-input-container class="md-block" style="margin:0">
                        <label>Enter Group Name</label>
                        <input type="text" name="bucketName" ng-model="UploadContCtrl.new_bucket.bucketName" required ng-class="{'has-error-border':new_bucket_form.bucketName.$invalid && UploadContCtrl.new_bucket.errorFromData}" check-bucket array-bucket="{{UploadContCtrl.bucketsList}}" bucket-name="{{UploadContCtrl.new_bucket.bucketName}}" autocomplete="off">
                        <div ng-if="new_bucket_form.bucketName.$error.required && UploadContCtrl.new_bucket.errorFromData" class="has-error-msg">Please Enter Bucket Name.</div>
                        <div ng-if="new_bucket_form.bucketName.$error.bucketmatch && UploadContCtrl.new_bucket.errorFromData && !new_bucket_form.bucketName.$error.required" class="has-error-msg">Bucket Name Already Exists.</div>
                    </md-input-container>
                    <div id="new-bucket"></div>
                    <div style="clear:both;margin-top:15px;">
                        <img src="public/images/info.svg" alt="info"/>
                        <span style="color:#999999">Only .csv and .xlsx files are allowed.<br>File size must not exceed 25MB.</span>
                    </div>
                </div>
            </div>

        </div>

    </div>
</form>

<div class="modal-footer clearfix">
    <div class="pull-left" ng-if="UploadContCtrl.newBucketModal">
        <span ng-if="UploadContCtrl.new_bucket.succesLoader"><img src="public/images/loader/upload_file.gif" alt="loader" style="margin:5px;" > Uploading</span>
    </div>
    <div class="pull-left" ng-if="!UploadContCtrl.newBucketModal">
        <span ng-if="UploadContCtrl.uploadLoader"><img src="public/images/loader/upload_file.gif" alt="loader" style="margin:5px;"> Uploading</span>
        <span style="color:#983a3a;line-height:48px;" ng-if="UploadContCtrl.errorUpload"><i class="fa fa-times"></i>&nbsp;Please upload contacts to atleast one group</span>
    </div>
    <div class="pull-right disabled">
        <span class="btn-upload" ng-if="UploadContCtrl.newBucketModal" ng-click="UploadContCtrl.new_bucket.upload(new_bucket_form.$valid)">UPLOAD CONTACTS</span>
        <span class="btn-upload" ng-if="!UploadContCtrl.newBucketModal" ng-click="UploadContCtrl.uploadContacts()">ADD CONTACTS</span>
    </div>
</div>