<div class="invited-contact">
    <div class="modal-header text-center" style="border-bottom:0;padding: 50px 0">
    	<div>
	        <img src="public/images/tickmark.svg" alt="tickmark" style="padding: 0">
	        <h2 style="font-size: 16px;">REQUEST POSTED SUCCESSFULLY</h2>
	    </div>
	    <button class="btn btn-style" type="button" ng-click="succCtrl.goDashBoard()" style="margin-top:5px;padding: 6px 30px">OK</button>
    </div>
</div>