<div ng-if="refStatus.accept">
    <div class="modal-header text-center" style="border-bottom:0">
    	<div>
	        <h5 style="font-size:18px">Are you sure you want to accept the Referral?</h5>
	    </div>
	    <button class="btn btn-default" type="button" ng-click="$dismiss()" style="border:1px solid gray">CANCEL</button>
	    <button class="btn btn-primary" type="button" ng-click="refStatus.referralStatus('ACCEPTED')" style="background:#37b894;border:1px solid #37b894">ACCEPT</button>
    </div>
</div>

<div ng-if="refStatus.decline">
    <div class="modal-header text-center" style="border-bottom:0">
    	<div>
	        <h5 style="font-size:18px">Are you sure you want to decline the Referral?</h5>
	    </div>
	    <button class="btn btn-default" type="button" ng-click="$dismiss()" style="border:1px solid gray">CANCEL</button>
	    <button class="btn btn-primary" type="button" ng-click="refStatus.referralStatus('DECLINED')" style="background:#37b894;border:1px solid #37b894">DECLINE</button>
    </div>
</div>