<div ng-if="refStatus.accept">
    <div class="modal-header">
    	<img src="public/images/cross_icon.png" alt="close" class="img-close" ng-click="$dismiss()">
    	<div style="padding:40px;overflow:hidden">
    		<img src="public/images/user_ico.png" alt="user">
    		<p>Are you sure want to <br> Accept  the  referral?</p>
    		<div ng-click="refStatus.referralStatus('ACCEPTED')">Yes</div>
    		<div style="float:right;background:#fff;border:1px solid red;color:#e66a6a" ng-click="$dismiss()">No</div>
    	</div>
    </div>
</div>
<div ng-if="refStatus.decline">
    <div class="modal-header">
    	<img src="public/images/cross_icon.png" alt="close" class="img-close" ng-click="$dismiss()">
    	<div style="padding:40px;overflow:hidden">
    		<img src="public/images/user_ico.png" alt="user">
    		<p>Are you sure want to <br> Decline  the  referral?</p>
    		<div ng-click="refStatus.referralStatus('DECLINED')">Yes</div>
    		<div style="float:right;background:#fff;border:1px solid red;color:#e66a6a" ng-click="$dismiss()">No</div>
    	</div>
    </div>
</div>
