<div  class="invited-contact" >
    <div class="modal-header text-center" style="border-bottom:0">
        <img src="public/images/tickmark.svg" alt="tickmark">
        <h3>PASSWORD RESET HAS DONE SUCCESSFUL</h3>
    </div>
    <div class="modal-footer" style="border-top:0;padding-bottom:40px">
        <a ui-sref="home" ng-click="$dismiss()"><button class="btn btn-style" type="button" style="padding:10px 40px">OK</button></a>
    </div>
</div>