<div  class="invited-contact" >
    <div class="modal-header text-center" style="border-bottom:0">
        <img src="public/images/tickmark.svg" alt="tickmark">
        <h4 style="padding:10px 0">PASSWORD CREATED SUCCESSFULLY</h4>
    </div>
    <div class="modal-footer" style="border-top:0;padding:0">
        <a ui-sref="home" ng-click="$dismiss()"><button class="btn btn-style" type="button" style="padding: 5px 25px;border-radius: 0px;">OK</button></a>
    </div>
</div>