<h4  class="text-center" ng-if="!!AllJobsCtrl.noLongerAvailable" style="color:#dc4e41" ng-bind="AllJobsCtrl.noLongerAvailable"></h4>
<div class="all-jobs" ng-if="!AllJobsCtrl.noLongerAvailable">
    <h4 class="job-count">{{AllJobsCtrl.infiniteScroll.total_count}} Job(s) found</h4>
    <md-divider></md-divider>
    <div style="position:relative">
        <div class="camp-list">
            <div class="list" ng-init="sh_cd = $stateParams.share_status" infinite-scroll='AllJobsCtrl.infiniteScroll.nextPage()' infinite-scroll-distance='0' infinite-scroll-container="'.camp-list'" style="min-height:350px;height:initial">
                <div class="row" ng-repeat="list in AllJobsCtrl.infiniteScroll.list" ng-click="AllJobsCtrl.updateReferralDetails(list)">
                    <a ui-sref="allJobs.jobDetails({ref: list.ref_code, share_status: sh_cd, jc : jc })" title="" class="detail">
                        <div class="col-sm-7">
                            <p ng-bind="list.job_name"></p>
                            <div class="fields">
                                <span class="label">Experience:</span>
                                <span class="value" ng-bind="list.experience"></span><br>
                                <span class="label">Location:</span>
                                <span class="value" ng-bind="list.location"></span>
                            </div>
                        </div>
                    </a>
                    <div class="col-sm-5 buttons" ng-init="sh_cd = $stateParams.share_status;jc = $stateParams.jc">
                        <a class="camp-btn" ui-sref="allJobs.referralDetails({ref: list.ref_code,flag: 0, status:list.status, jc:jc, share_status: sh_cd})" ng-if="list.post_type == 'external'">REFER</a>
                        <a class="camp-btn" ui-sref="allJobs.candidateDetails({ref: list.ref_code, flag: 0, status:list.status, jc:jc, share_status: sh_cd})" ng-if="list.post_type == 'internal' || sh_cd == 'share' || $stateParams.jc == 2">APPLY</a>
                    </div>
                </div>
                <div class="email-parser-loader" ng-if="AllJobsCtrl.infiniteScroll.busy">
                    <img src="../public/images/loader/spin.gif" alt="spinner">
                </div>
                <div class="overlay text" ng-if="AllJobsCtrl.noJobs">
                    <span>No Jobs Found</span>
                </div>
                <h4 ng-if="AllJobsCtrl.loader" class="loading-infinite">Loading...</h4>
            </div>
        </div>
        <div class="drop-cv">
            Refer friend for future openings here<a class="camp-btn" ui-sref="allJobs.referralDetails({ref: $root.ref,flag: 1,share_status: $stateParams.share_status, jc:$stateParams.jc})">Upload CV</a>
        </div>
    </div>

    <!-- <div class="container">
        <header>
            <div id="logo" ng-hide="AllJobsCtrl.infiniteScroll.company_logo == ''">
                <img ng-src="{{$root.url_spinner_small}}" class="spinner small img-thumbnail">
            </div>
            <span ng-bind="AllJobsCtrl.infiniteScroll.companyName" class="company-name" ng-if="AllJobsCtrl.infiniteScroll.company_logo == ''"></span>            
        </header>
        <section class="job">
            <div class="header clearfix">
                <div class="search pull-left">
                    <div data-epi-search data-opts="AllJobsCtrl.search_opts" data-path="../templates/components/"></div>
                </div>
                <div class="count pull-right">
                    Total Jobs: <span ng-bind="AllJobsCtrl.infiniteScroll.total_count || 0"></span>
                </div>
            </div>
            <div infinite-scroll='AllJobsCtrl.infiniteScroll.nextPage()' infinite-scroll-disabled='AllJobsCtrl.infiniteScroll.busy' infinite-scroll-distance='0' class="list">
                <div class="row" ng-repeat="list in AllJobsCtrl.infiniteScroll.list" ng-click="AllJobsCtrl.updateReferralDetails(list)">
                    <a ui-sref="jobDetails({ref: list.ref_code, share_status: sh_cd, jc : jc })" title="" class="details">
                        <div class="col-sm-8">
                            <span ng-bind="AllJobsCtrl.infiniteScroll.companyName"></span>
                            <p ng-bind="list.job_name"></p>
                            <div class="fields">
                                <span class="label">Experience:</span>
                                <span class="value" ng-bind="list.experience"></span>
                                <span class="label">Location:</span>
                                <span class="value" ng-bind="list.location"></span>
                            </div>
                        </div>
                    </a>
                    <div class="col-sm-4 buttons" ng-init="sh_cd = $stateParams.share_status;jc = $stateParams.jc">
                        <a class="apply" ui-sref="referralDetails({ref: list.ref_code,flag: 0, status:list.status, jc:jc, share_status: sh_cd})" ng-if="list.post_type == 'external'">REFER</a>
                        <a class="apply" ui-sref="candidateDetails({ref: list.ref_code, flag: 0, status:list.status, jc:jc, share_status: sh_cd})" ng-if="list.post_type == 'internal' || sh_cd == 'share' || $stateParams.jc == 2">APPLY</a>
                    </div>
                </div>
                <div class="overlay" ng-if="AllJobsCtrl.loader">
                    <img src="../public/images/loader/spin.gif" alt="spinner" style="width:10%">
                </div>
                <div class="overlay text" ng-if="AllJobsCtrl.noJobs">
                    <span>No Jobs Found</span>
                </div>
                <div class="text-center" ng-if="AllJobsCtrl.infiniteScroll.busy" style="opacity:0.5">
                    <img src="../public/images/loader/spin.gif" alt="spinner" style="width:10%">
                </div>
            </div>
        </section>
        <footer>
            <div class="box">
                <div class="social-media">
                    Share Jobs
                    <div class="social-icons">
                            Go to www.addthis.com/dashboard to customize your tools
                            <div class="addthis_inline_share_toolbox"></div>
                    </div>
                    social media share directive
                    <social-sharing data-opts="AllJobsCtrl.socialMedia" style="margin-top:10px;" data-path="../templates/components"></social-sharing>
                    <copy-url url="{{AllJobsCtrl.copyUrl}}" btn-text="{{AllJobsCtrl.copyText}}"></copy-url>
                </div>
                <div class="drop-cv">
                    Refer friend for future openings here <span><a ui-sref="referralDetails({ref: $root.ref,flag: 1,share_status: $stateParams.share_status, jc:$stateParams.jc})">Upload CV</a></span>
                </div>
            </div>
        </footer>
    </div> -->
</div>
