<div class="all-campaigns">
    <header class="logo container">
        <div layout="column">
            <div layout="row" flex>
                <div id="logo" flex="20" ng-hide="ReferralDetails.company_logo == ''">
                    <img ng-src="{{$root.url_spinner_small}}" class="spinner small img-thumbnail">
                </div>
                <span flex="20" ng-bind="ReferralDetails.company_name" class="company-name" ng-if="ReferralDetails.company_logo == ''"></span>         
                <i flex></i>
                <div class="menu">
                    <span class="tab"><a href="#">Home</a></span>
                    <span class="tab"><a href="#">About {{ReferralDetails.company_name}}</a></span>
                    <span class="tab"><a href="#" ng-click="JobsCtrl.createCampaign()">Join our Talent Community</a></span>
                </div>
            </div>
        </div>
    </header>
    <div class="filters">
        <div class="container" ng-style="{'margin-top' : $state.current.name === 'allJobs.all' ? '0' : '54px'}">
            <div class="des">
                <!-- <h3>
                    <span ng-bind="ReferralDetails.campaign_heading"></span> 
                </h3>
                <h4 class="date">
                    <img src="../public/images/email-parser/calender.svg" alt="calander"/>
                    <span ng-bind="ReferralDetails.start_date"></span>
                    <span ng-bind="ReferralDetails .start_time"></span>
                    &nbsp; to&nbsp;
                    <span ng-bind="ReferralDetails.end_date"></span>
                    <span ng-bind="ReferralDetails.end_time"></span>
                </h4>
                <h4>
                    <img src="../public/images/email-parser/location.svg" alt="location"/>
                    <span ng-bind="ReferralDetails .campaign_location"></span>
                </h4> -->
            </div>
            <div class="user-inputs" ng-if="$state.current.name == 'allJobs.all'">
                <div layout="column">
                    <div layout="row">
                        <div class="form-group search">
                            <i class="material-icons">search</i>
                            <input type="text" class="form-control" name="search-name" ng-model="JobsCtrl.searchOptions.search_name" tabindex="1" placeholder="I am looking for a job.." >
                        </div>
                        <div class="btn-group loc" uib-dropdown>
                            <input id="location" ng-model="JobsCtrl.searchOptions.search_location" name="location" ng-autocomplete="JobsCtrl.geo_location" details="JobsCtrl.geo_details" options="JobsCtrl.geo_options"  tabindex="2" apiplaceholder="Location">
                        </div>
                        <div class="btn-group exp" uib-dropdown>
                            <button id="btn-append-to-single-button"  tabindex="3" type="button" class="btn btn-primary" uib-dropdown-toggle ng-style="{'color' : JobsCtrl.searchOptions.search_experience ? '#555' : ''}">
                                {{JobsCtrl.experienceLabel}} <i class="material-icons animated fadeIn">keyboard_arrow_down</i>
                            </button>
                            <ul class="dropdown-menu animated slideInUp" uib-dropdown-menu role="menu" aria-labelledby="btn-append-to-single-button" >
                                <li role="menuitem" ng-repeat="exp in JobsCtrl.experiences">
                                    <a href="#" ng-click="JobsCtrl.selectExperienc(exp)" 
                                        ng-class="{'exp-active' : exp.experience_name == JobsCtrl.experienceLabel}">{{exp.experience_name}}
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <div class="action">
                            <md-button class="md-raised" tabindex="4" ng-click="JobsCtrl.findJobs()">FIND JOBS</md-button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="content">
        <div class="container" >
            <div layout="column" class="campaign-details">
                <div layout="row" flex>
                    <div flex="70"class="left">
                        <ui-view></ui-view>
                    </div>
                    <div flex="30" class="right">
                        <div class="about-comp">
                            <div class="box">
                                <h4>About <span ng-bind="ReferralDetails.company_name"></span></h4>
                                <span>
                                    {{ReferralDetails.company_name}} is a leading IT solutions provider, offering Applications. Business Process Outsourcing (BPO) and Infrastructure services globally through a combination of technology know how, domain and process expertise. The accolades we have been garnering can be attributed to our undeterred focus in delivering quality solutions across verticals that meet the challenging requirements of our esteemed customers. We have been recently felicitated by the economic times as the most distinguished digital company 2015...  
                                </span>
                                <h5>More..</h5>
                            </div>
                            <!-- <md-divider></md-divider>
                            <div class="suscribe">
                                <div class="row">
                                    <div class="col-sm-8">Wish to submit your profile for future opportunities?</div>
                                    <div class="col-sm-4 action"><button class="camp-btn">SUBSCRIBE</button></div>
                                </div>
                            </div> -->
                        </div>
                        <div class="create-camp" ng-click="JobsCtrl.createCampaign()">
                            <div class="join-team">JOIN OUR TALENT COMMUNITY<img src="../public/images/email-parser/arrows.png" alt="next"></div>
                        </div>
                        <div class="social-share">
                            <b>Share Jobs</b>
                            <!-- social media share directive -->
                            <social-sharing data-opts="socialMedia" data-path="../templates/components" style="margin-top:10px;"></social-sharing>
                        </div>
                        <b>Copy Jobs Link</b>
                        <copy-url url="{{ReferralDetails.bittly_url}}" btn-text="COPY"></copy-url>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

