<div class="drop-box">
	<div class="container">
		<section>
			<h1 class="logo">
				<img src="{{::ReferralDetails.company_logo}}" alt="company-logo" ng-show="{{::ReferralDetails.company_logo != ''}}">
				<span class="company-name" ng-show="{{::ReferralDetails.company_logo == ''}}">{{::ReferralDetails.company_name | uppercase}}</span>	
			</h1>
			<div class="row">
				<form name="apply_form" autocomplete="off" novalidate>
					<h3 class="title">Candidate Details</h3>
					<div class="col-sm-6 form-style">
						<div class="form-group">
						    <label for="fname">Full Name<sup>*</sup></label>
						    <input name="fullname" class="form-control input-lg"  required id="fname" type="text" maxlength="50" ng-model="fullname">
						    <span ng-show="apply_form.fullname.$error.required && ApplyJobCtrl.errorRequired" class="has-error-msg">Please Enter Full Name.</span>
					    </div>
					</div>
					<div class="col-sm-6 form-style">
						<div class="form-group">
						    <label for="email">Email Address<sup>*</sup></label>
						    <input name="emailid" class="form-control input-lg" id="email" type="text" required maxlength="50" ng-pattern="/^[a-z0-9A-Z._%+-]+@[a-zA-Z]+\.[a-z]{2,3}$/i" ng-model="ApplyJobCtrl.referralDetails.emailid" readonly>
						    <span ng-show="apply_form.emailid.$error.required && ApplyJobCtrl.errorRequired" class="has-error-msg">Please Enter Email Id.</span>
						    <span ng-show="apply_form.emailid.$error.pattern && ApplyJobCtrl.errorRequired" class="has-error-msg">Please Enter Valid Email Id.</span>
					    </div>
					</div>
					<div class="col-sm-6 form-style">
						<div class="form-group gap">
						    <label for="can-mobile">Phone Number</label>
						    <input name="phone_no" class="form-control input-lg" id="can-mobile" type="text" type="tel" onkeypress='return event.charCode >= 48 && event.charCode <= 57 || event.charCode == 0' maxlength="50" ng-model="values">
					    </div>
					</div>
					<div class="col-sm-6 form-style">
					    <div class="file">
						    <label for="can-upload">Upload CV<sup>*</sup></label>
						    <span class="file-name" ng-bind="ApplyJobCtrl.fileName" title="{{ApplyJobCtrl.fileName}}"></span>
						    <div id="upload-resume">
						  	</div>
						  	<span class="has-error-msg file-check" ng-show="ApplyJobCtrl.chkFile && ApplyJobCtrl.errorRequired" style="left:0">Please Select File.</span>
					    </div>
					</div>
				</form>
			</div>
			<div class="footer clearfix">
			    <div class="pull-left">
			        <span style="line-height:50px;">
			            <span ng-if="ApplyJobCtrl.loader">
			            	<img src="../public/images/loader/upload_file.gif" alt="loader" style="margin:5px;">Updating
		            	</span>
			            <span class="message" ng-class="{'success' : ApplyJobCtrl.backendMsg}" ng-bind="ApplyJobCtrl.backendMsg || ApplyJobCtrl.backendError"></span>
			        </span>
			    </div>
			    <div class="pull-right disabled">
			        <span class="cancel"><a ui-sref="allJobs({ref: $root.ref})">Cancel</a></span>
					<span class="submit" ng-click="ApplyJobCtrl.postFormData(apply_form.$invalid, 'apply')">SUBMIT</span>
			    </div>
			</div>
		</section>
	</div>
</div>