<div class="drop-box">
	<div class="container">
		<section>
			<h1 class="logo">
				<img ng-src="{{ApplyJobCtrl.referralDetails.company_logo}}" alt="company-logo" ng-if="ApplyJobCtrl.referralDetails.company_logo != ''"  draggable="false">
				<span class="company-name" ng-if="ApplyJobCtrl.referralDetails.company_logo == ''">{{ApplyJobCtrl.referralDetails.company_name | uppercase}}</span>	
			</h1>
			<!-- <div class="title-underline"></div> -->
			<div class="referral-details" ng-if="ApplyJobCtrl.showJobDetails">
                <h3 ng-bind="ApplyJobCtrl.jobDetails.job_title"></h3>
                <h5>
                	<span>Experience: </span>
                	<span class="exp" ng-bind="ApplyJobCtrl.jobDetails.experience"></span>
                </h5>
                <h5>
                	<span>Location:</span> 
                	<span class="loc" ng-bind="ApplyJobCtrl.jobDetails.location"></span>
                </h5>
                <hr>
            </div>
			<div class="row">
				<form name="apply_form" autocomplete="off" novalidate>
					<h3 class="title">Candidate Details</h3>
					<div class="col-sm-6 form-style">
						<div class="form-group">
						    <label for="fname">Full Name<sup>*</sup></label>
						    <input name="fullname" class="form-control input-lg"  required id="fname" type="text" maxlength="50" ng-model="fullname">
						    <span ng-show="apply_form.fullname.$error.required && ApplyJobCtrl.errorRequired" class="has-error-msg">Please enter Full Name.</span>
					    </div>
					</div>
					<div class="col-sm-6 form-style" ng-init="readOnly = $state.params.share_status == 'share' ? 'false' : 'true'">
						<div class="form-group">
						    <label for="email">Email<sup>*</sup></label>

						    <input name="emailid" ng-if="!ApplyJobCtrl.readOnlyEmail" class="form-control input-lg" id="email" type="text" required maxlength="50" ng-pattern='/^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/' ng-model="ApplyJobCtrl.referralDetails.emailid" ng-readonly="{{readOnly}}">

						    <input name="emailid" ng-if="ApplyJobCtrl.readOnlyEmail" class="form-control input-lg" id="email" type="text" required maxlength="50" ng-pattern='/^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/' ng-model="ApplyJobCtrl.referralDetails.emailid" readonly>

						    <input type="hidden" name="emp_email" value="{{ApplyJobCtrl.shareReferral}}" ng-if="ApplyJobCtrl.shareReferral">
						    <span ng-show="apply_form.emailid.$error.required && ApplyJobCtrl.errorRequired" class="has-error-msg">Please enter Email.</span>
						    <span ng-show="apply_form.emailid.$error.pattern && ApplyJobCtrl.errorRequired" class="has-error-msg">Please enter valid Email.</span>
					    </div>
					</div>
					<div class="col-sm-6 form-style">
						<div class="form-group gap">
						    <label for="can-mobile">Phone Number</label>
						    <input name="phone_no" class="form-control input-lg" id="can-mobile" type="text" type="tel" onkeypress='return event.charCode >= 48 && event.charCode <= 57 || event.charCode == 0' maxlength="50" ng-model="values">
					    </div>
					</div>
					<div class="col-sm-6 form-style">
					    <div class="file">
						    <label for="can-upload">Upload CV<sup ng-if="ApplyJobCtrl.hasResumeUpload">*</sup></label>
						    <span class="file-name" ng-bind="ApplyJobCtrl.fileName" title="{{ApplyJobCtrl.fileName}}"></span>
						    <div id="upload-resume">
						  	</div>
						  	<span class="has-error-msg file-check" ng-show="ApplyJobCtrl.hasUploadResume && ApplyJobCtrl.errorRequired" style="left:0">Please select File.</span>
					    </div>
					</div>
				</form>
			</div>
			<div class="footer clearfix">
			    <div class="pull-left">
			        <span style="line-height:50px;">
			            <span ng-if="ApplyJobCtrl.loader">
			            	<img src="../public/images/loader/upload_file.gif" alt="loader" style="margin:5px;">Updating
		            	</span>
			            <span class="message" ng-class="{'success' : ApplyJobCtrl.backendMsg}" ng-bind="ApplyJobCtrl.backendMsg || ApplyJobCtrl.backendError"></span>
			        </span>
			    </div>
			    <div class="pull-right disabled" ng-init="sh_cd = $stateParams.share_status">
			        <span class="cancel" ng-if="$stateParams.jc != 2"><a ui-sref="{{$stateParams.jc == 1 ? 'allCampaigns.all({ref: $root.camp_ref,share_status:sh_cd, jc : $stateParams.jc})' : 'allJobs.all({ref: $root.ref,share_status:sh_cd, jc : $stateParams.jc})'}}">Cancel</a></span>
			        <span class="cancel" ng-if="$stateParams.jc == 2"><a ui-sref="allJobs.all({ref: ApplyJobCtrl.refParam,share_status:sh_cd, jc : 2})">Cancel</a></span>
					<span class="submit" ng-click="ApplyJobCtrl.postFormData(apply_form.$invalid, 'apply')">SUBMIT</span>
			    </div>
			</div>
		</section>
	</div>
</div>