<div class="modal-header">
	<button type="button" class="close" ng-click="modalCtrl.jump();$dismiss();">&times;</button>
	<h4 class="modal-title">Job Has Expired</h4>
</div>
<div class="modal-body">
	<p>Thank you for your interest in this job. At this time, this job requisition has been closed. You may however send in your details and we will match this to other existing open positions here.</p>
	<p>Thanks,<br><span>Talent Acquisition Team.</span></p>
</div>
<div class="modal-footer">
		<button type="button" class="btn btn-default" ng-click="$dismiss();">CONTINUE</button>
</div>
      	