<md-dialog class="create-campaign" flex>
    <div class="main">
        <header>
            <img src="../public/images/cross_icon.png" alt="close" ng-click="createCampCtrl.closeDialog($event)">
            <h3>Join Our Talent Community</h3>
            <p class="desc">Joining our Talent Community will enhance your job search and application process,</p>
            <p>Whether you choose to apply or just leave your information, we look forward to staying connected with you.</p> 
        </header>
        <section>
            <form>
                <div layout="column">
                    <div layout="row">
                        <div flex="45">
                            <md-input-container class="md-block">
                                <label>FIRST NAME</label>
                                <input type="text" name="fname" ng-model="fname">
                            </md-input-container>
                        </div>
                        <i flex="10"></i>
                        <div flex="45">
                            <md-input-container class="md-block">
                                <label>LAST NAME</label>
                                <input type="text" name="lname" ng-model="lname">
                            </md-input-container>
                        </div>
                    </div>
                    <div layout="row">
                        <div flex="45">
                            <md-input-container class="md-block">
                                <label>MOBILE</label>
                                <input type="text" name="mobile" check-char-zero ng-model="mobile">
                            </md-input-container>
                        </div>
                        <i flex="10"></i>
                        <div flex="45">
                            <md-input-container class="md-block">
                                <label>EMAIL</label>
                                <input type="text" name="email" ng-model="email">
                            </md-input-container>
                        </div>
                    </div>
                    <div layout="row">
                        <div flex="45" style="position: relative">
                            <md-input-container class="md-block">
                                <label>LOCATION</label>
                                <input type="text" name="location" ng-model="location" ng-autocomplete="createCampCtrl.geo_location" details="createCampCtrl.geo_details" options="createCampCtrl.geo_options" apiplaceholder="">
                            </md-input-container>
                        </div>
                        <i flex="10"></i>
                        <div flex="45">
                            <md-input-container class="md-block select-box">
                                <label style="display:none">WHICH CAREER  AREA ARE YOU INTERESTED IN?</label>
                                <md-select name="industry" ng-model="career" >
                                    <md-option ng-repeat="career in createCampCtrl.careers" ng-value="career.job_function_id">{{career.job_function_name}}</md-option>
                                </md-select>
                            </md-input-container>
                        </div>
                    </div>
                    <div layout="row">
                        <div flex="45">
                            <md-input-container class="md-block select-box">
                                <label style="display:none">WOULD YOU LIKE TO RECEIVE JOB ALERTS?</label>
                                <md-select name="industry" ng-model="status" >
                                    <md-option ng-repeat="type in ['Yes', 'No']" ng-value="type">{{type}}</md-option>
                                </md-select>
                            </md-input-container>
                        </div>
                    </div>
                </div>
                <div class="community">
                    <p>SELECT AND JOIN OUR TALENT COMMUNITY</p>
                    <span ng-repeat="community in createCampCtrl.communitys"
                          ng-click="createCampCtrl.addOrDeleteCommunity($index)"
                          ng-style="{'background' : community.colorCode}"
                          >
                        <img src="../public/images/select.svg" alt="add" ng-class="{'active' : createCampCtrl.selectedCommunitys.indexOf($index) > - 1}">
                        {{community.name}}
                    </span>
                </div>
            </form>
        </section>
    </div>
    <footer>
        <md-button class="submit" ng-click="createCampCtrl.closeDialog($event)">SUBMIT</md-button>
        <span class="cancel" ng-click="createCampCtrl.closeDialog($event)">Cancel</span>
    </footer>
</md-dialog>
