<!DOCTYPE html>
<html ng-app="emailParser" prefix="og: http://ogp.me/ns#">
	<head>
		<title ng-bind="$state.current.data.pageTitle">Mintmesh</title>
		<base href="<?php echo $data['EMAIL_PARSER_DOMAIN']; ?>" target="_blank, _self, _parent, _top">
		<link rel="shortcut icon" href="../public/images/favicon.png"/>
		<!-- linkendin -->
		<meta property="og:image" content="../public/images/logo.png" />
		<link rel="stylesheet" type="text/css" href="../public/css/font-awesome.min.css?v=<?php echo $data['APP_VERSION']; ?>">
		<link rel="stylesheet" type="text/css" href="../public/css/bootstrap.css?v=<?php echo $data['APP_VERSION']; ?>">
		<link rel="stylesheet" type="text/css" href="../public/css/intlTelInput.css?v=<?php echo $data['APP_VERSION']; ?>">
		<link rel="stylesheet" type="text/css" href="../public/css/fileuploader.css?v=<?php echo $data['APP_VERSION']; ?>">
		<link rel="stylesheet" type="text/css" href="../public/css/email-parser.css?v=<?php echo $data['APP_VERSION']; ?>">
		<link rel="stylesheet" type="text/css" href="../public/css/email-parser-jobs.css?v=<?php echo $data['APP_VERSION']; ?>">

		<script type="text/javascript" src="../public/js/vendor/jquery.js?v=<?php echo $data['APP_VERSION']; ?>"></script>
		<script type="text/javascript" src="../public/js/vendor/bootstrap.min.js?v=<?php echo $data['APP_VERSION']; ?>"></script>
		<script type="text/javascript" src="../public/js/vendor/angular.js?v=<?php echo $data['APP_VERSION']; ?>"></script>
		<script type="text/javascript" src="../public/js/vendor/angular-ui-router.js?v=<?php echo $data['APP_VERSION']; ?>"></script>
        <script type="text/javascript" src="../public/js/vendor/ng-infinite-scroll.js?v=<?php echo $data['APP_VERSION']; ?>"></script>
		<script type="text/javascript" src="../public/js/vendor/intlTelInput.js?v=<?php echo $data['APP_VERSION']; ?>"></script>
		<script type="text/javascript" src="../public/js/vendor/fileuploader.js?v=<?php echo $data['APP_VERSION']; ?>"></script>
		<script type="text/javascript" src="../public/js/vendor/ui-bootstrap-tpls.js?v=<?php echo $data['APP_VERSION']; ?>"></script>

		<!-- Go to www.addthis.com/dashboard to customize your tools -->
		<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-584e9bc0740b5886"></script> 
	</head>
	<body class="email-parser">

		<script type="text/javascript">

			(function () {
                "use strict";
                
                angular.module('app.constants', [])
                .constant('App', {
                	Components : {},
                    Helpers : {},
                    base_url   : '<?php echo $data['APP_DOMAIN']; ?>',
                    API_DOMAIN : '<?php echo $data['API_DOMAIN']; ?>',
                    ref:'<?php echo isset($data["ref"])?$data['ref']:""; ?>',
                    url_spinner : '<?php echo $data['APP_DOMAIN']; ?>public/images/spinner.gif',
                    url_spinner_small: '<?php echo $data['APP_DOMAIN']; ?>public/images/spinner_small.gif'
                })
                .constant('ReferralDetails',<?php echo isset($data["referralDetails"])?$data['referralDetails']:"{}"; ?>)
            }());
            
	    </script>

		<div ui-view></div>

		<!-- <div class="modal fade" id="expired" role="dialog" ng-controller="modalController as ctrl">
		    <div class="modal-dialog">
		      	<div class="modal-content">
		        	<div class="modal-header">
		          		<button type="button" class="close" ng-click="ctrl.jump()" data-dismiss="modal">&times;</button>
		          		<h4 class="modal-title">Job Has Expired</h4>
		        	</div>
		        	<div class="modal-body">
		          		<p>Thank you for your interest in this job. At this time, this job requisition has been closed. You may however send in your details and we will match this to other existing open positions here.</p>
		          		<p>Thanks,<br><span>Talent Acquisition Team.</span></p>
		        	</div>
		        	<div class="modal-footer">
		          		<button type="button" class="btn btn-default" data-dismiss="modal">CONTINUE</button>
		        	</div>
		      	</div>
		  	</div>
		</div> -->

		<script type="text/javascript" src="../public/js/helpers/components.js?v=<?php echo $data['APP_VERSION']; ?>"></script>
		<script type="text/javascript" src="../public/js/helpers/helpers.js?v=<?php echo $data['APP_VERSION']; ?>"></script>
		<script type="text/javascript" src="../public/js/helpers/facebook-service.js?v=<?php echo $data['APP_VERSION']; ?>"></script>
		<script type="text/javascript" src="../public/js/controllers/email-parser/email-parser.js?v=<?php echo $data['APP_VERSION']; ?>"></script>
		<script type="text/javascript" src="../public/js/controllers/email-parser/app.js?v=<?php echo $data['APP_VERSION']; ?>"></script>
	</body>
</html>