<div class="all-jobs">
	<div class="container">
		<header>
			<img ng-src="{{JobDetailsCtrl.job_details.company_logo}}" src="{{$root.url_spinner}}" class="loading" alt="company-logo">
			<span ng-bind="JobDetailsCtrl.job_details.companyName" class="company-name" ng-if="JobDetailsCtrl.job_details.company_logo == ''"></span>
		</header>
		<section class="job-details">
			<div  class="loader" ng-if="JobDetailsCtrl.job_details.loader">
				<img src="../public/images/loader/spin.gif" alt="spinner" width="50px" height="50px"> 
			</div>
			<div ng-repeat="list in JobDetailsCtrl.job_details.list">
				<div class="row">
					<div class="col-sm-8 header">
						<p ng-bind="JobDetailsCtrl.job_details.companyName"></p>
						<h3 class="job-title" ng-bind="list.job_name"></h3>
					</div>
					<div>
						<div class="col-sm-2 rewards pull-right" ng-repeat="rewards in list.rewards">
							<div ng-if="rewards.rewards_type != 'free'">
								<h3>{{rewards.currency_type == 0 ? '&#x24;' : '&#8377' + ' ' + rewards.rewards_value}}</h3>
							</div>
							<div ng-if="rewards.rewards_type == 'free'">
								<h3 style="font-size:20px;">FREE</h3>
							</div>
							<p ng-bind="rewards.rewards_name + ' Rewards'"></p>
						</div>
					</div>
					<!-- <div class="col-sm-2 rewards">
						<h3> &#8377;1000</h3>
						<p>Referral Rewards</p>
					</div> -->
				</div>
				<div class="job-params">
					<div class="row">
						<div class="col-sm-2 labels">Job Function :</div>
						<div class="col-sm-10 value" ng-bind="list.job_function"></div>
					</div>
					<div class="row">
						<div class="col-sm-2 labels">Experience :</div>
						<div class="col-sm-10 value" ng-bind="list.experience"></div>
					</div>
					<div class="row">
						<div class="col-sm-2 labels">Possessions :</div>
						<div class="col-sm-10 value" ng-bind="list.vacancies"></div>
					</div>
					<div class="row">
						<div class="col-sm-2 labels">Location :</div>
						<div class="col-sm-10 value" ng-bind="list.location"></div>
					</div>
				</div>
				<div class="job-desc">
					<p>Job Description :</p>
					<pre ng-bind="list.job_description"></pre>
				</div>
				<div class="action">
					<a ui-sref="candidateDetails({ref: list.ref_code,flag: 0})">APPLY</a>
					<a class="refer" ui-sref="referralDetails({ref: list.ref_code,flag: 0})">REFER</a>
					<a class="all-jobs" ui-sref="allJobs({ref: list.ref_code})">VIEW ALL JOBS</a>
				</div>
			</div>
		</section>
		<footer>
			<div class="social-media">
				Share Jobs
				<!-- <div class="icon">
					<span><i class="fa fa-facebook " aria-hidden="true"></i></span>
					<span><i class="fa fa-linkedin" aria-hidden="true"></i></span>
					<span><i class="fa fa-twitter" aria-hidden="true"></i></span>
					<span><i class="fa fa-google-plus" aria-hidden="true"></i></span>
					<span><i class="fa fa-whatsapp" aria-hidden="true"></i></span>
				</div> -->
				<div class="social-icons">
					<!-- Go to www.addthis.com/dashboard to customize your tools -->
					<div class="addthis_inline_share_toolbox"></div>
				</div>
				<!-- social media share directive -->
				<!-- <social-sharing data-opts="JobDetailsCtrl.socialMedia"></social-sharing> -->
				<div class="link">
					<div class="form-group">
						<div class="field">
							<input type="text" class="form-control" id="website" value="{{JobDetailsCtrl.copyUrl}}">		
						</div>
						<div class="btns" data-copytarget="#website">
							COPY JOBS LINK
						</div>
					</div>
				</div>
			</div>
			<div class="drop-cv">
				Refer friend for future openings here ? &nbsp;<span><a ui-sref="referralDetails({ref: $root.ref,flag: 1})">Upload CV</a></span>
			</div>
		</footer>
	</div>
</div>

<script>
(function() {

	'use strict';
  
  // click events
  document.getElementsByClassName('btns')[0].addEventListener('click', copy, true);

	// event handler
	function copy(e) {

    // find target element
    var 
      t = e.target,
      c = t.dataset.copytarget,
      inp = (c ? document.querySelector(c) : null);
      
    // is element selectable?
    if (inp && inp.select) {
      
      // select text
      inp.select();

      try {
        // copy text
        document.execCommand('copy');
        inp.blur();
        
        // copied animation
        t.classList.add('copied');
        setTimeout(function() { t.classList.remove('copied'); }, 1500);
      }
      catch (err) {
        alert('please press Ctrl/Cmd+C to copy');
      }
      
    }
    
	}

})();
</script>