<div class="all-jobs">
	<div class="container">
		<header>
			<img ng-src="{{JobDetailsCtrl.job_details.company_logo}}" src="{{$root.url_spinner}}" class="loading" alt="company-logo">
			<span ng-bind="JobDetailsCtrl.job_details.companyName" class="company-name" ng-if="JobDetailsCtrl.job_details.company_logo == ''"></span>
		</header>
		<section class="job-details">
			<div  class="loader" ng-if="JobDetailsCtrl.job_details.loader">
				<img src="../public/images/loader/spin.gif" alt="spinner" width="50px" height="50px"> 
			</div>
			<div ng-repeat="list in JobDetailsCtrl.job_details.list">
				<div class="row">
					<div class="col-sm-8 header">
						<p ng-bind="JobDetailsCtrl.job_details.companyName"></p>
						<h3 class="job-title" ng-bind="list.job_name"></h3>
					</div>
					<div>
						<div class="col-sm-2 rewards pull-right" ng-repeat="rewards in list.rewards">
							<div ng-if="rewards.rewards_type != 'free'">
								<h3>{{(rewards.rewards_type == 'paid' ? rewards.currency_type == 1 ? '&#x24;' : '&#8377;' : '&#8471;') + ' ' + rewards.rewards_value}}</h3>
								<p ng-bind="rewards.rewards_name + ' Rewards'"></p>
							</div>
						</div>
					</div>
				</div>
				<div class="job-params">
					<div class="row">
						<div class="col-sm-2 labels">Job Function:</div>
						<div class="col-sm-10 value" ng-bind="list.job_function"></div>
					</div>
					<div class="row">
						<div class="col-sm-2 labels">Experience:</div>
						<div class="col-sm-10 value" ng-bind="list.experience"></div>
					</div>
					<div class="row">
						<div class="col-sm-2 labels">Possessions:</div>
						<div class="col-sm-10 value" ng-bind="list.vacancies"></div>
					</div>
					<div class="row">
						<div class="col-sm-2 labels">Location:</div>
						<div class="col-sm-10 value" ng-bind="list.location"></div>
					</div>
				</div>
				<div class="job-desc">
					<p>Job Description:</p>
					<pre ng-bind="list.job_description"></pre>
				</div>
				<div class="action">
					<a ui-sref="candidateDetails({ref: list.ref_code,flag: 0, status:list.status, jc: list.post_type == 'campaign' ? 1 : 0})" ng-if="list.post_type == 'internal' || list.post_type == 'campaign'">APPLY</a>
					<a class="" ui-sref="referralDetails({ref: list.ref_code,flag: 0, status:list.status, jc: list.post_type == 'campaign' ? 1 : 0})" ng-if="list.post_type == 'external' || list.post_type == 'campaign'">REFER</a>
					<a class="all-jobs" ui-sref="{{list.post_type == 'campaign' ? 'allCampaigns({ref: $root.camp_ref})' : 'allJobs({ref: $root.ref})'}}">VIEW ALL JOBS</a>
				</div>
			</div>
		</section>
		<footer>
			<div class="social-media">
				<div ng-if="JobDetailsCtrl.job_details.list[0].post_type == 'external'">
					Share Job
					<!-- social media share directive -->
					<social-sharing data-opts="JobDetailsCtrl.socialMedia" style="margin-top:10px;" data-path="../templates/components"></social-sharing>
				</div>
				<copy-url url="{{JobDetailsCtrl.copyUrl}}" btn-text="COPY JOB LINK"></copy-url>
			</div>
			<div class="drop-cv" ng-if="JobDetailsCtrl.job_details.list[0].post_type == 'external'">
				Refer friend for future openings here <span><a ui-sref="referralDetails({ref: $root.ref,flag: 1})">Upload CV</a></span>
			</div>
		</footer>
	</div>
</div>