<div class="bg-image">
	<div class="preloader" ng-if="emailCtrl.loadCond"></div>
	<div class="verify-page">
		<header class="text-center">
			<a href=""><img src="public/images/company_logo.svg" class="logo" alt="brand-logo"></a>
		</header>

		<div class="email-verify text-center">
			<div class="box col-md-4 col-xs-7 col-sm-5" ng-if="emailCtrl.verified">
				<img src="public/images/tickmark.svg" alt="tick-mark">
				<h3>VERIFIED!</h3>
				<p>Thank you for verifying your Email.</p>
				<button class="btn btn-style" ng-click="emailCtrl.continue()">CONTINUE<img src="public/images/arrow-buttons.svg"></button>
			</div>
			<div class="box col-md-4 col-xs-7 col-sm-5" ng-if="emailCtrl.already_verified">
				<img src="public/images/tickmark.svg" alt="tick-mark">
				<h3>Your Account Has Already Been Verified</h3>
				<p>Please Login to Continue</p>
				<button class="btn btn-style" ng-click="emailCtrl.login()">LOGIN<img src="public/images/arrow-buttons.svg"></button>
			</div>
		</div>
	</div>
	<footer>
		<div class="container">
			<div class="row">
				<div class="col-sm-5">
					<p>&copy; 2017 MINTMESH&trade; INC. ALL RIGHTS RESERVED.</p>
				</div>
				<div class="col-sm-7">
					<ul>
						<li><a href="https://mintmesh.com/us/" target="_blank">ABOUT US</a></li>
						<li><a href="https://mintmesh.com/terms-of-use/" target="_blank">TERMS & CONDITIONS</a></li>
						<li><a href="https://mintmesh.com/privacy-policy/" target="_blank">PRIVACY POLICY</a></li>
					</ul>
				</div>
			</div>
		</div>
	</footer>
</div>