<div class="analytics">
	<div class="container">
		<div layout="column" class="box mm-slide-left">
			<div layout="row">
				<i flex></i>
				<div flex="60">
					<div layout="column">
						<div layout="row" class="info text-center">
							<i flex></i>
							<div flex="70">
								The right place to find Your Business
							</div>
							<i flex></i>
						</div>
						<div layout="row" class="form-group search">
							<i flex></i>
							<angucomplete-alt id="search"
				              flex="60"
				              pause="300"
				              ng-model="sss"
				              selected-object="AnalyticsCtrl.selectedResult"
				              local-data="AnalyticsCtrl.dropDownList"
				              local-search="AnalyticsCtrl.localSearch"
				              title-field="name"
				              text-no-results="No results found"
				              minlength="1"
				              input-class="form-control input-lg"
				              match-class="highlight" />
				            </angucomplete-alt>
						    <md-button class="md-raised" ng-click="AnalyticsCtrl.search()">SEARCH</md-button>
						    <i flex></i>
						</div>
						<div class="data">
							<div class="result head">Recent Search</div>
							<div class="result empty"></div>
							<div class="result" ng-repeat="result in AnalyticsCtrl.recentSearchResults">
								<p ng-bind="result.title"></p>
								<span ng-bind="result.desc" class="ellipsis"></span>
							</div>
						</div>
					</div>
				</div>
				<i flex></i>
			</div>
		</div>
	</div>
</div>
