<div class="analytics">
	<div class="container">
		<div layout="column" class="box">
			<div layout="row">
				<i flex></i>
				<div flex="70" class="text-center">
					<div layout="column">
						<div layout="row" class="info">
							<i flex></i>
							<div flex="60">
								The right place to find Your Business
							</div>
							<i flex></i>
						</div>
						<div layout="row" class="form-group search">
							<i flex></i>
						    <input type="text" class="form-control input-lg" placeholder="I am " flex="60">
						    <md-button flex="20" class="md-raised">SEARCH</md-button>
						    <i flex></i>
						</div>
					</div>
				</div>
				<i flex></i>
			</div>
		</div>
	</div>
</div>