<link rel="stylesheet" type="text/css" href="public/css/dashboard.css">
<link rel="stylesheet" type="text/css" href="public/css/job_style.css">
<link rel="stylesheet" type="text/css" href="public/css/contacts.css">
<link rel="stylesheet" type="text/css" href="public/css/settings.css">
<link rel="stylesheet" type="text/css" href="public/css/jquery.circliful.css">
<script type="text/javascript" src="public/js/vendor/jquery.circliful.min.js"></script>

<div class="dashboard">

	<header ng-include="'templates/header.phtml'" ng-controller="HeaderController as headCtrl"></header>

	<div ui-view></div>

	<footer ng-include="'templates/footer.phtml'" ng-controller="FooterController as footCtrl"></footer>

</div>
