<style type="text/css">
	.candidates{
		background: #eeeff1;
	}
	.candidates img{
		width: 100%;
	    margin-top: -2px;
	}
	.candidates .container{
		padding: 0;
	}
</style>
<div class="candidates">
	<div class="container">
		<img src="public/images/Resume-Room-copy.jpg" alt="candidates" onclick="this.src = 'public/images/Resume-Room-Detail-View.jpg'">
	</div>

	<!-- <section>
		<div>
					
		</div>		
	</section> -->


</div>