<link rel="stylesheet" type="text/css" href="public/css/candidates.css">
<div class="candidates">
	<div class="container">
		<img src="public/images/Resume-Room-copy.jpg" alt="candidates" onclick="this.src = 'public/images/Resume-Room-Detail-View.jpg'">
	</div>
	<!-- <div class="sub-header">
		<div class="container">
			<ul>
				<li><a ui-sref="^.candidates.resumeRoom" ui-sref-active="active" style="margin-left:0;">RESUME ROOM</a></li>
			</ul>
		</div>
	</div>

	<div ui-view></div> -->

</div>