<md-progress-linear md-mode="determinate" id="borderLoader" value="{{DashCtrl.borderInc}}"></md-progress-linear>
<div class="dashboard-container">
	<section ng-if="DashCtrl.dashboardLoader">
		<div class="container">
			<div class="main-title">
				<h2>Welcome Back! <span ng-bind="DashCtrl.username" style="text-transform: capitalize"></span></h2>
			</div>

			<div class="panel-group">
				<!-- <div class="text-center" style="padding: 20px 0 0 0;cursor: pointer;">
					<span style="padding-bottom: 10px;border-bottom: 1px solid #ccc">Month to Date&nbsp;<strong>&nbsp;<img src="public/images/arrow-dropdown-black.svg"></strong></span>
				</div> -->

				<div>
					ALL OPEN JOBS: 
					<span style="color:#2c9172" ng-bind="DashCtrl.jobsCount"></span>
				</div>
				<div class="row" ng-init = "setColors = [ '#F98017', '#14A5F8', '#48BBC0', '#539F32']">
					<div class="panel panel-default" ng-repeat="jobStatusCount  in DashCtrl.jobsStatusCount">
						<span ng-style="{'color':setColors[$index]}" ng-bind="jobStatusCount"></span>
						<strong ng-bind="DashCtrl.statusNames[$index]"></strong>
					</div>
					<!-- <div class="arrow">
						<img src="public/images/arrow-buttons-grey.svg">
					</div> -->
					<!-- <div class="panel panel-default">
						<span  style="color: #14A5F8">1,874</span>
						<strong>Accepted</strong>
					</div> -->
					<!-- <div class="arrow">
						<img src="public/images/arrow-buttons-grey.svg">
					</div> -->
					<!-- <div class="panel panel-default">
						<span style="color: #48BBC0">876</span>
						<strong>Interviewed</strong>
					</div> -->
					<!-- <div class="arrow">
						<img src="public/images/arrow-buttons-grey.svg">
					</div> -->
					<!-- <div class="panel panel-default">
						<span  style="color: #539F32">256</span>
						<strong>Hired</strong>
					</div -->
				</div>
				<div style="padding-top: 53px">
					<div class="dropdown-days" ng-init="days='7'">
					SHOW REPORTS:
						<select ng-change="DashCtrl.lastProgressBar(days)" ng-model="days" >
							<option value="7">7 Days</option>
							<option value="30">30 Days</option>
							<option value="360">1 Year</option>
						</select>
						<i class="fa fa-angle-down fa-feedback"></i>
					</div>
				</div>
			</div>
		</div>

		<div class="circle-stats">
			<!-- <div class="text-center" style="padding: 20px 0 0 0;cursor: pointer;">
				<span style="padding-bottom: 12px;border-bottom: 1px solid #ccc">Last&nbsp;<strong>7 Days <img src="public/images/arrow-dropdown-black.svg"></strong></span>
			</div> -->
			<div class="container" style="position:relative">
				<div class="row">
					<div class="col-lg-4 col-md-4 col-sm-4">
						<div class="text-center head" style="font-weight: 500">
							CONTACTS ENGAGEMENT
						</div>
						<div class="circlestat">
							<!-- <span class="circle-info-half">User Satisfaction</span> -->
						</div>
						<!-- <div class="text-center foot" style="color: #222">
							<span class="arrow-up"></span>
								&nbsp;Engagement Increased to 
							<span class="text-increase">10%</span>
						</div> -->
					</div>
					<div class="col-lg-4 col-md-4 col-sm-4">
						<div class="text-center head" style="font-weight: 500">
							JOBS REACH
						</div>
						<div class="circlestat1"><!-- <span class="circle-info-half">User Satisfaction</span> --></div>
						<!-- <div class="text-center foot" style="color: #222">
							<span class="arrow-down"></span>
								&nbsp;Reach Decreased to 
							<span class="text-decrease">3%</span>
						</div> -->
					</div>
					<div class="col-lg-4 col-md-4 col-sm-4">
						<div class="text-center head">
							REWARDS CLAIMED
						</div>
						<div class="circlestat2"><!-- <span class="circle-info-half">User Satisfaction</span> --></div>
						<!-- <div class="text-center foot" style="color: #222">
							<span class="arrow-up"></span>
								&nbsp;Claim Increased to 
							<span class="text-increase">6%</span>
						</div> -->
					</div>
				</div>

				<div class="load-status-report" ng-if='DashCtrl.loaderProgress'>
					<span></span>
					<img src="public/images/loader/spin.gif" alt="loader">
				</div>
			</div>
		</div>

		<div class="referrals-hires">
			<div class="container">
				<div class="row">
					<div class="col-lg-6" style="margin-bottom: 30px;">
						<div class="dropdown-days">
							REFERRALS IN THE LAST:
								<select ng-change="DashCtrl.lastReferrals(refDays)" ng-model="refDays" ng-init="refDays='7'">
									<option value="7">7 Days</option>
									<option value="30">30 Days</option>
									<option value="360">1 Year</option>
								</select>
								<i class="fa fa-angle-down fa-feedback"></i>
							<!-- <span class="pull-right">Referrals Increased &nbsp;<span class="arrow-up"></span></span> -->
						</div>
						<div class="ref-hire-list">
							<ul class="referrals">
								<li class="clearfix" ng-repeat="refList in DashCtrl.referralsList track by $index">
									<div class="pull-left" style="position: relative;padding-right: 10px" ng-init="getColor=DashCtrl.getColor(refList.status)">
										<img ng-src="{{refList.referral_img}}" class="pull-left img-responsive img-circle dp" ng-style="{'border': '3px solid {{getColor}}'}">
										<img ng-src="{{refList.referred_by_img}}" class="img-responsive img-circle sub-img">
									</div>
									<div class="content">
										<span>
											<strong ng-bind="refList.referral"></strong>
											 	was referred for 
											<strong ng-bind="refList.job_title"></strong>
										</span>
										<br>
										<span>by {{refList.referred_by}}</span>
										<span>
											<span class="vr"></span>
											<span ng-bind="refList.created_at"></span> 
											<span class="pull-right" style="text-transform: capitalize;" ng-style="{'color':getColor}" ng-bind="refList.status | lowercase"></span>
										</span>
									</div>
								</li>
							</ul>
							<div class="no-data" ng-if="DashCtrl.noDataRef">
								NO REFERRALS FOUND
							</div>
							<div class="load-status-report" ng-if="DashCtrl.loaderRerrals">
								<span></span>
								<img src="public/images/loader/spin.gif" alt="loader">
							</div>
						</div>
					</div>
					<div class="col-lg-6" style="margin-bottom: 30px">
						<div class="dropdown-days">
							HIRES IN THE LAST:
							<select ng-change="DashCtrl.lastHires(hireDays)" ng-model="hireDays" ng-init="hireDays='30'">
								<option value="7">7 Days</option>
								<option value="30">30 Days</option>
								<option value="360">1 Year</option>
							</select>
							<i class="fa fa-angle-down fa-feedback"></i>
							<!-- <span class="pull-right">Hires Decreased &nbsp;<span class="arrow-down"></span></span> -->
						</div>
						<div class="ref-hire-list">
							<ul class="hires">
								<li class="clearfix" ng-repeat="hireList in DashCtrl.hiresList">
									<div class="pull-right" style="padding: 5px 0;line-height: 1.8em">
										<strong ng-bind="hireList.job_title"></strong>
										<br ng-init="cost=hireList.service_cost">
										<span class="paid" ng-bind=" cost==0 ? 'Free' : 'Paid $'+cost" ng-style="{'background':cost==0 ? '#666666':''}"></span>
									</div>
									<div class="pull-left" style="position: relative;">
										<img ng-src="{{hireList.referral_img}}" class="pull-left img-responsive img-circle dp" style="border: 3px solid #468A25">
										<img ng-src="{{hireList.referred_by_img}}" class="img-responsive img-circle sub-img">
										<div class="content">
											<span>
												<strong ng-bind="hireList.referral"></strong>
													was referred by
											</span>
											<br>
											<span>
												<i style="color:#000">{{hireList.referred_by}}</i>
											</span>
											<span class="vr"></span>
											<span ng-bind="hireList.created_at"></span> 
										</div>
									</div>
								</li>
							</ul>
							<div class="no-data" ng-if="DashCtrl.noDataHire">
								NO HIRES FOUND
							</div>
							<div class="load-status-report" ng-if="DashCtrl.loaderHires">
								<span></span>
								<img src="public/images/loader/spin.gif" alt="loader">
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="top-contacts" style="border:0">
			<div class="container">

				 <div class="first">

					<!-- <div>TOP REFERRERS FROM YOUR <strong>CONTACTS</strong></div> -->

					<!-- <div class="row">
						<div class="col-lg-4 col-md-6 col-sm-6" ng-repeat="conn in DashCtrl.dashboard_JSON[0].Connections">
							<div class="box clearfix">
								<div class="clearfix">
									<div class="pull-left">
										<img ng-src="public/images/Ui_Faces/{{conn.name}}.jpg" class="img-responsive img-circle dp">
									</div>
									<div class="pull-left" style="line-height: 1.5em;padding: 8px 0 0 8px;">
										<strong class="name">{{conn.name}}</strong>
										<p>{{conn.designation}}</p>
									</div>
								</div>
								<hr>
								<div class="row" style="font-size: 14px;">
									<div class="col-lg-6">
										<span>REFERRALS MADE</span><br>
										<big class="count">{{conn.referral_made}}</big>
									</div>
								</div>
							</div>
						</div>
					</div> -->
				</div>

				<!-- <div class="second">

					<div style="padding: 15px 0">Top Contacts by <strong>Department &nbsp;<img src="public/images/arrow-dropdown-black.svg"></strong> &nbsp;and <strong>Location &nbsp;<img src="public/images/arrow-dropdown-black.svg"></strong></div>

					<div class="row">
						<div class="col-lg-4 col-md-6 col-sm-6">
							<div class="box clearfix">
								<div class="clearfix">
									<div class="pull-left">
										<img src="public/images/dp.jpg" class="img-responsive img-circle dp">
									</div>
									<div class="pull-left" style="line-height: 1.5em;padding: 8px 0 0 8px;">
										<strong class="name">Johnson</strong>
										<p>UI/UX Designer</p>
									</div>
								</div>
								<hr>
								<div class="row" style="font-size: 14px;">
									<div class="col-lg-6">
										<span>REFERRALS MADE</span><br>
										<big class="count">40</big>
									</div>
									<div class="col-lg-6">
										<span>TOTAL CONTACTS</span><br>
										<big class="count">460</big>
									</div>
								</div>
							</div>
						</div>
						<div class="col-lg-4 col-md-6 col-sm-6">
							<div class="box clearfix">
								<div class="clearfix">
									<div class="pull-left">
										<img src="public/images/dp.jpg" class="img-responsive img-circle dp">
									</div>
									<div class="pull-left" style="line-height: 1.5em;padding: 8px 0 0 8px;">
										<strong class="name">John Butler</strong>
										<p>UI/UX Designer</p>
									</div>
								</div>
								<hr>
								<div class="row" style="font-size: 14px;">
									<div class="col-lg-6">
										<span>REFERRALS MADE</span><br>
										<big class="count">36</big>
									</div>
									<div class="col-lg-6">
										<span>TOTAL CONTACTS</span><br>
										<big class="count">456</big>
									</div>
								</div>
							</div>
						</div>
						<div class="col-lg-4 col-md-6 col-sm-6">
							<div class="box clearfix">
								<div class="clearfix">
									<div class="pull-left">
										<img src="public/images/dp.jpg" class="img-responsive img-circle dp">
									</div>
									<div class="pull-left" style="line-height: 1.5em;padding: 8px 0 0 8px;">
										<strong class="name">Willmark</strong>
										<p>iOS Developer</p>
									</div>
								</div>
								<hr>
								<div class="row" style="font-size: 14px;">
									<div class="col-lg-6">
										<span>REFERRALS MADE</span><br>
										<big class="count">36</big>
									</div>
									<div class="col-lg-6">
										<span>TOTAL CONTACTS</span><br>
										<big class="count">435</big>
									</div>
								</div>
							</div>
						</div>
						<div class="col-lg-4 col-md-6 col-sm-6">
							<div class="box clearfix">
								<div class="clearfix">
									<div class="pull-left">
										<img src="public/images/dp.jpg" class="img-responsive img-circle dp">
									</div>
									<div class="pull-left" style="line-height: 1.5em;padding: 8px 0 0 8px;">
										<strong class="name">Christopher</strong>
										<p>UI Manager</p>
									</div>
								</div>
								<hr>
								<div class="row" style="font-size: 14px;">
									<div class="col-lg-6">
										<span>REFERRALS MADE</span><br>
										<big class="count">62</big>
									</div>
									<div class="col-lg-6">
										<span>TOTAL CONTACTS</span><br>
										<big class="count">492</big>
									</div>
								</div>
							</div>
						</div>
						<div class="col-lg-4 col-md-6 col-sm-6">
							<div class="box clearfix">
								<div class="clearfix">
									<div class="pull-left">
										<img src="public/images/dp.jpg" class="img-responsive img-circle dp">
									</div>
									<div class="pull-left" style="line-height: 1.5em;padding: 8px 0 0 8px;">
										<strong class="name">Steve Chris</strong>
										<p>Resource Manager</p>
									</div>
								</div>
								<hr>
								<div class="row" style="font-size: 14px;">
									<div class="col-lg-6">
										<span>REFERRALS MADE</span><br>
										<big class="count">56</big>
									</div>
									<div class="col-lg-6">
										<span>TOTAL CONTACTS</span><br>
										<big class="count">480</big>
									</div>
								</div>
							</div>
						</div>
						<div class="col-lg-4 col-md-6 col-sm-6">
							<div class="box clearfix">
								<div class="clearfix">
									<div class="pull-left">
										<img src="public/images/dp.jpg" class="img-responsive img-circle dp">
									</div>
									<div class="pull-left" style="line-height: 1.5em;padding: 8px 0 0 8px;">
										<strong class="name">Daniel</strong>
										<p>Sr. Software Engineer</p>
									</div>
								</div>
								<hr>
								<div class="row" style="font-size: 14px;">
									<div class="col-lg-6">
										<span>REFERRALS MADE</span><br>
										<big class="count">50</big>
									</div>
									<div class="col-lg-6">
										<span>TOTAL CONTACTS</span><br>
										<big class="count">479</big>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>  -->
			</div>
		</div>
	</section>
</div>