<div class="edit-company">
	<!-- <div id="file-uploader"></div> -->

	<div class="container">
		<div class="head">
			<h2 class="pull-left">Company Profile</h2>
			<div ng-if="!editCompCtrl.update">
				<span class="pull-right btn-edit" style="padding:10px 20px;" ng-click="editCompCtrl.edit('write')">EDIT PROFILE</span>
			</div>
			<div ng-if="editCompCtrl.update" class="btn-disabled">
				<span class="pull-right btn-update" style="position:relative;" ng-click="editCompCtrl.update_company(edit_company_form.$valid)">UPDATE<img src="public/images/loader/dot.svg" alt="dot" ng-if="editCompCtrl.updateLoader"/></span>
				<span class="pull-right btn-cancel" style="margin-right:20px;" ng-click="editCompCtrl.edit('cancel')">CANCEL</span>
			</div>
		</div>
		<div class="error-spacer"></div>
		<div class="msg" ng-if="editCompCtrl.errorMsgCond">
			<span>Successfully Updated</span>
		</div>
		<div class="edit-box clearfix">
			<form name="edit_company_form" novalidate>
				<div class="row">
	 				<div class="col-sm-6">
	 					<div style="width:85%">
	 						<md-input-container class="md-block">
								<label>COMPANY NAME</label>
								<input type="text" name="company" ng-model="editCompCtrl.company_details.name" required ng-class="{'has-error-border':edit_company_form.company.$invalid && editCompCtrl.errCond}">
								<div ng-if="edit_company_form.company.$error.required && editCompCtrl.errCond" class="has-error-msg">Please Enter Company Name</div>
							</md-input-container>
							<md-input-container class="md-block">
					            <label>INDUSTRY</label>
					            <md-select ng-model="editCompCtrl.company_details.industry" required ng-class="{'has-error-border':edit_company_form.industry.$invalid && editCompCtrl.errCond}">
					              	<md-option ng-repeat="industry in editCompCtrl.industry_list" ng-value="industry.industry_id">
					                	{{industry.industry_name}}
					              	</md-option>
					            </md-select>
					            <div class="md-errors-spacer"></div>
					            <div ng-if="edit_company_form.industry.$error.required && editCompCtrl.errCond" class="has-error-msg">Please Select Industry</div>
					        </md-input-container>
				            <input type="hidden" name="industry" ng-value="editCompCtrl.company_details.industry">
					        <md-input-container class="md-block">
					            <label>NUMBER OF EMPLOYEES</label>
					            <md-select ng-model="editCompCtrl.company_details.number_of_employees" required ng-class="{'has-error-border':edit_company_form.employees.$invalid && editCompCtrl.errCond}">
					              	<md-option ng-repeat="count in editCompCtrl.no_of_emp" ng-value="count">
					                	{{count}}
					              	</md-option>
					            </md-select>
					            <div class="md-errors-spacer"></div>
					            <div ng-if="edit_company_form.employees.$error.required && editCompCtrl.errCond" class="has-error-msg">Please Select Number of Employees</div>
					        </md-input-container>
				            <input type="hidden" name="number_of_employees" ng-value="editCompCtrl.company_details.number_of_employees">
	 					</div>
	 				</div>
	 				<div class="col-sm-6">
	 					<div style="width:85%">
		 					<md-input-container class="md-block">
								<label>WEBSITE<span style="color: #999">(URL)</span></label>
								<input  type="text" name="website" ng-model="editCompCtrl.company_details.website" required ng-pattern="/^(http:\/\/www\.|https:\/\/www\.|www\.|https:\/\/|http:\/\/)[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/i" ng-class="{'has-error-border':edit_company_form.website.$invalid && editCompCtrl.errCond}">
								<div ng-if="edit_company_form.website.$error.required && editCompCtrl.errCond"  class="has-error-msg">Please Enter URL</div>
								<div ng-if="edit_company_form.website.$error.pattern && editCompCtrl.errCond"  class="has-error-msg">Please Enter Valid URL</div>
							</md-input-container>
							<md-input-container class="md-block">
      							<label>DESCRIPTION</label>
          						<textarea name="description" ng-model="editCompCtrl.company_details.description" md-maxlength="500" maxlength="500" ng-maxlength="500" rows="1" style="max-height:106px !important"></textarea>
    						</md-input-container>
						</div>
	 				</div>
				</div>
				<div class="row">
					<div class="col-sm-6">
						<div style="width:85%;">
							<div class="company-logo">
					        	<span>LOGO <small style="color: #999">(Add your company logo)</small></span>
					        	<div id="company-logo" style="position:relative"></div>
					        	<ul style="color: #999;font-size:13px;padding-left:19px;">
					        		<li>Supported file format: ".JPEG", ".JPG", ".PNG"</li>
					        		<li>Max file size (1.0MB)</li>
					        	</ul>
					        </div>
					        <div class="referral-bonus">
					        	<span>REFERRAL BONUS POLICY</span>
					        	<div id="referral-bonus"></div>
					        	<ul style="color: #999;font-size:13px;padding-left:19px;">
					        		<li>Supported file format: ".JPEG", ".JPG", ".PNG", ".DOC", ".PDF", ".XLSX"</li>
					        		<li>Max file size (10.0MB)</li>
					        	</ul>
					        </div>
						</div>
					</div>
					<div class="col-sm-6">
						<div style="width:85%;">
							<div>
								<span>PHOTOS <small style="color: #999">(Add your company pictures)</small></span>
								<div class="image-group">
									<div class="multiple-images"></div>
									<div class="multiple-images"></div>
									<br>
									<div class="multiple-images" style="padding-top:8px;"></div>
									<div class="multiple-images" style="padding-top:8px;"></div>
								</div>
								<ul style="color: #999;font-size:13px;padding-left:19px;margin-top:25px;">
					        		<li>Supported file format: ".JPEG", ".JPG", ".PNG"</li>
					        		<li>Max file size (1.0MB)</li>
					        	</ul>
							</div>
						</div>
					</div>
				</div>
			</form>
		</div>
	</div>

</div>