
<div class="sub-header">
	<div class="container">
		<div class="row">
			<div class="col-sm-5 sub_left">
				<div class="mid-nav">
					<h3>
						<a ui-sref="^.job" style="min-width:100px;"><img src="public/images/back-arrow.svg" alt="back" style="margin-bottom: 4px;">
						<span style="min-width:100px;">{{EngContCtrl.job_title | uppercase}}</span></a>
					</h3>
					<span class="openbox" style="margin:0">OPEN</span>
				</div>
				<ul>
					<li><a ui-sref="^.jobDetails({post_id:EngContCtrl.post_id})" ui-sref-active="active">JOB DETAILS</a></li>
					<li><a ui-sref="^.engagement/contacts({post_id:EngContCtrl.post_id})" ui-sref-active="active">ENGAGEMENT/CONTACTS</a></li>
					<li><a ui-sref="^.rewards({post_id:EngContCtrl.post_id})" ui-sref-active="active">REWARDS</a></li>
				</ul>
			</div>
			<div class="col-sm-7 text-center sub-right">
				<ul>
					<li>
						<h3>{{EngContCtrl.subHeaderCount.invited_count}}</h3>
						<span><img src="public/images/invited-header.svg" alt="invited">INVITED</span>
					</li>
					<li>
						<h3>{{EngContCtrl.subHeaderCount.referral_count}}</h3>
						<span><img src="public/images/referrals-header.svg" alt="referral">REFERRALS</span>
					</li>
					<li>
						<h3>{{EngContCtrl.subHeaderCount.pending_count}}</h3>
						<span><img src="public/images/referrals-header.svg" alt="pending">PENDING</span>
					</li>
					<li>
						<h3>{{EngContCtrl.subHeaderCount.accepted_count}}</h3>
						<span><img src="public/images/Applied.svg" alt="accepetd"></i>ACCEPTED</span>
					</li>
					<li>
						<h3>{{EngContCtrl.subHeaderCount.hired_count}}</h3>
						<span><img src="public/images/hired-header.svg" alt="hired">HIRED</span>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>

<div class="engage-contact">
	<div class="container">
		<div class="row">
			<ul class="nav nav-tabs" ng-init="switchCond = EngContCtrl.tabCond">
  				<li ng-class="{'active':EngContCtrl.tabCond == 'ALL'}"><a data-toggle="tab" ng-click="EngContCtrl.referralsCond('');switchCond = 'ALL'">ALL REFERRALS ({{EngContCtrl.subHeaderCount.referral_count ? EngContCtrl.subHeaderCount.referral_count : '0'}})</a></li>
  				<li ng-class="{'active':EngContCtrl.tabCond == 'PENDING'}"><a data-toggle="tab" ng-click="EngContCtrl.referralsCond('PENDING');switchCond = 'PENDING'">PENDING ({{EngContCtrl.subHeaderCount.pending_count ? EngContCtrl.subHeaderCount.pending_count : '0'}})</a></li>
  				<li ng-class="{'active':EngContCtrl.tabCond == 'ACCEPTED'}"><a data-toggle="tab" ng-click="EngContCtrl.referralsCond('ACCEPTED');switchCond = 'ACCEPTED'">ACCEPTED ({{EngContCtrl.subHeaderCount.accepted_count ? EngContCtrl.subHeaderCount.accepted_count : '0'}})</a></li>
			</ul>

			<div class="tab-content" ng-switch="switchCond">
		  		<div id="all" class="tab-pane active" ng-class="{'active': switchCond == 'ALL'}" ng-switch-when="ALL">
		  			<div class="box">
			    		<div class="box-content" style="padding: 30px 0px 0px 0px;">
							<ul>
								<li class="t_head" ng-style="{'border-bottom':EngContCtrl.length_zero ? '1px solid #ccc' : ''}">
									<div class="col-lg-3">
										CANDIDATE
									</div>
									<div class="col-lg-3">
										REFERRER 
									</div>
									<div class="col-lg-2">
										REFERRED ON
									</div>
									<div class="col-lg-2">
										RESUME
									</div>
									<div class="col-lg-2 text-center">
										STATUS
									</div>
								</li>
								<li ng-repeat="allReferrals in EngContCtrl.referrals">
									<div class="col-lg-3">
										<div class="pull-left">
											<img ng-src="{{allReferrals.dp_image == null ? 'public/images/avatar.png' : allReferrals.dp_image}}" class="img-responsive img-circle border-{{allReferrals.status | lowercase}}" ng-style="{'border': allReferrals.dp_image == null ? '0': ''}">
										</div>
										<div class="content pull-left" ng-style="{'padding-top': allReferrals.designation == ''? '18px' : ''}" style="width:75%">
											<big class="ellipsis" title="{{allReferrals.name}}">{{allReferrals.name}}</big>
											<p style="margin:0" class="ellipsis" title="{{allReferrals.designation}}">{{allReferrals.designation}}</p>
										</div>
									</div>
									<div class="col-lg-3" style="padding: 0">
										<div class="pull-left">
											<img ng-src="{{allReferrals.referred_by_dp_image}}" class="img-responsive img-circle border-default">
										</div>
										<div class="content pull-left" ng-style="{'padding-top': allReferrals.ref_designation == ''? '18px' : ''}" style="width:75%">
											<big class="ellipsis" title="{{allReferrals.referred_by_name}}">{{allReferrals.referred_by_name}}</big>
											<p style="margin:0;" class="ellipsis" title="{{allReferrals.ref_designation}}">{{allReferrals.ref_designation}}</p>
										</div>
									</div>
									<div class="col-lg-2" style="padding-top:6px;">
										<img src="public/images/clock.png"alt="clock">&nbsp;&nbsp;
										<span style="display: inline-block;padding: 12px 0;line-height: 1.8em">{{allReferrals.created_at}}</span>
									</div>
									<div class="col-lg-2" style="padding-top:6px;">
										<div ng-if="!allReferrals.resume_path == ''">
											<a href="{{allReferrals.resume_path}}" download>
												<!-- <img src="public/images/download.svg" alt="download_svg"> -->
												<div style="background:url('public/images/referrals.png') no-repeat 0 -257px" class="multiple-images"></div>
											</a>
											<a href="{{allReferrals.resume_path}}" target="_blank">
												<span class="resume_file" title="{{allReferrals.resume_path | fileName}}">{{allReferrals.resume_path | fileName}}</span>
											</a>
										</div>
										<div ng-if="allReferrals.resume_path == ''" style="padding-top:15px;">
											No Resume Found
										</div>
									</div>
									<div class="col-lg-2 text-center pointer" style="padding-top: 20px" ng-if="allReferrals.status == 'PENDING'">
										<span  ng-click="EngContCtrl.referral_status('',allReferrals,'accepted')" style="outline:none;"><img src="public/images/tickmark-accept.svg" alt="response"><span class="tick-accept">ACCEPT</span></span>
										<img src="public/images/closemark-decline.svg" alt="response" ng-click="EngContCtrl.referral_status('',allReferrals,'declined')" class="pull-right">
									</div>
									<div class="col-lg-2 text-center" style="padding-top: 20px" ng-if="allReferrals.status != 'PENDING'">
										<div class="multiple-images" ng-style="{'background':allReferrals.status == 'ACCEPTED' ? 'url(public/images/referrals.png) no-repeat -4px -96px' : 'url(public/images/referrals.png) no-repeat -4px -137px'}"></div><span class="text-{{allReferrals.status | lowercase}}">{{allReferrals.status}}</span>
									</div>
								</li>
								<div class="clearfix"></div>
								<div class="text-center" style="height:500px;line-height:500px" ng-if="EngContCtrl.referrals_load_cond">Loading data...</div>
								<div class="text-center" style="height:500px;line-height:500px;" ng-if="EngContCtrl.length_zero">No Data Found</div>
							</ul>
						</div>
			    	</div>
		  		</div>
		  		<div id="pending" class="tab-pane" ng-class="{'active': switchCond == 'PENDING'}" ng-switch-when="PENDING">
		    		<div class="box">
			    		<div class="box-content" style="padding: 30px 0px 0px 0px;">
							<ul>
								<li class="t_head" ng-style="{'border-bottom':EngContCtrl.length_zero ? '1px solid #ccc' : ''}">
									<div class="col-lg-3">
										CANDIDATE
									</div>
									<div class="col-lg-3">
										REFERRER 
									</div>
									<div class="col-lg-2">
										REFERRED ON
									</div>
									<div class="col-lg-2">
										RESUME
									</div>
									<div class="col-lg-2 text-center">
										AWAITING ACTION
									</div>
								</li>
								<li ng-repeat="pendingReferrals in EngContCtrl.referrals">
									<div class="col-lg-3">
										<div class="pull-left">
											<img ng-src="{{pendingReferrals.dp_image == null ? 'public/images/avatar.png' : pendingReferrals.dp_image}}" class="img-responsive img-circle border-{{pendingReferrals.status | lowercase}}" ng-style="{'border': pendingReferrals.dp_image == null ? '0': ''}">
										</div>
										<div class="content pull-left" ng-style="{'padding-top': pendingReferrals.designation == ''? '18px' : ''}" style="width:75%;">
											<big class="ellipsis" title="{{pendingReferrals.name}}">{{pendingReferrals.name}}</big>
											<p style="margin:0" class="ellipsis" title="{{pendingReferrals.designation}}">{{pendingReferrals.designation}}</p>
										</div>
									</div>
									<div class="col-lg-3" style="padding: 0">
										<div class="pull-left">
											<img ng-src="{{pendingReferrals.referred_by_dp_image}}" class="img-responsive img-circle border-default">
										</div>
										<div class="content pull-left" ng-style="{'padding-top': pendingReferrals.ref_designation == ''? '18px' : ''}"style="width:75%">
											<big class="ellipsis" title="{{pendingReferrals.referred_by_name}}">{{pendingReferrals.referred_by_name}}</big>
											<p style="margin:0;" class="ellipsis" title="{{pendingReferrals.ref_designation}}">{{pendingReferrals.ref_designation}}</p>
										</div>
									</div>
									<div class="col-lg-2" style="padding-top:6px;">
										<img src="public/images/clock.png"alt="clock">&nbsp;&nbsp;
										<span style="display: inline-block;padding: 12px 0;line-height: 1.8em">{{pendingReferrals.created_at}}</span>
									</div>
									<div class="col-lg-2" style="padding-top:6px;">
										<div ng-if="!pendingReferrals.resume_path == ''">
											<a href="{{pendingReferrals.resume_path}}" download>
												<!-- <img src="public/images/download.svg" alt="download_svg"> -->
												<div style="background:url('public/images/referrals.png') no-repeat 0 -257px" class="multiple-images"></div>
											</a>
											<a href="{{pendingReferrals.resume_path}}" target="_blank">
												<span class="resume_file" title="{{pendingReferrals.resume_path | fileName}}">{{pendingReferrals.resume_path | fileName}}</span>
											</a>
										</div>
										<div ng-if="pendingReferrals.resume_path == ''" style="padding-top:15px;">
											No Resume Found
										</div>
									</div>
									<div class="col-lg-2 text-center pointer" style="padding-top: 20px"><!-- ng-if="pendingReferrals.status == 'PENDING'">-->
										<span ng-click="EngContCtrl.referral_status('PENDING',pendingReferrals,'accepted')" style="outline:none"><img src="public/images/tickmark-accept.svg" alt="response"><span class="tick-accept">ACCEPT</span></span>
										<img src="public/images/closemark-decline.svg" alt="response" ng-click="EngContCtrl.referral_status('PENDING',pendingReferrals,'declined')" class="pull-right">
									</div>
									<!-- <div class="col-lg-2 text-center" style="padding-top: 20px" ng-if="pendingReferrals.status != 'PENDING'">
										<span class="text-{{pendingReferrals.status | lowercase}}">{{pendingReferrals.status}}</span>
									</div> -->
								</li>
								<div class="clearfix"></div>
								<div class="text-center" style="height:500px;line-height:500px" ng-if="EngContCtrl.referrals_load_cond">Loading data...</div>
								<div class="text-center" style="height:500px;line-height:500px;" ng-if="EngContCtrl.length_zero">No Data Found</div>
							</ul>
						</div>
			    	</div>
		  		</div>
		  		<div id="active" class="tab-pane" ng-class="{'active': switchCond == 'ACCEPTED'}" ng-switch-when="ACCEPTED">
		    		<div class="box">
			    		<div class="box-content" style="padding: 30px 0px 0px 0px;">
							<ul>
								<li class="t_head" ng-style="{'border-bottom':EngContCtrl.length_zero ? '1px solid #ccc' : ''}">
									<div class="col-lg-3">
										CANDIDATE
									</div>
									<div class="col-lg-3">
										REFERRER 
									</div>
									<div class="col-lg-2">
										RESUME
									</div>
									<div class="col-lg-4">
										AWAITING ACTION
									</div>
								</li>
								<li ng-repeat="activeReferrals in EngContCtrl.referrals" style="padding:16px 0!important">
									<div class="col-lg-3">
										<div class="pull-left">
											<img ng-src="{{activeReferrals.dp_image == null ? 'public/images/avatar.png' : activeReferrals.dp_image}}" class="img-responsive img-circle border-{{activeReferrals.status | lowercase}}" ng-style="{'border': activeReferrals.dp_image == null ? '0': ''}">
										</div>
										<div class="content pull-left" ng-style="{'padding-top': activeReferrals.designation == ''? '18px' : ''}" style="width:75%">
											<big class="ellipsis" title="{{activeReferrals.name}}">{{activeReferrals.name}}</big>
											<p style="margin:0" class="ellipsis" title="{{activeReferrals.designation}}">{{activeReferrals.designation}}</p>
										</div>
									</div>
									<div class="col-lg-3" style="padding: 0">
										<div class="pull-left">
											<img ng-src="{{activeReferrals.referred_by_dp_image}}" class="img-responsive img-circle border-default">
										</div>
										<div class="content pull-left" ng-style="{'padding-top': activeReferrals.ref_designation == ''? '18px' : ''}" style="width:75%;">
											<big class="ellipsis" title="{{activeReferrals.referred_by_name}}">{{activeReferrals.referred_by_name}}</big>
											<p style="margin:0;" class="ellipsis" title="{{activeReferrals.ref_designation}}">{{activeReferrals.ref_designation}}</p>
										</div>
									</div>
									<div class="col-lg-2" style="padding-top:6px;">
										<div ng-if="!activeReferrals.resume_path == ''">
											<a href="{{activeReferrals.resume_path}}" download>
												<!-- <img src="public/images/download.svg" alt="download_svg"> -->
												<div style="background:url('public/images/referrals.png') no-repeat 0 -257px" class="multiple-images"></div>
											</a>
											<a href="{{activeReferrals.resume_path}}" target="_blank">
												<span class="resume_file" title="{{activeReferrals.resume_path | fileName}}">{{activeReferrals.resume_path | fileName}}</span>
											</a>
										</div>
										<div ng-if="activeReferrals.resume_path == ''" style="padding-top:15px;">
											No Resume Found
										</div>
									</div>
									<!-- <div class="col-lg-4 text-center" style="padding-top: 20px" ng-if="activeReferrals.status == 'PENDING'">
										<img src="public/images/tickmark-accept.svg" alt="response" ng-click="EngContCtrl.referral_status('ACCEPTED',activeReferrals,'accepted')">&nbsp;&nbsp;
										<img src="public/images/closemark-decline.svg" alt="response" ng-click="EngContCtrl.referral_status('ACCEPTED',activeReferrals,'declined')">
									</div> -->
									<div class="col-lg-4" style="margin-top:-5px"><!-- ng-if="activeReferrals.status != 'PENDING'">-->
										<div class="btn-group">
											<div style="pointer-events:none" ng-class="{'bg-accepted':activeReferrals.awaiting_action_status == 'ACCEPTED'}">Accepted</div>
											<div class="interviewed" ng-click="EngContCtrl.process_status('INTERVIEWED',$index)" ng-class="{'bg-accepted':activeReferrals.awaiting_action_status == 'INTERVIEWED'}">Interviewed</div>
											<div class="offermade" ng-click="EngContCtrl.process_status('OFFERMADE',$index)" ng-class="{'bg-accepted':activeReferrals.awaiting_action_status == 'OFFERMADE'}">Offer Made</div>
											<div class="hired" ng-click="EngContCtrl.process_status('HIRED',$index)" ng-class="{'bg-accepted':activeReferrals.awaiting_action_status == 'HIRED'}">Hired</div>
										</div>
										<div class="status_details" style="position:absolute;font-size:13px;">
											<span>{{activeReferrals.name+" "+activeReferrals.awaiting_action_status+" by "+activeReferrals.awaiting_action_by+" at "+activeReferrals.awaiting_action_updated_at}}</span>
										</div>
									</div>
								</li>
								<div class="clearfix"></div>
								<div class="text-center" style="height:500px;line-height:500px" ng-if="EngContCtrl.referrals_load_cond">Loading data...</div>
								<div class="text-center" style="height:500px;line-height:500px;" ng-if="EngContCtrl.length_zero">No Data Found</div>
							</ul>
						</div>
			    	</div>
		  		</div>
			</div>	

		</div>
	</div>
</div>
