<div class="forgot-password">

	<header class="text-center">
		<a href=""><img src="public/images/company_logo.svg" class="logo"></a>
	</header>

	<section>
		<div class="container">
			<div style="width:55%;margin:0 auto;">
				<form role="form" name="re_enter_password_form" ng-submit="forgotCtrl.forgot_submit(re_enter_password_form.$valid)" novalidate>
					<h1>Check---{{forgotCtrl.createPwd}}</h1>
					<h1 class="text-center">Create New Password</h1>
					<div class="error-spacer" style="float:none">
						<div ng-if="forgotCtrl.backendError" class="has-error-msg text-center" style="float:none">{{forgotCtrl.backendMsg}}</div>
					</div>

					<div style="padding:10px 0;width:70%;margin:0 auto;">
						<md-input-container class="md-block">
							<label for="new_password">New Password</label>
							<input type="password" id="new_password" name="new_password" ng-model="forgotCtrl.forgotPassword.new_password" required ng-pattern="/^(?=.*[a-zA-Z0-9]).{6,16}$/" ng-class="{'has-error-border':re_enter_password_form.new_password.$invalid && forgotCtrl.forgot_show_error}">
		         			<div ng-if="re_enter_password_form.new_password.$error.required && forgotCtrl.forgot_show_error" class="has-error-msg">Please enter New Password.</div>
		         			<div ng-if="re_enter_password_form.new_password.$error.pattern && forgotCtrl.forgot_show_error" class="has-error-msg">Please enter atleast 6 characters.</div>
						</md-input-container>
						<md-input-container class="md-block">
							<label for="re_password">Confirm Password</label>
							<input type="password" id="re_password" name="re_password" ng-model="forgotCtrl.forgotPassword.re_password" pw-match="new_password" ng-class="{'has-error-border': re_enter_password_form.re_password.$invalid && forgotCtrl.forgot_show_error}" required>
							<div ng-if="re_enter_password_form.re_password.$error.required && forgotCtrl.forgot_show_error" class="has-error-msg">Please enter Confirm Password.</div>
			         		<div ng-if="re_enter_password_form.re_password.$dirty && re_enter_password_form.re_password.$error.pwmatch && forgotCtrl.forgot_show_error && !re_enter_password_form.re_password.$error.required" class="has-error-msg">Password doesn't match.</div>
						</md-input-container>
						<div class="text-center"><button class="btn btn-lg btn-style btn-loader">Reset Password<img src="public/images/loader/butt_loader.gif" width="30px" style="margin-top: -2px;" alt="loader" ng-if="forgotCtrl.load_cond_reset"></button></div>
						<div class="back-to-home text-center"><span ng-click="forgotCtrl.forgot_cancel()">Cancel</span></div>
					</div>
				</form>
			</div>
		</div>
	</section>

	<footer>
		<div class="container">
			<div class="row">
				<div class="col-sm-5">
					<p>&copy; 2017 MINTMESH&trade; INC. ALL RIGHTS RESERVED.</p>
				</div>
				<div class="col-sm-7">
					<ul>
						<li><a href="https://mintmesh.com/us/" target="_blank">ABOUT US</a></li>
						<li><a href="https://mintmesh.com/terms-of-use/" target="_blank">TERMS & CONDITIONS</a></li>
						<li><a href="https://mintmesh.com/privacy-policy/" target="_blank">PRIVACY POLICY</a></li>
					</ul>
				</div>
			</div>
		</div>
	</footer>

</div>