<div class="container" ng-init="selectedTab = 'dashboard'">
	<div class="row">
		<div class="col-lg-2">
			<a ui-sref=".dashboard"><img src="public/images/logo.png" alt="brand-logo"></a>
		</div>
		<div class="menu col-lg-7">
			<ul class="opt">
				<li><a ui-sref=".dashboard" ng-class="{'active':selectedTab === 'dashboard'}" ng-click="selectedTab = 'dashboard'">DASHBOARD</a></li>
				<li><a ui-sref=".job" ng-class="{'active':selectedTab === 'job'}" ng-click="selectedTab = 'job'">JOBS</a></li>
				<li><a href="">CONTACTS</a></li>
				<!-- <li><a ui-sref=".importContactsList" ng-class="{'active':selectedTab === 'contacts'}" ng-click="selectedTab = 'contacts'">CONTACTS</a></li> -->
				<!-- <li><a ui-sref="#/">SETTINGS</a></li> -->
			</ul>
		</div>
		<div class="notifications col-lg-3 pull-right text-center">
			<div class="row">
				<div class="not_alert col-lg-3" style=visibility:hidden>
					<span class="num">2</span>
					<i class="fa fa-bell-o"></i>
				</div>
				<div class="col-lg-9">
					<div class="user">
						<span><img src="public/images/arrow-dropdown-white.svg"></span>
						<span class="comp_name">Jennifer</span>
						<span class="user_dp"><img src="public/images/Ui_Faces/Jenifer.jpg" class="image-responsive img-circle" alt="dp" style="width: 40px;border: 1px solid #ccc"></span>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>