<div  class="grid-contacts import-contacts">
	<div class="container">
		<div class="row">
			<div class="col-sm-12">

				<div class="im-c-head">
					<h3 class="mrZpdZ pull-left" style="color:#808080"><a ui-sref="importContacts"><img src="public/images/back-arrow-black.svg" alt="arrowback"> Import Contacts</a></h3>
					<a href=""><img src="public/images/company_logo.svg" alt="logo" class="import_logo"></a>
				</div>

				<div ng-include="'templates/contacts.phtml'">
				</div>
				
			</div>
		</div>
	</div>
</div>