<div  style="background:#F2F2F2;padding:0">
	<div class="container">
		<div class="row">
			<div class="col-sm-10 col-sm-offset-1">

				<!-- logo -->
				<div class="text-center">
					<a href=""><img src="public/images/logo.png" alt="logo" class="import_logo"></a> 
				</div>

				<!--import contacts-->
				<div class="row" id="import_c_box">
					<div class="col-sm-12" class="tit_head"> 
						<div style="padding:22px 0px;text-align:center">
							<img src="public/images/arrow-back.svg" alt="arrowback" style="float:left" ng-click="invConts.backToImportContact()">
							<h3 class="mrZpdZ text-center" style="color:#E98029;display:inline-block">INVITE TO MINTMESH</h3>
							<a ui-sref='home' style="color:black"><span class="skip">SKIP<img src="public/images/arrow-buttons-skip.svg" style="margin-top: -6px;padding-left: 4px;" alt="arrow"></span></a>
						</div>
					</div>

					<!--angular grid-->
					<div class="col-sm-12" style="padding:0px">
						<div ui-grid="gridOptions" ui-grid-selection class="grid import-con-grid">
						<!-- <div class="grid-msg-overlay" ng-hide="gridOptions.data.length && !loading">
						    <div class="msg">
						      <span>Loading Data...</span>
						      <i class="fa fa-spinner fa-spin"></i>
						    </div>
						  </div>
						</div> -->
					</div>
				</div>
				<!--footer-->
				<div class="col-sm-12" id="im_c_foot">
					<button class="btn pull-right" ng-click="invConts.inviteCustom()">CONTINUE<img src="public/images/arrow-buttons.svg" alt="arrow"></button>
				</div>
			</div>
		</div>
	</div>
</div>