<link rel="stylesheet" type="text/css" href="public/css/job_style.css">

<div class="sub-header">
	<div class="container">
		<div class="mid-nav">
			<h3>
				<a ui-sref="^.job"><img src="public/images/back-arrow.svg" alt="back" style="margin-bottom: 4px;">
				<span>UI/UX Designer</span></a>
			</h3>
			<span class="openbox" style="margin:0">OPEN</span>
		</div>
		<ul>
			<li><a ui-sref="^.jobDetails">JOB DETAILS</a></li>
			<li><a ui-sref="^.engagement/contacts">ENGAGEMENT/CONTACTS</a></li>
			<li><a ui-sref="^.rewards">REWARDS</a></li>
		</ul>
	</div>
</div>
<div class="container" style="font-size:16px;min-height:873px">
	<div class="row">
		<div class="col-xs-12 job_des_bo">
			<div class="job_des_info">
				<div>
					<span>Job function:</span>
					<span>{{jobDetailsCtrl.post_data.job_function}}</span>
				</div>
				<div>
					<span>Industry:</span>
					<span>{{jobDetailsCtrl.post_data.industry_name}}</span>
				</div>
				<div>
					<span>Location:</span>
					<span>{{jobDetailsCtrl.post_data.location}}</span>
				</div>
				<div>
					<span>Experience:</span>
					<span>{{jobDetailsCtrl.post_data.experience_range}}</span>
				</div>
				<div>
					<span>Employment type:</span>
					<span>{{jobDetailsCtrl.post_data.employment_type}}</span>
				</div>
				<div>
					<span>Position ID:</span>
					<span>{{jobDetailsCtrl.post_data.position_id}}</span>
				</div>
				<div>
					<span>Requisition ID:</span>
					<span>{{jobDetailsCtrl.post_data.requistion_id}}</span>
				</div>
			</div>
		</div>
		<div class="col-xs-12 job-des-text job_des_bo">
			<p>Job Description:</p>
			<p>{{jobDetailsCtrl.job_description}}</p>
			
		</div>
		<div class="col-xs-12 job-des-text job_des_bo" style="border:0">
			<p>Company Description:</p>
			<p>{{jobDetailsCtrl.company_description}}</p>
		</div>
</div>
