
<div class="job_details loader" style="min-height:1000px" ng-if="jobDetailsCtrl.job_details_loader"></div>

<div class="sub-header">
	<div class="container">
		<div class="row">
			<div class="col-sm-5 sub_left">
				<div class="mid-nav">
					<h3>
						<a ui-sref="^.job"><img src="public/images/back-arrow.svg" alt="back">
							<span class="ellipsis" ng-bind="jobDetailsCtrl.post_data.job_title">
								<md-tooltip>{{jobDetailsCtrl.post_data.job_title}}</md-tooltip>
							</span>
						</a>
					</h3>
					<span class="post {{jobDetailsCtrl.post_data.post_type}}" ng-bind="jobDetailsCtrl.post_data.post_type"></span>
					<span class="status {{jobDetailsCtrl.post_data.status == 'ACTIVE' ? 'open' : 'closed'}}" ng-bind="jobDetailsCtrl.post_data.status == 'ACTIVE' ? 'OPEN' : 'CLOSED'">
					</span>
				</div>
				<ul>
					<li><a ui-sref="^.jobDetails({post_id:jobDetailsCtrl.post_id})" ui-sref-active="active">JOB DETAILS</a></li>
					<li><a ui-sref="^.engagement/contacts({post_id:jobDetailsCtrl.post_id})" ui-sref-active="active">REFERRALS</a></li>
					<li><a ui-sref="^.rewards({post_id:jobDetailsCtrl.post_id})" ui-sref-active="active">REWARDS</a></li>
				</ul>
			</div>
			<div class="col-sm-7 text-center sub-right">
				<ul>
					<li>
						<h3>{{jobDetailsCtrl.post_data.invited_count}}</h3>
						<span><img src="public/images/invited-header.svg" alt="invited">INVITED</span>
					</li>
					<li>
						<h3>{{jobDetailsCtrl.post_data.referral_count}}</h3>
						<span><img src="public/images/referrals-header.svg" alt="referrals">REFERRALS</span>
					</li>
					<li>
						<h3>{{jobDetailsCtrl.post_data.pending_count}}</h3>
						<span><img src="public/images/referrals-header.svg" alt="pending">PENDING</span>
					</li>
					<li>
						<h3>{{jobDetailsCtrl.post_data.accepted_count}}</h3>
						<span><img src="public/images/Applied.svg" alt="applied"></i>ACCEPTED</span>
					</li>
					<li>
						<h3>{{jobDetailsCtrl.post_data.hired_count}}</h3>
						<span><img src="public/images/hired-header.svg" alt="hired">HIRED</span>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>


<div class="container new-job-details" style="font-size:16px;min-height:873px" ng-if="!jobDetailsCtrl.job_details_loader">
	<div class="row info-box" style="margin:0;position:relative">
		<span class="close-job ripplelink" ng-click="jobDetailsCtrl.closeJob()" ng-if="jobDetailsCtrl.post_data.status == 'ACTIVE'" ng-show="::jobDetailsCtrl.post_data.is_close == '1'">
			CLOSE JOB
		</span>
		<div class="col-sm-6 lt">
			<div class="row">
				<span class="col-sm-5">Job Function:</span>
				<span class="col-sm-7">{{jobDetailsCtrl.post_data.job_function}}</span>
			</div>
			<div class="row">
				<span class="col-sm-5">Industry:</span>
				<span class="col-sm-7">{{jobDetailsCtrl.post_data.industry_name}}</span>
			</div>
			<div class="row">
				<span class="col-sm-5">Location:</span>
				<span class="col-sm-7">{{jobDetailsCtrl.post_data.location}}</span>
			</div>
			<div class="row">
				<span class="col-sm-5">Experience:</span>
				<span class="col-sm-7">{{jobDetailsCtrl.post_data.experience_range}}</span>
			</div>
			<div class="row">
				<span class="col-sm-5">Employment Type:</span>
				<span class="col-sm-7">{{jobDetailsCtrl.post_data.employment_type}}</span>
			</div>
			<div class="row" ng-if="jobDetailsCtrl.post_data.no_of_vacancies != 0">
				<span class="col-sm-5">Number of Vacancies:</span>
				<span class="col-sm-7">{{jobDetailsCtrl.post_data.no_of_vacancies}}</span>
			</div>
			<div class="row" ng-if="jobDetailsCtrl.post_data.position_id != ''">
				<span class="col-sm-5">Position ID:</span>
				<span class="col-sm-7">{{jobDetailsCtrl.post_data.position_id}}</span>
			</div>
			<div class="row" ng-if="jobDetailsCtrl.post_data.requistion_id != ''">
				<span class="col-sm-5">Requisition ID:</span>
				<span class="col-sm-7">{{jobDetailsCtrl.post_data.requistion_id}}</span>
			</div>
		</div>
		<div class="col-sm-6 rt">
			<div class="currency">
				<div ng-hide="jobDetailsCtrl.post_data.rewards.length == 0">
					<h4 style="color:#777777;font-weight: 700;">Job Rewards:</h4>
					<div class="box-rewards">
						<div ng-repeat="rewards in jobDetailsCtrl.post_data.rewards">
							<span ng-bind="(rewards.rewards_name) + ' Rewards'"></span>
							<h4 ng-bind="jobDetailsCtrl.getRewardsView(rewards)"
								ng-style="{'color': rewards.rewards_name == 'Discovery' ? '#3e7b1c' :' #2174a6'}">	
							</h4>
						</div>
					</div>
				</div>
				<div>
					<h4>Invited Groups:</h4>
					<h4><span style="color:inherit" ng-repeat="bktName in jobDetailsCtrl.post_data.bucket_name">{{bktName + ($last ? '' : ',&nbsp;') }}</span></h4>
				</div>
			</div>
		</div>
	</div>
	<div class="job-des-text job_des_bo">
		<p>Job Description:</p>
		<span ng-bind-html="jobDetailsCtrl.post_data.job_description"></span>
	</div>
	<div class="job-des-text job_des_bo" style="border:0">
		<p>Company Description:</p>
		<span ng-bind-html="jobDetailsCtrl.post_data.company_description"></span>
	</div>
</div>
