
<div class="job_details loader" style="min-height:1000px" ng-if="jobDetailsCtrl.job_details_loader"></div>

<div class="sub-header">
	<div class="container">
		<div class="row">
			<div class="col-sm-5 sub_left">
				<div class="mid-nav">
					<h3>
						<a ui-sref="^.job" style="min-width:100px;"><img src="public/images/back-arrow.svg" alt="back" style="margin-bottom: 4px;">
						<span style="min-width:100px;">{{jobDetailsCtrl.post_data.job_title | uppercase}}</span></a>
					</h3>
					<span class="openbox" style="margin:0"
						ng-bind="jobDetailsCtrl.post_data.status == 'ACTIVE' ? 'OPEN' : 'CLOSED'"
						ng-style="{'background' : jobDetailsCtrl.post_data.status == 'ACTIVE' ? '' : '#be7276'}">
					</span>
				</div>
				<ul>
					<li><a ui-sref="^.jobDetails({post_id:jobDetailsCtrl.post_id})" ui-sref-active="active">JOB DETAILS</a></li>
					<li><a ui-sref="^.engagement/contacts({post_id:jobDetailsCtrl.post_id})" ui-sref-active="active">REFERRALS</a></li>
					<li><a ui-sref="^.rewards({post_id:jobDetailsCtrl.post_id})" ui-sref-active="active">REWARDS</a></li>
				</ul>
			</div>
			<div class="col-sm-7 text-center sub-right">
				<ul>
					<li>
						<h3>{{jobDetailsCtrl.post_data.invited_count}}</h3>
						<span><img src="public/images/invited-header.svg" alt="invited">INVITED</span>
					</li>
					<li>
						<h3>{{jobDetailsCtrl.post_data.referral_count}}</h3>
						<span><img src="public/images/referrals-header.svg" alt="referrals">REFERRALS</span>
					</li>
					<li>
						<h3>{{jobDetailsCtrl.post_data.pending_count}}</h3>
						<span><img src="public/images/referrals-header.svg" alt="pending">PENDING</span>
					</li>
					<li>
						<h3>{{jobDetailsCtrl.post_data.accepted_count}}</h3>
						<span><img src="public/images/Applied.svg" alt="applied"></i>ACCEPTED</span>
					</li>
					<li>
						<h3>{{jobDetailsCtrl.post_data.hired_count}}</h3>
						<span><img src="public/images/hired-header.svg" alt="hired">HIRED</span>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>


<div class="container" style="font-size:16px;min-height:873px" ng-if="!jobDetailsCtrl.job_details_loader">
	<div class="row" style="margin:0;position:relative">
		<span class="close-job" ng-click="jobDetailsCtrl.closeJob()" ng-if="jobDetailsCtrl.post_data.status == 'ACTIVE'">
			CLOSE JOB
		</span>
		<div class="col-xs-12 job_des_bo">
			<div class="job_des_info">
				<div>
					<span>Job Function:</span>
					<span>{{jobDetailsCtrl.post_data.job_function}}</span>
				</div>
				<div>
					<span>Industry:</span>
					<span>{{jobDetailsCtrl.post_data.industry_name}}</span>
				</div>
				<div>
					<span>Location:</span>
					<span>{{jobDetailsCtrl.post_data.location}}</span>
				</div>
				<div>
					<span>Experience:</span>
					<span>{{jobDetailsCtrl.post_data.experience_range}}</span>
				</div>
				<div>
					<span>Employment Type:</span>
					<span>{{jobDetailsCtrl.post_data.employment_type}}</span>
				</div>
				<div>
					<span>Position ID:</span>
					<span>{{jobDetailsCtrl.post_data.position_id}}</span>
				</div>
				<div>
					<span>Requisition ID:</span>
					<span>{{jobDetailsCtrl.post_data.requistion_id}}</span>
				</div>
			</div>
		</div>
		<div class="col-xs-12 job-des-text job_des_bo">
			<p>Job Description:</p>
			<p class="indent" style="white-space: pre-line;">{{jobDetailsCtrl.post_data.job_description}}</p>
			
		</div>
		<div class="col-xs-12 job-des-text job_des_bo" style="border:0">
			<p>Company Description:</p>
			<p class="indent" style="white-space: pre-line;">{{jobDetailsCtrl.post_data.company_description}}</p>
		</div>
</div>
