<link rel="stylesheet" type="text/css" href="public/css/job_style.css">


<div class="job-search container padZ" style="padding-bottom:10%;min-height:1000px">
	<!--Search sort-->
	<div class="row search-job" style="padding:0;border:0;margin-bottom:1%">
		<div class="left-inner-addon col-xs-12 col-sm-4 ct-search">
    		<img src="public/images/search.svg" alt="feedback_left" ng-if="!jobSearchCtrl.search_load_cond">
    		<input type="text" ng-model="jobSearchCtrl.search_value" class="form-control search" placeholder="Search Jobs" ng-keyup="jobSearchCtrl.searchFilter(jobSearchCtrl.pay_status,jobSearchCtrl.search_value)"/>
    		<img src="public/images/loader/search_loader.gif" alt="feedback_left" style="width:45px;height:41px;" ng-if="jobSearchCtrl.search_load_cond"/>
    		<img src="public/images/cross.svg" class="feedback" ng-show="jobSearchCtrl.search_value.length >= 1" ng-click="jobSearchCtrl.search_value = '';jobSearchCtrl.searchFilter(jobSearchCtrl.pay_status,jobSearchCtrl.search_value)" alt="feedback_right">
           <span class="bar"></span>
		</div>
		<div class="col-xs-12 col-sm-6 col-sm-offset-2">
			<span>
				<span class="sort_g">Sort by</span>
				<div class="form-group">
					<i class="fa fa-angle-down fa-feedback select-arrow" style="color:#000"></i>
				  <select class="form-control" style="display:inline-block" ng-model="jobSearchCtrl.pay_status" ng-change="jobSearchCtrl.selectFilter(jobSearchCtrl.pay_status,jobSearchCtrl.search_value)">
				    <option value="2">All</option>
				    <option value="0">Paid</option>
				    <option value="1">Free</option>
				  </select>
				</div>
				<a ui-sref="^.postJob"><button class="btn"><img src="public/images/arrow-top.svg" alt="uparrow" style="margin-top:-3px"> POST REQUEST</button></a>
			</span>
		</div>	
	</div>

	<div class="total_record" ng-if="jobSearchCtrl.post_count">
		Total Jobs : {{jobSearchCtrl.post_count}}
	</div>

	<div class="post_err_msg" ng-if="jobSearchCtrl.init_no_posts_found">There are no open Job Requests  at this time.<br> Would you like to create a new Job Request?</div>
	<div class="post_err_msg" ng-if="jobSearchCtrl.no_posts_found">No Jobs Found</div>
	<!-- infinite scroll -->
	<div infinite-scroll='jobSearchCtrl.nextPage(jobSearchCtrl.pay_status,jobSearchCtrl.search_value)' infinite-scroll-disabled='jobSearchCtrl.busy' infinite-scroll-distance='2'>
		<!--Typeof Job -->
		<div class="row" ng-repeat="jobList in jobSearchCtrl.jobDetails">
			<div class="job-type">
				<img src="public/images/breifcase_gray.svg" alt="briefcase">
				<a href="" ui-sref="^.jobDetails({post_id:jobList.id})" title="" ng-click="jobSearchCtrl.job_details(jobList)">
					<h3>
						<span title="{{jobList.job_title}}">{{jobList.job_title}}</span>
						<img src="public/images/arrow-buttons_green.svg">
					</h3>
				</a>
				<span ng-init="sc=jobList.service_cost;jobList.cost = jobList.free_service == '1' ? 'FREE' : (jobList.service_currency =='DLR' ? '$'+sc+'/Referral' : '&#8377;'+sc+'/Referral')" style="float:right">
					<span ng-class="{'job_free':jobList.free_service == '1'}">
						{{jobList.cost}}
					</span>
					<span>
						{{jobList.created_at | myDate | date:'dd MMM, yyyy'}}
					</span>
					<img src="public/images/time.svg" title="{{jobList.created_at | limitTo:8:11}}" alt="search">
				</span>
			</div>
			<div class="job-info">
				<div class="col-sm-4 col-xs-12 job-info_d">
					<div>
						<span>Experience: </span>
						<span>{{jobList.experience.name}}</span>
					</div>
					<div>
						<span>Employment Type: </span>
						<span>{{jobList.employment.name}}</span>
					</div>
					<div>
						<span>Location: </span>
						<span title="{{jobList.location}}">{{jobList.location}}</span>
					</div>
				</div>
				<div class="col-sm-2 col-xs-6 invited">
					<div>
						<h1>{{jobList.invited_count}}</h1>
						<span><img src="public/images/invited.svg" alt="invited">INVITED</span>
					</div>
				</div>
				<div class="col-sm-2 referal_s col-xs-6 referral">
					<div>
						<h1>{{jobList.referral_count}}</h1>
						<span><img src="public/images/referrals.svg" alt="invited">REFERRALS</span>
					</div>
				</div>
				<div class="col-sm-2 col-xs-6 accepted">
					<div>
						<h1>{{jobList.accepted_count}}</h1>
						<span><img src="public/images/Applied.svg" alt="invited"></i>ACCEPTED</span>
					</div>
				</div>
				<div class="col-sm-2 col-xs-6 hired	">
					<div>
						<h1>{{jobList.hired_count}}</h1>
						<span><img src="public/images/hired.svg">HIRED</span>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div  ng-if="jobSearchCtrl.busy">
		<img src="public/images/loader/preloader.gif" alt="spinner" style="display: block;margin: 0 auto;width: 20%;">
	</div>
	
</div>