<div class="container post-job">
	<div class="row">
		<div class="job-title text-center">
			<a ui-sref="^.postJob"><img src="public/images/arrow-back.svg" alt="arrowback"></a>
			<h2>Get Ready to Post Your Request</h2>
		</div>
		<div class="job-info">
			<div>
				<span class="company-name" style="margin:0">Enter Pi</span>
			</div>
			<div class="job-name">
				<div class="col-lg-4">
					<div>
						<span>Job Title:</span>
						<span>{{post2Ctrl.post_job_result.job_title}}</span>
					</div>
					<div>
						<span>Job function:</span>
						<span>{{post2Ctrl.post_job_result.job_func}}</span>
					</div>
					<div>
						<span>Location:</span>
						<span>{{post2Ctrl.post_job_result.location}}</span>
					</div>
					<div>
						<span>Experience:</span>
						<span>{{post2Ctrl.post_job_result.experience}}</span>
					</div>
					<div>
						<span>Position ID:</span>
						<span>{{post2Ctrl.post_job_result.position_id}}</span>
					</div>
				</div>
				<div class="col-lg-8">
					<p style="color: #9A9A9A;font-size:16px;">Job Description:</p>
					
					<p>Responsibilities and tasks:</p>
					<p>{{post2Ctrl.post_job_result.job_desc}}</p>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="container-fluid reward-ref"  style="border-top:1px solid silver;padding-top:2%">
	<h2>SELECT THE REWARD </h2>
	<div class="container" style="padding: 40px 15px">
		<div class="choose-pay row row-centered">
			<div class="col-lg-3 col-centered" style="color:#D89731;">
				<div class="amount-pay amount-s">
					<h4>FREE</h4>
					<h1 style="visibility: hidden;">&#36; 0</h1>
					<h4>JUST A THANK YOU </h4>
					<input type="radio" name="amount-ref" ng-checked="true">
					<label></label>
				</div>
			</div>
			<div class="col-lg-3 col-centered">
				<div class="amount-pay">
					<h4>PAY</h4>
					<h1>&#36;10</h1>
					<h4>PER REFERRAL</h4>
					<input type="radio" name="amount-ref">
					<label></label>
				</div>
			</div>
			<div class="col-lg-3 col-centered">
				<div class="amount-pay">
					<h4>PAY</h4>
					<h1>&#36;20</h1>
					<h4>PER REFERRAL</h4>
					<input type="radio" name="amount-ref">
					<label></label>
				</div>
			</div>
			<div class="col-lg-3 col-centered">
				<div class="amount-pay">
					<h4>PAY</h4>
					<h1>&#36;50</h1>
					<h4>PER REFERRAL</h4>
					<input type="radio" name="amount-ref">
					<label></label>
				</div>
			</div>
			<div class="col-lg-3 col-centered">
				<div class="amount-pay">
					<h4>PAY</h4>
					<h1>&#36;100</h1>
					<h4>PER REFERRAL</h4>
					<input type="radio" name="amount-ref">
					<label></label>
				</div>
			</div>
			<div class="col-lg-3 col-centered">
				<div class="amount-pay">
					<h4>PAY</h4>
					<h1>&#36;500</h1>
					<h4>PER REFERRAL</h4>
					<input type="radio" name="amount-ref">
					<label></label>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="container-fluid" style="padding-bottom: 100px;">
	<div class="container" style="border-top:1px solid #ccc">
		<h2 class="text-center" style="color: #388A73;padding: 30px 15px 40px;margin:0">SELECT THE DISTRIBUTION LIST </h2>
		<div class="row select-type row-centered">
			<div class="col-lg-3 col-centered">
				<div class="amount-pay" style="background: #3B8670;" >
					<!-- <i class="fa fa-plus-circle" ng-click="icon = true" ng-if="!icon"></i>
				    <i class="fa fa-check-circle-o"  ng-click="icon = false" ng-if="icon"></i> -->
				    
				    <img src="public/images/add.svg"  ng-click="post2Ctrl.icon = true" ng-if="!post2Ctrl.icon">
				    <img src="public/images/select.svg"  ng-click="post2Ctrl.icon = false" ng-if="post2Ctrl.icon">
				    <h3>EMPLOYEES</h3>
				</div>
			</div>
			<div class="col-lg-3 col-centered" >
				<div class="amount-pay" style="background: #907942;">
					<img src="public/images/add.svg"  ng-click="post2Ctrl.icon_c = true" ng-if="!post2Ctrl.icon_c">
				    <img src="public/images/select.svg"  ng-click="post2Ctrl.icon_c = false" ng-if="post2Ctrl.icon_c">
				    <h3>CLIENTS</h3>
				</div>
			</div>
			<div class="col-lg-3 col-centered">
				<div class="amount-pay" style="background: #607D8B;">
					<img src="public/images/add.svg"  ng-click="post2Ctrl.icon_s = true" ng-if="!post2Ctrl.icon_s">
				    <img src="public/images/select.svg"  ng-click="post2Ctrl.icon_s = false" ng-if="post2Ctrl.icon_s">
				    <h3>CANDIDATES</h3>
				</div>
			</div>
			<div class="col-lg-3 col-centered">
				<div class="amount-pay" style="background: #4574A9;">
					<img src="public/images/add.svg"  ng-click="post2Ctrl.icon_i = true" ng-if="!post2Ctrl.icon_i">
				    <img src="public/images/select.svg"  ng-click="post2Ctrl.icon_i = false" ng-if="post2Ctrl.icon_i">
				    <h3>iOS DEVELOPERS</h3>
				</div>
			</div>
		</div>
	</div>
	<div class="text-center" style="padding: 40px 0">
		<button class="btn btn-style" ng-click="post2Ctrl.requestSuccess()" style="padding: 12px 32px;">POST REQUEST</button>
	</div>
</div>
