
<div class="post-job">

	<section>
		<div class="container" style="padding-bottom: 80px;">
			<div class="job-title" style="padding-left:0px;">
				<!-- <img src="" alt="enterpi"> -->
				<a ui-sref="^.job"><img src="public/images/back-arrow-black.svg" alt="arrowback" style="margin-top:30px;"></a>
				<span class="company-name">{{PtJobCtrl.company_name | uppercase}}</span>
				<h2 class="text-center">Create Your Request</h2>
			</div>

			<div class="content">
				<form role="form" name="post_job" ng-submit="PtJobCtrl.postJob(post_job.$valid)" novalidate>
					<div class="row">
						<div class="col-lg-4">
							<div class="form-group">
								<label for="job_title">Job Title*</label>
							  	<input type="text" class="form-control" id="job_title" name="job_title" ng-model="PtJobCtrl.postJob1.job_title" value="" required>
							  	<div class="error-spacer"></div>
							  	<div ng-if="post_job.job_title.$error.required && PtJobCtrl.job_post_error" class="has-error-msg">Job Title Field is Required.</div>
							</div>
						</div>
						<div class="col-lg-4">
							<div class="form-group">
								<label for="job_func">Job Function*</label>
								<i class="fa fa-angle-down fa-feedback" style="color: #F46113"></i>
								<select class="form-control" id="job_func" name="job_func" ng-model="PtJobCtrl.postJob1.job_func" required ng-options="job_functions.job_function_name for job_functions in PtJobCtrl.job_function">
									<option selected disabled value="">Please Select</option>
								</select>
								<div class="error-spacer"></div>
								<div ng-if="post_job.job_func.$error.required && PtJobCtrl.job_post_error" class="has-error-msg">Job Function Field is Required.</div>
							</div>
						</div>
						<div class="col-lg-4">
							<div class="form-group">
								<label for="location">Location*</label>
								<input id="location" class="form-control" ng-model="PtJobCtrl.postJob1.location" name="location" ng-autocomplete="PtJobCtrl.geo_location" details="PtJobCtrl.geo_details" options="PtJobCtrl.geo_options" required class="has-error-border">
								<div class="error-spacer"></div>
								<div ng-if="post_job.location.$error.required && PtJobCtrl.job_post_error" class="has-error-msg">Location Field is Required.</div>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-lg-4">
							<div class="form-group">
								<label for="industry">Industry*</label>
								<i class="fa fa-angle-down fa-feedback" style="color: #F46113"></i>
								<select class="form-control" id="industry" ng-model="PtJobCtrl.postJob1.industry" name="industry" required ng-options="industry.industry_name for industry in PtJobCtrl.industry_list">
									<option  selected disabled value="">Please Select</option>
								</select>
								<div class="error-spacer"></div>
								<div ng-if="post_job.industry.$error.required && PtJobCtrl.job_post_error" class="has-error-msg">Industry Field is Required.</div>
							</div>
						</div>
						<div class="col-lg-4">
							<div class="form-group">
								<label for="emp_type">Employment Type*</label>
								<i class="fa fa-angle-down fa-feedback" style="color: #F46113"></i>
								<select class="form-control" id="emp_type" ng-model="PtJobCtrl.postJob1.emp_type" name="emp_type" required ng-options="employmentTypes.employment_type_name for employmentTypes in PtJobCtrl.employment_type">
									<option selected disabled value="">Please Select</option>
								</select>
								<div class="error-spacer"></div>
								<div ng-if="post_job.emp_type.$error.required && PtJobCtrl.job_post_error" class="has-error-msg">Employment Type Field is Required.</div>
							</div>
						</div>
						<div class="col-lg-4">
							<div class="form-group">
								<label for="experience">Experience*</label>
								<i class="fa fa-angle-down fa-feedback" style="color: #F46113"></i>
								<select class="form-control" id="experience" ng-model="PtJobCtrl.postJob1.experience" name="experience" required ng-options="experiences.experience_name for experiences in PtJobCtrl.experience">
									<option selected disabled value="">Please Select</option>
								</select>
								<div class="error-spacer"></div>
								<div ng-if="post_job.experience.$error.required && PtJobCtrl.job_post_error" class="has-error-msg">Experience Field is Required.</div>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-lg-4">
							<div class="form-group">
								<label for="pos-id">Position ID</label>
								<input type="text" class="form-control" id="pos-id" value="" ng-model="PtJobCtrl.postJob1.position_id">
							</div>
						</div>
						<div class="col-lg-4">
							<div class="form-group">
								<label for="req-id">Requisition Id</label>
								<input type="text" class="form-control" id="req-id" value="" ng-model="PtJobCtrl.postJob1.requistion_id">
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-lg-12">
							<div class="form-group">
								<label for="job_desc">Job Description*</label>
								<textarea class="form-control" id="job_desc" rows="6" ng-model="PtJobCtrl.postJob1.job_desc" name="job_desc" required maxlength="250"></textarea>
								<div class="error-spacer"></div>
								<div>
									<div ng-if="post_job.job_desc.$error.required && PtJobCtrl.job_post_error" class="has-error-msg">Job Description Field is Required.</div>
								    <span class="max_length">Remaining {{250 - PtJobCtrl.postJob1.job_desc.length}} / 250 left</span>
								</div>
							</div>
						</div>
					</div>
					<!-- <div class="row">
						<div class="col-lg-12">
							<div class="form-group">
								<label for="company-description">Company Description*</label>
								<textarea class="form-control" rows="6" id="company-description">Lorem Ipsum is simply dummy text of  the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknow printer took a gallery of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting , remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passanges, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</textarea>
							</div>
						</div>
					</div> -->
					<div class="text-center" style="padding: 50px 0;">
						<button class="btn btn-style" style="padding: 12px 32px;">CONTINUE&nbsp;&nbsp;<img src="public/images/arrow-buttons.svg" style="margin-top: -2px;"></button>
					</div>
				</form>
			</div>
		</div>
	</section>

</div>
