
<div class="post-job">

	<section>
		<div class="container" style="padding-bottom: 80px;">
			<div class="job-title">
				<!-- <img src="" alt="enterpi"> -->
				<span class="company-name">Enterpi</span>
				<h2 class="text-center">Create Your Request</h2>
			</div>

			<div class="content">
				<form role="form" name="post_job" ng-submit="PtJobCtrl.postJob(post_job.$valid)" novalidate>
					<div class="row">
						<div class="col-lg-4">
							<div class="form-group">
								<label for="job_title">Job Title*</label>
							  	<input type="text" class="form-control" id="job_title" name="job_title" ng-model="job_title" value="" required ng-class="{'has-error-border':post_job.job_title.$invalid && PtJobCtrl.job_post_error}">
							  	<div ng-if="post_job.job_title.$error.required && PtJobCtrl.job_post_error" class="has-error-msg">Job Title Field is Required.</div>
							</div>
						</div>
						<div class="col-lg-4">
							<div class="form-group">
								<label for="job_func">Job Function*</label>
								<i class="fa fa-angle-down fa-feedback" style="color: #F46113"></i>
								<select class="form-control" id="job_func" name="job_func" ng-model="job_func" ng-class="{'has-error-border':post_job.job_func.$invalid && PtJobCtrl.job_post_error}" required>
									<option selected disabled>Please Select</option>
									<option ng-repeat="job_functions in PtJobCtrl.job_function">{{job_functions.job_function_name}}</option>
								</select>
								<div ng-if="post_job.job_func.$error.required && PtJobCtrl.job_post_error" class="has-error-msg">Job Function Field is Required.</div>
							</div>
						</div>
						<div class="col-lg-4">
							<div class="form-group">
								<label for="location">Location*</label>
								<!-- <i class="fa fa-angle-down fa-feedback" style="color: #F46113"></i> -->
								<!-- <select class="form-control" id="location">
									<option selected disabled>Please Select</option>
									<option ng-repeat="location in PtJobCtrl.location">{{loc}}</option>
								</select> -->
								<!-- <input id="location" class="form-control"> -->
								<input id="location" class="form-control" ng-model="location" name="location"  ng-class="{'has-error-border':post_job.location.$invalid && PtJobCtrl.job_post_error}" required class="has-error-border">
								<div ng-if="post_job.location.$error.required && PtJobCtrl.job_post_error" class="has-error-msg">Location Field is Required.</div>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-lg-4">
							<div class="form-group">
								<label for="industry">Industry*</label>
								<i class="fa fa-angle-down fa-feedback" style="color: #F46113"></i>
								<select class="form-control" id="industry" ng-model="industry" name="industry" ng-class="{'has-error-border':post_job.industry.$invalid && PtJobCtrl.job_post_error}" required>
									<option selected disabled>Please Select</option>
									<option ng-repeat="industries in PtJobCtrl.industry">{{industries.industry_name}}</option>
								</select>
								<div ng-if="post_job.industry.$error.required && PtJobCtrl.job_post_error" class="has-error-msg">Industry Field is Required.</div>
							</div>
						</div>
						<div class="col-lg-4">
							<div class="form-group">
								<label for="emp_type">Employment Type*</label>
								<i class="fa fa-angle-down fa-feedback" style="color: #F46113"></i>
								<select class="form-control" id="emp_type" ng-model="emp_type" name="emp_type" ng-class="{'has-error-border':post_job.emp_type.$invalid && PtJobCtrl.job_post_error}" required>
									<option selected disabled>Please Select</option>
									<option ng-repeat="employmentTypes in PtJobCtrl.employment_type">{{employmentTypes.employment_type_name}}</option>
								</select>
								<div ng-if="post_job.emp_type.$error.required && PtJobCtrl.job_post_error" class="has-error-msg">Employment Type Field is Required.</div>
							</div>
						</div>
						<div class="col-lg-4">
							<div class="form-group">
								<label for="experience">Experience*</label>
								<i class="fa fa-angle-down fa-feedback" style="color: #F46113"></i>
								<select class="form-control" id="experience" ng-model="experience" name="experience" ng-class="{'has-error-border':post_job.experience.$invalid && PtJobCtrl.job_post_error}" required>
									<option selected disabled>Please Select</option>
									<option ng-repeat="experiences in PtJobCtrl.experience">{{experiences.experience_name}}</option>
								</select>
								<div ng-if="post_job.experience.$error.required && PtJobCtrl.job_post_error" class="has-error-msg">Experience Field is Required.</div>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-lg-4">
							<div class="form-group">
								<label for="pos-id">Position ID</label>
								<input type="text" class="form-control" id="pos-id" value="">
							</div>
						</div>
						<div class="col-lg-4">
							<div class="form-group">
								<label for="req-id">Requistion Id</label>
								<input type="text" class="form-control" id="req-id" value="">
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-lg-12">
							<div class="form-group">
								<label for="job_desc">Job Description*</label>
								<textarea class="form-control" id="job_desc" rows="6" ng-model="job_desc" name="job_desc" ng-class="{'has-error-border':post_job.job_desc.$invalid && PtJobCtrl.job_post_error}" required></textarea>
								<div ng-if="post_job.job_desc.$error.required && PtJobCtrl.job_post_error" class="has-error-msg">Job Description Field is Required.</div>
							</div>
						</div>
					</div>
					<!-- <div class="row">
						<div class="col-lg-12">
							<div class="form-group">
								<label for="company-description">Company Description*</label>
								<textarea class="form-control" rows="6" id="company-description">Lorem Ipsum is simply dummy text of  the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknow printer took a gallery of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting , remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passanges, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</textarea>
							</div>
						</div>
					</div> -->
					<div class="text-center" style="padding: 50px 0;">
						<button class="btn btn-style" style="padding: 12px 32px;">CONTINUE&nbsp;&nbsp;<img src="public/images/arrow-buttons.svg" style="margin-top: -2px;"></button>
					</div>
				</form>
			</div>
		</div>
	</section>

</div>
