
<div class="sub-header">
	<div class="container">
		<div class="row">
			<div class="col-sm-5 sub_left">
				<div class="mid-nav">
					<h3>
						<a ui-sref="^.job" style="min-width:100px;"><img src="public/images/back-arrow.svg" alt="back" style="margin-bottom: 4px;">
						<span style="min-width:100px;">{{RewardCtrl.job_title | uppercase}}</span></a>
					</h3>
					<span class="openbox" style="margin:0">OPEN</span>
				</div>
				<ul>
					<li><a ui-sref="^.jobDetails({post_id:RewardCtrl.post_id})" ui-sref-active="active">JOB DETAILS</a></li>
					<li><a ui-sref="^.engagement/contacts({post_id:RewardCtrl.post_id})" ui-sref-active="active">ENGAGEMENT/CONTACTS</a></li>
					<li><a ui-sref="^.rewards({post_id:RewardCtrl.post_id})" ui-sref-active="active">REWARDS</a></li>
				</ul>
			</div>
			<div class="col-sm-7 text-center sub-right">
				<ul>
					<li>
						<h3>{{RewardCtrl.subHeaderCount.invited_count}}</h3>
						<span><img src="public/images/invited-header.svg" alt="invited">INVITED</span>
					</li>
					<li>
						<h3>{{RewardCtrl.subHeaderCount.referral_count}}</h3>
						<span><img src="public/images/referrals-header.svg" alt="referral">REFERRALS</span>
					</li>
					<li>
						<h3>{{RewardCtrl.subHeaderCount.pending_count}}</h3>
						<span><img src="public/images/referrals-header.svg" alt="pending">PENDING</span>
					</li>
					<li>
						<h3>{{RewardCtrl.subHeaderCount.accepted_count}}</h3>
						<span><img src="public/images/Applied.svg" alt="accepetd"></i>ACCEPTED</span>
					</li>
					<li>
						<h3>{{RewardCtrl.subHeaderCount.hired_count}}</h3>
						<span><img src="public/images/hired-header.svg" alt="hired">HIRED</span>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>



<div class="rewards">
	<div class="container">
		<div class="header clearfix">
			<h2 class="pull-left">Total Rewards for Referrals</h2>
			<span class="pull-right total col-lg-2 text-right text-hired">&#36; 0.00</span>
		</div>
		<div class="rewards-list">
			<div class="row clearfix">
				<div class="col-lg-12">
					<ul>
						<li class="t_head clearfix">
							<div class="col-lg-4">
								NAME
							</div>
							<div class="col-lg-4">
								REFERRED
							</div>
							<div class="col-lg-2">
								REWARDED ON
							</div>
							<div class="col-lg-2 text-right">
								REWARDED
							</div>
						</li>
						<li class="clearfix" ng-repeat="reward in RewardCtrl.rewards[0].referred" ng-if="reward.status == 'Accepted'">
							<div class="col-lg-4">
								<div class="pull-left">
									<img ng-src="public/images/Ui_Faces/{{reward.referred_by}}.jpg" class="img-responsive img-circle border-default">
								</div>
								<div class="content pull-left">
									<span class="text-name">{{reward.referred_by}}</span>
									<p>{{reward.ref_designation}}</p>
								</div>
							</div>
							<div class="col-lg-4">
								<div class="pull-left">
									<img ng-src="public/images/Ui_Faces/{{reward.name}}.jpg" class="img-responsive img-circle border-default">
								</div>
								<div class="content pull-left">
									<big>{{reward.name}}</big>
									<p>{{reward.designation}}</p>
								</div>
							</div>
							<div class="col-lg-2">
								<span class="time">{{reward.time}}&nbsp;&nbsp;<img src="public/images/time.svg" alt="clock"></span>
							</div>
							<div class="col-lg-2 text-right">
								<span class="text-hired reward">&#36; {{reward.rewarded}}</span>
							</div>
						</li>
					</ul>
				</div>
			</div>
		</div>
		
	</div>
</div>