<link rel="stylesheet" type="text/css" href="public/css/style.css">
<div class="settings">
	<div class="sub-header">
		<div class="container">
			<ul>
				<li><a ui-sref="^.settings.companyProfile" ui-sref-active="active" style="margin-left:0;">COMPANY PROFILE</a></li>
				<li><a ui-sref="^.settings.myProfile" ui-sref-active="active">MY PROFILE</a></li>
				<li><a ui-sref="^.settings.userProfile" ui-sref-active="active">USER PROFILE</a></li>
			</ul>
		</div>
	</div>

	<div ui-view></div>
</div>