<div class="user-profile">
	<div class="container">
		<div class="row">
			<div class="col-sm-3">
				<div class="users">
					<span class="add-user">+ ADD USER</span>
					<md-input-container class="md-block">
                        <label>Search Users</label>
                        <img src="public/images/search.svg" alt="search" class="feedback">
                        <input type="text" name="search" ng-model="UserProfileCtrl.search">
                    </md-input-container>
                    <ul>
                    	<li ng-repeat="users in UserProfileCtrl.users | filter: { user : UserProfileCtrl.search }" ng-click="UserProfileCtrl.getUserData(users)" ng-class="{'active':UserProfileCtrl.activeClass == users.user}">
                    		<img ng-src="{{users.image == '' || users.image == null ? 'public/images/avatar.png' : users.image}}" alt="user_dp" class="img-circle">
                    		<span ng-bind="users.user" class="name ellipsis" style="width:75%;"></span>
                    	</li>
                    </ul>
				</div>
			</div>
			<div class="col-sm-9" style="padding-left:0;">
				<div class="user-data">
					<div class="head clearfix">
						<div class="pull-left">
							<span class="image">
								<img ng-src="{{UserProfileCtrl.userHeaderList.image == '' || UserProfileCtrl.userHeaderList.image == null ? 'public/images/avatar.png' : UserProfileCtrl.userHeaderList.image}}" alt="user_dp" ng-style="{'border-color': UserProfileCtrl.userHeaderList.image == '' || UserProfileCtrl.userHeaderList.image == null ? 'transparent' : '#04a3ff'}" class="img-circle" style="border:2px solid">
							</span>
							<span class="text">
								<h3 ng-bind="UserProfileCtrl.userHeaderList.user" class="ellipsis" style="width:100%;margin:0"></h3>
								<p ng-bind="UserProfileCtrl.userHeaderList.designation" class="ellipsis" style="width:100%"></p>
							</span>
						</div>
						<div class="pull-right">
							<span>RESET PASSWORD</span>
						</div>
					</div>
					<div class="content">
						<div class="clearfix">
							<form name="user_details_form" novalidate>
				                <div class="pull-left" style="margin-right:50px;">
				                    <md-input-container class="md-block">
				                        <label>NAME</label>
				                        <input type="text" name="name" ng-model="UserProfileCtrl.userDetails.user" required ng-class="{'has-error-border':user_details_form.name.$invalid && UserProfileCtrl.errCond}">
				                        <div ng-if="user_details_form.name.$error.required && UserProfileCtrl.errCond" class="has-error-msg">Please Enter Name</div>
				                    </md-input-container>
				                    <md-input-container class="md-block">
				                        <label>EMAIL</label>
				                        <input type="text" name="emailid" ng-model="UserProfileCtrl.userDetails.email" required ng-pattern="/^[a-z0-9A-Z._%+-]+@[a-zA-Z]+\.[a-z]{2,3}$/" ng-class="{'has-error-border':user_details_form.emailid.$invalid && UserProfileCtrl.errCond}">
				                        <div ng-if="user_details_form.emailid.$error.required && UserProfileCtrl.errCond" class="has-error-msg">Please Enter Email Address</div>
				                        <div ng-if="user_details_form.emailid.$error.pattern && UserProfileCtrl.errCond" class="has-error-msg">Please Enter Valid Email Address</div>
				                    </md-input-container>
				                     <md-input-container class="md-block select-box">
				                        <label style="display:none">STATUS</label>
				                        <md-select name="status" ng-model="UserProfileCtrl.userDetails.status">
				                            <md-option ng-repeat="status in UserProfileCtrl.statusText" ng-value="status">{{status}}</md-option>
				                        </md-select>
				                    </md-input-container>
				                </div>
				                <div class="pull-left">
				                    <md-input-container class="md-block">
				                        <label>DESIGNATION</label>
				                        <input type="text" name="designation" ng-model="UserProfileCtrl.userDetails.designation" required ng-class="{'has-error-border':user_details_form.designation.$invalid && UserProfileCtrl.errCond}">
				                        <div ng-if="user_details_form.designation.$error.required && UserProfileCtrl.errCond" class="has-error-msg">Please Enter Designation</div>
				                    </md-input-container>
				                    <md-input-container class="md-block">
				                        <label>LOCATION</label>
				                        <input type="text" name="location" ng-model="UserProfileCtrl.userDetails.location" ng-class="{'has-error-border':user_details_form.location.$invalid && UserProfileCtrl.errCond}">
				                        <div ng-if="user_details_form.location.$error.pattern && UserProfileCtrl.errCond" class="has-error-msg">Please Enter Location</div>
				                    </md-input-container>
				                </div>
			            	</form>
		                </div>

			                <!-- Permissions -->
		                <div class="user-management clearfix">
		                	<div class="pull-left">
			                	<form class="" name="user_management_form">
				                	<div class="permissions">
				                		<p>Permissions</p>
			                			<div class="form-group">
										  	<label for="type" class="control-label">User Type</label>
										  	<div class="pull-right" style="margin-top: -10px;">
										  		<select class="form-control" id="type" name="user_type">
											    	<option value="manager">Manager</option>
											    	<option value="employee">Employee</option>
											    	<option value="client">Client</option>
											    	<option value="others">Others</option>
											  	</select>
											</div>
										</div>
										<div class="form-group">
										  	<label class="control-label">Dashboard</label>
										  	<div class="pull-right radio-switch" style="margin-top: -10px;">
										  		<label>
										  			<input type="radio" name="dashboard_permissions" value="yes" checked>
										  			<span>Yes</span>
									  			</label>
										  		<label>
										  			<input type="radio" name="dashboard_permissions" value="no">
										  			<span>No</span>
									  			</label>
											</div>
										</div>
				                	</div>
				                	<div class="jobs">
				                		<p>Jobs</p>
				                		<div class="form-group">
										  	<label class="control-label">See All jobs</label>
										  	<div class="pull-right radio-switch" style="margin-top: -10px;">
										  		<label>
										  			<input type="radio" name="see_jobs_permissions" value="yes" checked>
										  			<span>Yes</span>
									  			</label>
										  		<label>
										  			<input type="radio" name="see_jobs_permissions" value="no">
										  			<span>No</span>
									  			</label>
											</div>
										</div>
										<div class="form-group">
										  	<label class="control-label">Add Jobs</label>
										  	<div class="pull-right radio-switch" style="margin-top: -10px;">
										  		<label>
										  			<input type="radio" name="add_jobs_permissions" value="yes" checked>
										  			<span>Yes</span>
									  			</label>
										  		<label>
										  			<input type="radio" name="add_jobs_permissions" value="no">
										  			<span>No</span>
									  			</label>
											</div>
										</div>
										<div class="form-group">
										  	<label class="control-label">Edit Jobs</label>
										  	<div class="pull-right radio-switch" style="margin-top: -10px;">
										  		<label>
										  			<input type="radio" name="edit_jobs_permissions" value="yes" checked>
										  			<span>Yes</span>
									  			</label>
										  		<label>
										  			<input type="radio" name="edit_jobs_permissions" value="no">
										  			<span>No</span>
									  			</label>
											</div>
										</div>
				                	</div>
				                	<div class="user">
				                		<p>User</p>
				                		<div class="form-group">
										  	<label class="control-label">Add User</label>
										  	<div class="pull-right radio-switch" style="margin-top: -10px;">
										  		<label>
										  			<input type="radio" name="add_user_permissions" value="yes" checked>
										  			<span>Yes</span>
									  			</label>
										  		<label>
										  			<input type="radio" name="add_user_permissions" value="no">
										  			<span>No</span>
									  			</label>
											</div>
										</div>
										<div class="form-group">
										  	<label class="control-label">Edit User</label>
										  	<div class="pull-right radio-switch" style="margin-top: -10px;">
										  		<label>
										  			<input type="radio" name="edit_user_permissions" value="yes" checked>
										  			<span>Yes</span>
									  			</label>
										  		<label>
										  			<input type="radio" name="edit_user_permissions" value="no">
										  			<span>No</span>
									  			</label>
											</div>
										</div>
				                	</div>
				                </form>
				            </div>
		                </div>

		                	<!-- Footer -->
	                	<div class="footer">
	                		<div class="pull-left">
        						<span ng-if="UserProfileCtrl.updateLoader" style="line-height:50px;">
        							<img src="public/images/loader/upload_file.gif" alt="loader" style="margin:5px;"> Updating
    							</span>
	                		</div>
	                		<div class="pull-right">
	                			<span class="btn-cancel">CANCEL</span>
	                			<span class="btn-update" ng-click="UserProfileCtrl.updateChanges(user_details_form.$valid)">UPDATE CHANGES</span>
	                		</div>
	                	</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>