<link rel="stylesheet" type="text/css" href="public/css/contacts.css">
<div class="upload-contacts">
	<section>
		<div class="container">
			<a class="head" ui-sref="app.contact">
				<img src="public/images/arrow-back-grey.svg" alt="arrow-back">
				<span>ADD CONTACT BUCKET</span>
			</a>
			<div class="box">
				<div class="box-content text-center">
					<div class="heading">
						<h3 style="margin:0">Upload Contacts</h3>
						<p style="margin:16px 0;">
							<img src="public/images/info.svg" alt="info"/>
							<span>Organize your contacts in one of the groups below or create your own</span>
						</p>
					</div>
					<div class="file-uploading">
						<div class="row">
							<div class="col-sm-4" ng-repeat="bucketList in UploadContCtrl.bucketsList" ng-init="colorCode = UploadContCtrl.colorPicker($index)">
								<!-- qq uploader -->
								<div class="upload-bucket" ng-style="{'background':colorCode,'border-color':colorCode}"></div>
								
								<p ng-click="UploadContCtrl.downloadSample()" class="text-center">DOWNLOAD TEMPLATE</p>
							</div>
							<div class="col-sm-4">
								<div class="upload-bucket" ng-click="UploadContCtrl.uploadModal()">
									<p class="own"><i class="fa fa-plus" style="margin-right:3px;"></i>Add Your Own</p>
								</div>
								<p ng-click="UploadContCtrl.downloadSample()" class="text-center">DOWNLOAD TEMPLATE</p>
							</div>
						</div>
					</div>
				</div>
				<div class="box-footer">
					<div class="pull-right">
						<a ui-sref="app.contact"><span class="btn-cancel">Cancel</span></a>
					    <span class="btn-add">ADD CONTACTS</span>
					</div>
				</div>
			</div>
		</div>
	</section>
</div>