<link rel="stylesheet" type="text/css" href="public/css/contacts.css">
<div class="upload-contacts">
	<section>
		<div class="container">
			<a class="head">
				<img src="public/images/arrow-back-grey.svg" alt="arrow-back">
				<span>ADD CONTACT BUCKET</span>
			</a>
			<div class="box">
				<div class="box-content text-center">
					<div class="heading">
						<h3 style="margin:0">Upload Contacts</h3>
						<p style="margin:16px 0;">
							<img src="public/images/info.svg" alt="info"/>
							<span>Organize your contacts in one of the groups below or create your own</span>
						</p>
					</div>
					<div class="file-uploading">
						<div class="row row-centered">
							<div class="col-sm-4 col-centered" ng-repeat="x in [1,2,3,4,5]">
								<div class="upload">
									
								</div>
								<p ng-click="UploadContCtrl.downloadSample()" class="text-center">DOWNLOAD TEMPLATE</p>
							</div>
						</div>
					</div>
				</div>
				<div class="box-footer">
					<div class="pull-right">
						<span class="btn-cancel">Cancel</span>
					    <span class="btn-add">ADD CONTACTS</span>
					</div>
				</div>
			</div>
		</div>
	</section>
</div>