<link rel="stylesheet" type="text/css" href="public/css/contacts.css">
<div class="upload-contacts">
	<section>
		<div class="container">
			<div class="head">
				<a class="head" ui-sref="app.contact">
					<img src="public/images/arrow-back-grey.svg" alt="arrow-back">
				</a>
				<span>ADD CONTACT BUCKET</span>
			</div>
			<div class="box">
				<div class="box-content text-center">
					<div class="heading">
						<h3 style="margin:0">Upload Contacts</h3>
						<p style="margin:16px 0;">
							<img src="public/images/info.svg" alt="info"/>
							<span>Organize your contacts in one of the groups below or create your own</span>
						</p>
					</div>
					<div class="file-uploading">
						<form role="form" name="upload_contacts_form">
							<div class="row">
								<div class="col-sm-4" ng-repeat="bucketList in UploadContCtrl.bucketsList" ng-init="colorCode = UploadContCtrl.colorPicker($index)">
									<!-- qq uploader -->
									<div class="upload-bucket" ng-style="{'background':colorCode,'border-color':colorCode}"></div>
									
									<p ng-click="UploadContCtrl.downloadSample()" class="text-center">DOWNLOAD TEMPLATE</p>
								</div>
								<div class="col-sm-4">
									<div class="upload-bucket" ng-click="UploadContCtrl.uploadModal()">
										<p class="own"><i class="fa fa-plus" style="margin-right:3px;"></i>Add Your Own</p>
									</div>
									<p ng-click="UploadContCtrl.downloadSample()" class="text-center">DOWNLOAD TEMPLATE</p>
								</div>
							</div>
						</form>
					</div>
				</div>
				<div class="box-footer">
					<div class="pull-left" ng-if="UploadContCtrl.errorUpload" style="color: #983a3a;line-height: 48px;">
						<span><i class='fa fa-times'></i>&nbsp;Please Upload Atleash One Bucket</span>
					</div>
					<div class="pull-right">
						<a ui-sref="app.contact"><span class="btn-cancel">Cancel</span></a>
					    <span class="btn-add" ng-click="UploadContCtrl.uploadContacts()">ADD CONTACTS<img src="public/images/loader/dot.svg" alt="dot" ng-if="UploadContCtrl.uploadLoader" ng-style="{'pointer-events':UploadContCtrl.uploadLoader ? 'none' : 'auto'}"/></span>
					</div>
				</div>
			</div>
		</div>
	</section>
</div>