<link rel="stylesheet" type="text/css" href="public/css/choosen/choosen.jquery.css">
<script type="text/javascript" src="public/js/vendor/choosen.jquery.js"></script>
<div class="candidates">
	<div class="sub-header">
		<div class="container">
			<ul>
				<li><a ui-sref="^.candidates.resumeRoom" ui-sref-active="active"><span class="background two"></span><span class="text">RESUME ROOM</span></a></li>
				<li><a ui-sref="^.candidates.uploadResume" ui-sref-active="active"><span class="background two"></span><span class="text">UPLOAD RESUME</span></a></li>
				<li><a ui-sref="^.candidates.findResume" ui-sref-active="active"><span class="background two"></span><span class="text">FIND RESUME</span></a></li>
			</ul>
		</div>
	</div>
    <div ui-view class="animated fadeIn"></div>
</div>