<div class="resume-room">
	<div class="container">
		<div class="row">
			<div class="col-sm-12" style="padding-bottom:50px">
				<div class="box">
					<div class="box-header clearfix">
							
						<div class="col-sm-4">
							<span>CANDIDATES ( <span ng-bind="ResumeRoomCtrl.totalRecords || 0"></span> ) </span>
						</div>
						<form name="filter_form" style="display:inline-block">
							<md-input-container>
						        <label style="display:none !important">Filter By Status</label>
						        <md-select ng-model="ResumeRoomCtrl.filterList" md-on-close="ResumeRoomCtrl.applyFilter()"
						        	data-md-container-class="multiple-select" multiple placeholder="Filter By Status">
						          	<md-select-header class="demo-select-header">
							            <input ng-model="searchTerm" type="search" placeholder="Select Status"
							            	class="demo-header-searchbox md-text">
						          	</md-select-header>
					            	<md-option ng-value="status" ng-repeat="status in ResumeRoomCtrl.filterOptions">{{status}}</md-option>
						        </md-select>
				      		</md-input-container>
				      		<input type="hidden" name="filter" value="{{ResumeRoomCtrl.filterList}}">
						</form>
						<div class="col-sm-3 pull-right">
							<div data-epi-search data-opts="ResumeRoomCtrl.search_opts"></div>
						</div>
					</div>
					<div class="box-content">
						<div id="grid" ui-grid="ResumeRoomCtrl.gridOptions" class="grid" ui-grid-selection style="border: 0;">
							<div class="grid-msg-overlay" ng-if="ResumeRoomCtrl.loader">
					          	<div class="msg">
					            	<span>
					              		<img src="public/images/loader/spin.gif" alt="loader" width="25%">
					            	</span>
					          	</div>
					   		</div>
					   		<div class="grid-msg-overlay" ng-if="ResumeRoomCtrl.noCandidates">
						        <div class="msg">
						        	<span>No Candidates Found</span>
						        </div>
					    	</div>
						</div>
					</div>
					<div class="box-footer clearfix">
						<div class="status col-sm-4">
							<span style="padding-right:10px;">Change Status to:</span>
				            <md-select name="status" ng-model="ResumeRoomCtrl.status" placeholder="Status" class="md-no-underline" ng-change="ResumeRoomCtrl.statusChange(ResumeRoomCtrl.status)" ng-disabled="ResumeRoomCtrl.countArr.length==0">
				              	<md-option ng-repeat="options in ResumeRoomCtrl.statusOptions" ng-value="options">
				                	{{options}}
				              	</md-option>
				            </md-select>
						</div>
						<div class="paging col-sm-4 text-center">
							<div ng-if="ResumeRoomCtrl.totalRecords">												
								<ul uib-pagination total-items="ResumeRoomCtrl.totalRecords" ng-model="ResumeRoomCtrl.pageNumber" max-size="3" direction-links="false" force-ellipses="true" ng-change="ResumeRoomCtrl.pageChanged(ResumeRoomCtrl.pageNumber)" boundary-link-numbers="true" rotate="false" ng-if="ResumeRoomCtrl.totalRecords > 10"></ul>
							</div>
						</div>
						<div class="pull-right col-sm-4 text-right">
							<span ng-bind="ResumeRoomCtrl.selectionCount"></span>
							<span class="download">DOWNLOAD RESUME</span>
						</div>
					</div>
				</div>
			</div>
		</div>

	</div>
</div>


<!--cellTemplate for status change like Accept or Decline-->
<script type="text/ng-template" id="status-change.html">
	<div class="ui-grid-cell-contents ui-grid-status">
		<div ng-switch on="COL_FIELD">
			<div ng-switch-when="PENDING" class="pending">
				<img class="pull-left" src="public/images/tickmark-accept.svg" alt="accept" ng-click="grid.appScope.statusUpdate(row, 1);$event.stopPropagation()">
				{{ COL_FIELD }}
				<img class="pull-right" alt="decline" src="public/images/closemark-decline.svg" ng-click="grid.appScope.statusUpdate(row, 0);$event.stopPropagation()">
			</div>
			<div ng-switch-when="DECLINED" class="declined">
				<div class="decline-img"></div>
				{{ COL_FIELD }}
			</div>
			<div ng-switch-when="ACCEPTED" class="accepted">
				<div class="accept-img"></div>
				{{ grid.appScope.awtStatus(row) }}
			</div>
			<div ng-switch-default class="status-default">
				{{ COL_FIELD }}
			</div>
		</div>
	</div>
</script>

<script type="text/ng-template" id="download-resume.html">
	<div class="ui-grid-cell-contents ui-grid-download" title="{{ COL_FIELD }}">
		<a href="{{grid.appScope.downloadResume(row)}}" download ng-click="$event.stopPropagation()">
			<div class="download" ng-click="grid.appScope.downloadResume(row)"></div>
		</a>
		<a href="{{$root.base_url+'viewer?url='+grid.appScope.downloadResume(row)}}" title="" target="_blank">{{ COL_FIELD }}</a>
	</div>
</script>