<div class="candidates">
	<div class="sub-header">
		<div class="container">
			<ul>
				<li><a ui-sref="^.contact.Internal" ui-sref-active="active"><span class="background two"></span><span class="text">INTERNAL COMMUNITIES</span></a></li>
				<li><a ui-sref="^.contact.External" ui-sref-active="active"><span class="background two"></span><span class="text">TALENT COMMUNITIES</span></a></li>
			</ul>
		</div>
	</div>
    <div ui-view class="animated fadeIn"></div>
</div>